### ISSUE TITLE
Error: Type 'TextCapalization ' not found

### ISSUE THREAD

**Issue by TheDeveloperYJ** [AbdulRahmanAlHamali/flutter_typeahead#1]
Importing the library and setting up the given example in the docs throws out the below error 
----------
final TextCapitalization textCapitalization;
compiler message:         ^
compiler message: file:///C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_typeahead-0.2.1/lib/flutter_typeahead.dart:1152:7: Error: Type 'TextCapitalization' not found.
compiler message:       TextCapitalization textCapitalization,
compiler message:       ^
compiler message: file:///C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_typeahead-0.2.1/lib/flutter_typeahead.dart:701:9: Error: No
named parameter with the name 'onEditingComplete'

**Comment by AbdulRahmanAlHamali** [comment]
Hello,

Thank you for using my package.

Could you please provide me with the output of the command

`flutter doctor`

I suspect that you're facing this problem because you don't have a version of Flutter older than 0.6.0

**Comment by TheDeveloperYJ** [comment]
Yeah it worked ! Thanks for resolving the issue and developing the package . It is really helpful !
