### ISSUE TITLE
TextFieldConfiguration onChange not being fired

### ISSUE THREAD

**Issue by chrise1967** [AbdulRahmanAlHamali/flutter_typeahead#108]
TextFieldConfiguration onChange not being fired. See follow example code.  The onChanged print(value) does not get called when entering text.

`

Widget build(BuildContext context) {
    return TypeAheadFormField(
      getImmediateSuggestions: true,
      textFieldConfiguration: TextFieldConfiguration(
        onChanged: (value) {
          print(value);
        },
      ),
      suggestionsCallback: (pattern) {
        return getSuggestions(pattern);
      },
      itemBuilder: (context, suggestion) {
        return ListTile(
          title: Text(suggestion),
        );
      },
      transitionBuilder: (context, suggestionsBox, controller) {
        return suggestionsBox;
      },
      noItemsFoundBuilder: (context) {
        return null;
      },
      onSuggestionSelected: (suggestion) {
        print(suggestion);
      },
    );
  }
`

**Comment by KaYBlitZ** [comment]
Found the problem. onChanged was overridden in TypeAheadFormField. Works if using just TypeAheadField though. I can push out a fix in a bit

**Comment by KaYBlitZ** [comment]
Fixed in 1.6.1

**Comment by kaciula** [comment]
@KaYBlitZ I'm seeing this issue in version 1.8.0. onChanged() is not being called for TypeAheadFormField.
