### ISSUE TITLE
Custom Focus Node prevents suggestions

### ISSUE THREAD

**Issue by IanGrantMarino** [AbdulRahmanAlHamali/flutter_typeahead#111]
It seems that passing a custom `FocusNode` to the `textFieldConfiguration` prevents suggestions from being displayed. Here is a basic sample app that should demonstrate this:
```dart
import 'package:flutter/material.dart';
import 'package:flutter_typeahead/flutter_typeahead.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData.light(),
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TypeAheadField(
          textFieldConfiguration: TextFieldConfiguration(
            focusNode: FocusNode(),
          ),
          suggestionsCallback: (_) => ['option 1', 'option 2'],
          itemBuilder: (context, suggestion) => ListTile(title: Text(suggestion)),
          onSuggestionSelected: (_) {},
        ),
      ),
    );
  }
}
```

The text field in this app doesn't show any suggestions but if the `focusNode: FocusNode(),` line is commented out then it shows the overlay suggesting the two options.

**Comment by fluttdev** [comment]
Can confirm that behaviour! Will there be a bug fix?

**Comment by kjmj** [comment]
Also having this issue. Looking for a workaround

**Comment by KaYBlitZ** [comment]
I've been testing this. Using the example by IanGrantMarino, the code does work with an external FocusNode. But when I use hot reload during testing, it breaks as described above. Can anyone else confirm this? Seems like a hot reload bug. If I completely close the app and start it again, the focus node will work again.

**Comment by ianspryn** [comment]
I think I found a different way to reproduce the bug.

I'm using your library as a way to list similar tags to what the user has typed, and then the user can tap a suggestion to insert it into the text field. As a result, the keyboard dismisses itself because I tapped outside of the text field. Since I want to keep the keyboard up, I say `focusNode.requestFocus()` in the `onSuggestionSelected` callback. When I do this, the `onSuggestionSelected` method is no longer called until I (in my specific case) close the `AlertDialog` that contains the `TypeAheadField` and reopen it.


Example below.


```
import 'package:flutter/material.dart';
import 'package:flutter_typeahead/flutter_typeahead.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData.light(),
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {

  final FocusNode focus = FocusNode();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TypeAheadField(
          textFieldConfiguration: TextFieldConfiguration(
            focusNode: focusNode,
          ),
          suggestionsCallback: (_) => ['option 1', 'option 2'],
          itemBuilder: (context, suggestion) => ListTile(title: Text(suggestion)),
          onSuggestionSelected: (_) {
            focusNode.requestFocus();
          },
        ),
      ),
    );
  }
}
```

**Comment by grangoni** [comment]
I'm having the same issue. Suggestions stop working when providing a FocusNode. Problem remains even after restarting the app.

**Comment by grangoni** [comment]
Actually, I just managed to make it it work with the following using the following constructor parameters: 
 focusNode = FocusNode(canRequestFocus: true, skipTraversal: true);
Hope it helps.

**Comment by chirastefan** [comment]
is there a fix or workaround for this issue? `focusNode = FocusNode(canRequestFocus: true, skipTraversal: true);` doesn't seem to work for me

**Comment by Tokenyet** [comment]
This also happend to me when I used `focusNode.requestFocus` in `onSuggestionSelected`.

If I want to make It work, I should click somewhere else, then back to `TextField`, then It will have this one-time usage again.

**Comment by baer999** [comment]
Still having this behaviour that it don't work with focusNode.

Working on Flutter Windows project and this code.
When eliminating focusNode then everything works fine (but I'm not able to requestFocus for this field within applicaton user flow which would be amazing).

I work with newest Flutter beta version 3.13.0-0.4.pre

`TypeAheadFormField(
      hideOnEmpty: true,
      hideOnLoading: true,
      hideSuggestionsOnKeyboardHide: false,
      textFieldConfiguration: TextFieldConfiguration(
          autofocus: true,
          focusNode: widget.focusNode,
          controller: widget.textEditingController),
      suggestionsCallback: (pattern) async {
        if (pattern.isEmpty || widget.basket.currentItem.variantOid == null) {
          return const Iterable<IngredientSearchItem>.empty();
        }
        return await MyApi().getIngredientsBySearch(
            widget.basket.currentItem.variantOid!, pattern);
      },
      itemBuilder: (context, suggestion) {
        return ListTile(title: Text(suggestion.ingredientName));
      },
      transitionBuilder: (context, suggestionsBox, controller) {
        return suggestionsBox;
      },
      onSuggestionSelected: (suggestion) {
        setState(() {
          widget.basket.updateCurrentIngredientItem(suggestion);
        });
        if (widget.onChanged != null) {
          widget.onChanged!();
        }
      },
    )`

Behaviour with focusNode is broken after the first Dropdown selection.
It works for the first time and afterwards there won't come any Popup / DropDown List again (if using focusNode).

A Fix would be amazing, if I can do anything to support pls let me know!
