### ISSUE TITLE
How to work with Data Model class instead of just Strings?

### ISSUE THREAD

**Issue by aytunch** [AbdulRahmanAlHamali/flutter_typeahead#113]
I get a list of Products from my backend and I convert the JSON objects in to a Product Model Class and keep them in a List<Product>.

Product class has lets say an id field and a name field.
I can display suggestions with product.name however i get an error when i click on the suggestion. Product is not a subclass of String. How can i get the whole product object when user clicks on a suggestion?

**Comment by aytunch** [comment]
[Similar issue is opened in flutter_form_builder which is dependent in this great package](https://github.com/danvick/flutter_form_builder/issues/21)

**Comment by deakjahn** [comment]
`suggestionsCallback˛ expects a `Future<List<T>>`, not a `Future<List<String>>`. Likewise, `onSuggestionSelected` passes a `T`. I have no problems using the package with non-String items.

But I did receive error messages some time ago until I realized that `.where()`, the filter I used to create my suggestion list, has lazy evaluation and that's not what the widget likes. Isn't this by any chance your problem, too? The solution is easy, just use `toList()` at the end to evaluate the iterable.

**Comment by aytunch** [comment]
@deakjahn Thanks for your input, can you please share a code snippet so I can try and see if it works. I am still having problems:/

**Comment by deakjahn** [comment]
I have a POCO, very simple:

class Part {
      String name;
      String number;
      List<int> groups;
      List<int> pages;
    
      Part({this.name, this.number, this.groups, this.pages});
    }

When I create the widget, I just use this type:

    Widget _buildSearch() => TypeAheadField<Part>(
          itemBuilder: (context, item) => _buildSuggestion(context, item),
          suggestionsCallback: (pattern) async => await _getMatches(pattern),
          onSuggestionSelected: (suggestion) => _showPart(suggestion),
          noItemsFoundBuilder: (context) => ErrorText(message: 'Part cannot be found'),
          errorBuilder: (context, error) => ErrorText(message: '$error'),
        );

(This calls my functions but there is nothing special about them, `_buildSuggestion()` just returns a `Row`. The more interesting one will be `_getMatches`:

    Future<List> _getMatches(String query) async {
      if (query.isEmpty)
        return <Part>[];
      else {
        final filtered = _parts.where((item) => item.name.toLowerCase().contains(query.toLowerCase()));
        return filtered.take(20).toList();
      }
    }

I return a maximum of 20 matching items. And when I return, I don't just return the result of `take()` but convert it to a list, forcing the otherwise lazy evaluation to actually happen and all list elements to be ready and finished. I think that's what you missed.

**Comment by fabiangruss** [comment]
Hi @aytunch ,

I do have the same problem when clicking on a suggestion, which is backed by a custom Model class. Displaying the list of suggestions based on the model is working fine, but clicking on the suggestion always throws the exception "...  is not a subtype of type 'String'. Did you solve that issue and if so, how?

Could you post the function behind your `onSuggestionSelected ` @deakjahn ?
That would be a great help. I can't seem to find my error here.

Thank you!

**Comment by deakjahn** [comment]
I could but you won't find anything interesting there:

    void _showPart(Part part) {
      if (part != null)
        // simply use part
        setState(() {
          _name = part.name;
        });
    }

Just as you would expect.
