### ISSUE TITLE
Hidden suggestions box is on the upper left of the screen that captures clicks

### ISSUE THREAD

**Issue by humazed** [AbdulRahmanAlHamali/flutter_typeahead#116]
Hidden suggestions box is on the upper left of the screen that captures clicks.

the box that captures the clicks.
![Screenshot_1563962392](https://user-images.githubusercontent.com/8838182/61784877-d3554e80-ae0a-11e9-851b-137033f07fa6.png)

example of a problem this causes.
![untitled](https://user-images.githubusercontent.com/8838182/61784886-d81a0280-ae0a-11e9-940b-5522c88b9f05.gif)

**Comment by diegoveloper** [comment]
Same error here, nice catch

**Comment by diegoveloper** [comment]
Hey @humazed  , I fixed the issue and sent a Pull request, meanwhile you can use the package in this way:

```
  flutter_typeahead:
    git:
      url: https://github.com/aeyrium/flutter_typeahead
```

**Comment by KaYBlitZ** [comment]
@diegoveloper I merged your PR, changing the code slightly by calling close() instead which should do the same thing. I actually tested both close() and your code, but I am still getting the problem described here.....
