### ISSUE TITLE
Bump keyboard_visibility version.

### ISSUE THREAD

**Issue by VyMajoris** [AbdulRahmanAlHamali/flutter_typeahead#126]
It seems that the keyboard_visibility:0.5.1 has a bug with the registration that causes issues with firebase messaging.

https://github.com/FirebaseExtended/flutterfire/issues/145#issuecomment-532635075

**Comment by KaYBlitZ** [comment]
I have updated the dependency. Feel free to create a new issue if you find another problem with this new version.
