### ISSUE TITLE
Open suggestions on focus / Close suggestion box

### ISSUE THREAD

**Issue by fluttdev** [AbdulRahmanAlHamali/flutter_typeahead#133]
Hi,

first of all thanks for the great library! Got two questions about it.

1. Is it possible to open the suggestions box when the empty text field gets focus?

2. After closing the keyboard the suggestion box stays open with hideSuggestionsOnKeyboardHide: false. But how to close it? A tap somewhere next to it doesn't close it :/

Thanks for your help!

**Comment by KaYBlitZ** [comment]
Hi,

1. There should be a property for getImmediateSuggestions or something
similar that does what you want.

2. The textbox would have to lose focus by selecting one. Or you can pass a
suggestions box controller to typeahead and call close on the controller.

**Comment by fluttdev** [comment]
Thanks for your  answer!

Using getImmediateSuggestions fetches suggestions immediately when the field is added to the view. But I want the user to tap on the textfield first. I tried to get this behaviour with a custom suggestions box controller and a custom focusNode but ran into this issue:
https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/111

**Comment by rockingdice** [comment]
I've made a PR to fix this issue. Please try it. The animation is not good enough but working.

**Comment by MartinJLee** [comment]
I have noticed that it will call suggestionsCallback on focus. It would be nice if it can use cached one instead.
