### ISSUE TITLE
A TextEditingController was used after being disposed.

### ISSUE THREAD

**Issue by talamaska** [AbdulRahmanAlHamali/flutter_typeahead#136]
So following best practices I do dispose my textcontroller in the dispose, but 
but internally in the SuggestionsListState 
```
  @override
  void dispose() {
    _animationController.dispose();
    super.dispose();
    widget.controller.removeListener(this._controllerListener);
  }

```
for some reason is called after my parent dispose and I get an exception

```
════════ Exception caught by widgets library ═════════
The following assertion was thrown while finalizing the widget tree:
A TextEditingController was used after being disposed.

Once you have called dispose() on a TextEditingController, it can no longer be used.
When the exception was thrown, this was the stack
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> 
package:flutter/…/foundation/change_notifier.dart:105
#1      ChangeNotifier._debugAssertNotDisposed 
package:flutter/…/foundation/change_notifier.dart:111
#2      ChangeNotifier.removeListener 
package:flutter/…/foundation/change_notifier.dart:166
#3      _SuggestionsListState.dispose 
package:flutter_typeahead/flutter_typeahead.dart:1085
#4      StatefulElement.unmount 
package:flutter/…/widgets/framework.dart:4142
...
══════════════════════════════════════════════════════════
````

flutter doctor
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.18362.476], locale bg-BG)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.40.2)

**Comment by KaYBlitZ** [comment]
Thanks for the bug report. I think a check for null via will fix this `widget.controller?.removeListener(this._controllerListener);` Will add in the next release.

**Comment by sterlp** [comment]
I still have this issue of some reason but only in a widget test not in the running code:

`
The following assertion was thrown while finalizing the widget tree:
A TextEditingController was used after being disposed.
Once you have called dispose() on a TextEditingController, it can no longer be used.

When the exception was thrown, this was the stack:
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:106:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:112:6)
#2      ChangeNotifier.removeListener (package:flutter/src/foundation/change_notifier.dart:167:12)
#3      _SuggestionsListState.dispose (package:flutter_typeahead/flutter_typeahead.dart:1102:24)
#4      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4729:12)
#5      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1922:13)
#6      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#7      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5817:14)
#8      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#9      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#10     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#11     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#12     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#13     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#14     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#15     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#16     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#17     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#18     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#19     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#20     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#21     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#22     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5929:16)
#23     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#24     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#25     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#26     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#27     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#28     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#29     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#30     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#31     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5817:14)
#32     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#33     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#34     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#35     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#36     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#37     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5817:14)
#38     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#39     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#40     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5817:14)
#41     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#42     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#43     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#44     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#45     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#46     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#47     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#48     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#49     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#50     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#51     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#52     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#53     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#54     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#55     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#56     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#57     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#58     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#59     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#60     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#61     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#62     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#63     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#64     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#65     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#66     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#67     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#68     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#69     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#70     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#71     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#72     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#73     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#74     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#75     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#76     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5817:14)
#77     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#78     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#79     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#80     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#81     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#82     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#83     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#84     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#85     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#86     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#87     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#88     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#89     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#90     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#91     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#92     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#93     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#94     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5817:14)
#95     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#96     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#97     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#98     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#99     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#100    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#101    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#102    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#103    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#104    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#105    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#106    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#107    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#108    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#109    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#110    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#111    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#112    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#113    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#114    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#115    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#116    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#117    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#118    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#119    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#120    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#121    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#122    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#123    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#124    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5817:14)
#125    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#126    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#127    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#128    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#129    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#130    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#131    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#132    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#133    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#134    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#135    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#136    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#137    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#138    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#139    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#140    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#141    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#142    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#143    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#144    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#145    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#146    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#147    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#148    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#149    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#150    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#151    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#152    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#153    ListIterable.forEach (dart:_internal/iterable.dart:41:13)
#154    _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1931:25)
#155    BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2714:27)
#156    BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2545:15)
#157    BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2713:7)
#158    AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1026:18)
#159    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
#160    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
#161    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
#162    AutomatedTestWidgetsFlutterBinding.scheduleWarmUpFrame (package:flutter_test/src/binding.dart:954:5)
#163    runApp (package:flutter/src/widgets/binding.dart:989:7)
#164    TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:710:7)
#176    testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
#189    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1099:17)
#190    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1087:35)
(elided 38 frames from class _FakeAsync, dart:async, dart:async-patch, and package:stack_trace)
`

**Comment by astheras** [comment]
I have this issue too 
@override
```
  void onClose() {
    if (searchOnStoppedTyping != null) searchOnStoppedTyping!.cancel();
    focusNode.dispose();
    teController.removeListener(teControllerListener);
    teController.dispose();
    super.onClose();
  }
```
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
A TextEditingController was used after being disposed.

Once you have called dispose() on a TextEditingController, it can no longer be used.
When the exception was thrown, this was the stack
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure>
package:flutter/…/foundation/change_notifier.dart:117
#1      ChangeNotifier._debugAssertNotDisposed
package:flutter/…/foundation/change_notifier.dart:123
#2      ChangeNotifier.removeListener
package:flutter/…/foundation/change_notifier.dart:195
#3      EditableTextState.dispose
package:flutter/…/widgets/editable_text.dart:1675
#4      StatefulElement.unmount
package:flutter/…/widgets/framework.dart:4800
...


**Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (5 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4**
