### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by joeblew99** [AbdulRahmanAlHamali/flutter_typeahead#137]
Just wondering if the web support is going to be merged from https://github.com/sarbagyastha/flutter_typeahead

**Comment by hillelcoren** [comment]
Thank you for your work on the library, it works great!

Related to this issue are there plans to add keyboard support. For example, being able to use the up/down keys to move the focus between the options and tab or enter to select an item.

**Comment by sh0umik** [comment]
Its a bit weird! Its not working on flutter beta.

 `[✓] Flutter (Channel beta, v1.13.6, on Mac OS X 10.14.6 18G103, locale en-BD)`

It worked before ! I have also tried the `https://github.com/sarbagyastha/flutter_typeahead` in both `master` and `beta` channel and same problem, Not able to select any item in suggestion after result comes.

**Comment by hillelcoren** [comment]
I believe it is working on the dev channel

**Comment by hillelcoren** [comment]
I'm seeing the same behavior, it was working but now is not

**Comment by KaYBlitZ** [comment]
I cannot merge #134 . The code that is used breaks functionality for iOS users. You can see my explanation there.

With regards to broken functionality, what exactly is not working. Is it mobile or web? What's the exact problem?

**Comment by DisbarredMouse** [comment]
It's Web for me, Dont know about Mobile. when on latest from master, dev, or beta channel onSuggestionSelected doesnt seem to get triggered. As a result I am not able to select any item in the selection list, list just closes without any item getting selected.

**Comment by crimsonsuv** [comment]
Hello, will we get an update for the latest flutter beta? as the web is not working, the suggestion list is not showing.

**Comment by bluemix** [comment]
currently, v1.8.0, after clicking on the suggested item, it doesn't reflected back as being selected 
![flutter_typehead_issue_on_web](https://user-images.githubusercontent.com/3332274/74080424-13052000-4a55-11ea-9605-9a628b9af788.gif)

**Comment by Ahmadre** [comment]
> currently, v1.8.0, after clicking on the suggested item, it doesn't reflected back as being selected:
> 
> ![flutter_typehead_issue_on_web](https://user-images.githubusercontent.com/3332274/74080424-13052000-4a55-11ea-9605-9a628b9af788.gif) [ ![flutter_typehead_issue_on_web](https://user-images.githubusercontent.com/3332274/74080424-13052000-4a55-11ea-9605-9a628b9af788.gif) ](https://user-images.githubusercontent.com/3332274/74080424-13052000-4a55-11ea-9605-9a628b9af788.gif) [ ](https://user-images.githubusercontent.com/3332274/74080424-13052000-4a55-11ea-9605-9a628b9af788.gif)

This is an architectual issue. It has nothing to do with: https://pub.dev/packages/flutter_keyboard_visibility.

They got web support already.
