### ISSUE TITLE
How to prevent the suggestionbox from being scrollable?

### ISSUE THREAD

**Issue by felipeleon73** [AbdulRahmanAlHamali/flutter_typeahead#140]
My suggestionsCallback always returns a maximum of 5 items. I would like the suggestionBox to show all 5 items (or less) and if there is no space at the bottom, it will auto-flip.
Instead the suggestionbox remains  at the bottom and shows me only a scrollable line

**Comment by KaYBlitZ** [comment]
You can return a list of only the first 5 items. Use `autoFlipDirection: true` in your TypeAheadField to have it auto flip the direction if there is not enough space.
