### ISSUE TITLE
flutter_typeahead in web support

### ISSUE THREAD

**Issue by ljcom** [AbdulRahmanAlHamali/flutter_typeahead#145]
I want to reuse this widget for web support, but there is error message like below:

Because no versions of flutter_typeahead match >1.7.0 <2.0.0 and flutter_typeahead 1.7.0 depends on flutter any from sdk, flutter_typeahead ^1.7.0 requires flutter any from sdk.
So, because flutter from sdk doesn't exist (the Flutter SDK is not available) and flutter_wbackstage depends on flutter_typeahead ^1.7.0, version solving failed.

Can you help me?

**Comment by KaYBlitZ** [comment]
Try using v 1.8.0
