### ISSUE TITLE
Extend suggestions box to the left

### ISSUE THREAD

**Issue by kaciula** [AbdulRahmanAlHamali/flutter_typeahead#147]
My text form field is narrow and I want my suggestions box to be wider and to extend to the left so that each suggestion fits in one line. Is this possible right now?

I can use the suggestionsBoxDecoration to give a larger width to the box but it extends to the right not left.

![device-2020-01-16-181619](https://user-images.githubusercontent.com/18688/72542286-91263a80-388c-11ea-9669-b83cb40356cf.png)

**Comment by KaYBlitZ** [comment]
Hi, great suggestion. I will add an offsetX in the SuggestionsBoxController to let you shift the box. Use constraints to set a proper width as well. Expect this in the next 1.8.0 release!

Use the `offsetX` property in `SuggestionsBoxDecoration` to shift the suggestions box along the x-axis. 
You may also pass BoxConstraints to `constraints` in `SuggestionsBoxDecoration` to adjust the width 
and height of the suggestions box. Using the two together will allow the suggestions box to be placed 
almost anywhere.

**Comment by sharpsan** [comment]
How do you specify the width of the suggestions currently?  I was not able to do so using the decorationBuilder:

```
      decorationBuilder: (context, widget) {
        return Container(
          color: Colors.white,
          constraints: BoxConstraints(
            minWidth: 700,
            maxWidth: 700,
          ),
          child: widget,
        );
      },
```
