### ISSUE TITLE
HideOnEmpty not working

### ISSUE THREAD

**Issue by DevonJerothe** [AbdulRahmanAlHamali/flutter_typeahead#149]
Hello I am trying to hide the dropdown when there are no suggestions or when the textfield is empty. When there are no suggestions and the textfield has a query it hides correctly. However, if I backspace to empty or clear the TextController the empty suggestion box appears. Screenshots show my issue.

Here is my current code snip

```dart
          child: TypeAheadField(
                    hideOnEmpty: true,                   
                    textFieldConfiguration: TextFieldConfiguration(
                      onEditingComplete: () async {
                        FocusScope.of(context).requestFocus(FocusNode());
                        if(_textController.text.isNotEmpty){
                        BlocProvider.of<SmogonBloc>(context).add(SearchSmogon(
                            alias: _textController.text.toLowerCase(),
                            lang: 'en',
                            gen: 'xy'));
                        }
                      },
                      controller: _textController,
                      autocorrect: false,
                      autofocus: false,
                      decoration: InputDecoration(
                        border: InputBorder.none,
                        suffixIcon: GestureDetector(
                          child: Icon(Icons.clear),
                          onTap: () {
                            BlocProvider.of<SmogonBloc>(context)
                                .add(ResetSmogon());
                            _textController.clear();
                          },
                        ),
                        hintText: 'Search Pokemon',
                      ),
                    ),
                    suggestionsCallback: (pattern) {
                      return PokeDB.getMons(pattern);
                    },
                    itemBuilder: (context, suggestion) {
                      if(_textController.text.isNotEmpty){
                        return ListTile(
                          leading: Image.asset('lib/assets/img/sprites/${suggestion['ID']}.png'),
                          title: Text(suggestion['name']),
                        );
                      }
                      return null;
                    },
                    onSuggestionSelected: (Map<String, String> suggestion) async {
                      _textController.text = suggestion['name'];
                      BlocProvider.of<SmogonBloc>(context).add(SearchSmogon(
                            alias: _textController.text.toLowerCase(),
                            lang: 'en',
                            gen: 'xy'));
                    },
                  )),
```

Some screenshots

<img width="390" alt="Screen Shot 2020-01-23 at 3 27 46 PM" src="https://user-images.githubusercontent.com/13026977/73022027-be2b9d80-3df6-11ea-833b-69df00749fd0.png">

This is the issue Im running into

<img width="392" alt="Screen Shot 2020-01-23 at 3 27 59 PM" src="https://user-images.githubusercontent.com/13026977/73022045-caaff600-3df6-11ea-8570-3411fd10d4fa.png">

**Comment by KaYBlitZ** [comment]
Hi. I dont think there is anything wrong on typeahead's side. There is this snippet in the code

```
} else if (this._suggestions.isEmpty) {
      if (widget.hideOnEmpty) {
        child = Container(height: 0);
      } else {
        child = createNoItemsFoundWidget();
      }
    }
```
I am guessing that you are returning a non-empty collection in suggestionsCallback, which is why the suggestions box gets rendered. But in itemBuilder, you are returning null for some items, which make it appear that the suggestions are empty. Can you perhaps try trimming you collection before returning it in suggestionsCallback?

**Comment by DevonJerothe** [comment]
> But in itemBuilder, you are returning null for some items, which make it appear that the suggestions are empty.

Right as I posted this I noticed that.... sure enough removing the null showed I was returning suggestions. Cant believe I didn't catch this, was driving me mad lol. Thanks for that tho! closing.
