### ISSUE TITLE
flutter_typeahead not working in iOS flutter

### ISSUE THREAD

**Issue by straltest** [AbdulRahmanAlHamali/flutter_typeahead#15]
I am getting compile error in flutter iOS application. In Android this package is working fine.
Below is error which I am getting when using this package.

compiler message: file:///Users/stral/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_typeahead-0.4.1/lib/flutter_typeahead.dart:1120:9: Error: Type 'TextCapitalization' not found.
compiler message:   final TextCapitalization textCapitalization;
compiler message:         ^
compiler message: file:///Users/stral/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_typeahead-0.4.1/lib/flutter_typeahead.dart:1179:7: Error: Type 'TextCapitalization' not found.
compiler message:       TextCapitalization textCapitalization,
compiler message:       ^
compiler message: file:///Users/stral/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_typeahead-0.4.1/lib/flutter_typeahead.dart:717:9: Error: No named parameter with the name 'onEditingComplete'.
compiler message:         onEditingComplete: widget.textFieldConfiguration.onEditingComplete,
compiler message:         ^^^^^^^^^^^^^^^^^
compiler message: file:///Users/stral/flutter/packages/flutter/lib/src/material/text_field.dart:99:9: Context: Found this candidate, but the arguments don't match.
compiler message:   const TextField({
compiler message:         ^
compiler message: file:///Users/stral/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_typeahead-0.4.1/lib/flutter_typeahead.dart:1120:9: Error: 'TextCapitalization' isn't a type.
compiler message:   final TextCapitalization textCapitalization;
compiler message:         ^^^^^^^^^^^^^^^^^^
compiler message: file:///Users/stral/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_typeahead-0.4.1/lib/flutter_typeahead.dart:1148:32: Error: Getter not found: 'TextCapitalization'.
compiler message:       this.textCapitalization: TextCapitalization.none,
compiler message:                                ^^^^^^^^^^^^^^^^^^
compiler message: file:///Users/stral/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_typeahead-0.4.1/lib/flutter_typeahead.dart:1148:32: Error: The getter 'TextCapitalization' isn't defined for the class 'flutter_typeahead::TextFieldConfiguration<flutter_typeahead::TextFieldConfiguration::T>'.
compiler message: Try correcting the name to the name of an existing getter, or defining a getter or field named 'TextCapitalization'.
compiler message:       this.textCapitalization: TextCapitalization.none,
compiler message:                                ^
compiler message: file:///Users/stral/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_typeahead-0.4.1/lib/flutter_typeahead.dart:1179:7: Error: 'TextCapitalization' isn't a type.
compiler message:       TextCapitalization textCapitalization,
compiler message:       ^^^^^^^^^^^^^^^^^^

Please provide any solution for this.

**Comment by sjmcdowall** [comment]
I am using it fine in flutter on iOS both emulator and real devices... make sure you do a "flutter upgrade" (beta channel I suggest) and then a "flutter clean" then "flutter run" .. you may also have to do a rm -rf ios/Pods  and then "cd ios; pod install" .. but don't do that until you try the upgrade and clean

**Comment by AbdulRahmanAlHamali** [comment]
Hello @straltest, I apologize for taking so long to reply. I have been extremely overwhelmed in the past period, and now I am planning to get things back on track.

Has been solved?
