### ISSUE TITLE
Beta Channel v1.13.6 - Issues

### ISSUE THREAD

**Issue by JeffOlajos** [AbdulRahmanAlHamali/flutter_typeahead#151]
Flutter for Web

This plugin seemed to work relatively well until the recent flutter release on the beta channel. Now it wont fire the onTap() of the InkWell inside your onSelected. Have you run across this? 

Ive tried a number of things to simplfy but I'm unable to get it to function. If I roll back to Beta Channel v1.12.13+hotfix.6 it works fine.

**Comment by DisbarredMouse** [comment]
Same problem for me.

Seems broken if using flutter v1.13.3 or later

**Comment by KaYBlitZ** [comment]
Can one of you post sample code?

**Comment by jshep23** [comment]
This is still broken. Here is a gist with some sample code.
https://gist.github.com/jshep23/42ccc4c56f73171edb0c77392a81f957

Current version of the plugin is flutter_typeahead: ^1.8.0
I just tried upgrading to Flutter Version : 1.14.6 in the beta channel and still not working.

Also confirmed rolling back to Flutter Version v1.12.13+hotfix.6 "fixes" the issue

**Comment by jshep23** [comment]
Just to add, there is no error raised. The suggestions list shows up correctly, however when you try to select an item, the suggestions list just disappears, and the logic in the `onSuggestionSelected` handler is never executed.

**Comment by abcnow** [comment]
same problem.. we have created an encyclopedia and when users search and try to select content from dropdown menu with mouse is not allowing them to do so.. it works on iphone and ipad with touch but not with mouse on pc/desktop/browser

**Comment by DeepakKanyanRor** [comment]
Same Problem.

**Comment by jquintana53** [comment]
Below is a **quick app code to reproduce it**:

```
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_typeahead/flutter_typeahead.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    final field = TypeAheadField(
      textFieldConfiguration: TextFieldConfiguration(
          autofocus: true,
          style: DefaultTextStyle.of(context).style.copyWith(fontStyle: FontStyle.italic),
          decoration: InputDecoration(border: OutlineInputBorder())),
      suggestionsCallback: (pattern) {
        final completer = Completer<List<String>>()..complete(['a', 'b', 'c', 'd', 'e', 'f']);

        return completer.future;
      },
      itemBuilder: (context, suggestion) {
        return ListTile(
          leading: Icon(Icons.info),
          title: Text(suggestion),
        );
      },
      onSuggestionSelected: (suggestion) {
        print('suggestion is $suggestion');
      },
    );

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: field,
    );
  }
}
```

**Comment by jquintana53** [comment]
**Work around** (until it gets fixed)

Following the above example, wrap the widgets provided by itemBuilder in a Listener:

```
.....
      itemBuilder: (context, suggestion) {
        return Listener(
            child: ListTile(
              leading: Icon(Icons.info),
              title: Text(suggestion),
            ),
            onPointerDown: (_) => print(suggestion),
          );
      },
.....
```
PS: The mouse pointer highlight in the list will still be off but it'll work.

**Comment by abcnow** [comment]
@jquintana53 thanks for the tip.. it worked for us!

**Comment by jquintana53** [comment]
If you'd like to remove the highlighting you can wrap the ListTile in a Container with a defined background color, there will be no highlighting but I think it'll be less confusing to the user. See below:

```
....
        itemBuilder: (context, String suggestion) {
          return Listener(
            child: Container(
              color: Colors.white, // or whatever color
              child: ListTile(
                title: Text(suggestion),
              ),
            ),
            onPointerDown: (_) => print(suggestion),
          );
        },
....
```

**Comment by jshep23** [comment]
Thanks @jquintana53! This also worked for us. Hopefully a long term fix can be implemented soon, but this gets us moving! Appreciate it 👍

**Comment by rasmuschristensen** [comment]
thanks @jquintana53 great workaround for now

**Comment by wterrill** [comment]
> itemBuilder: (context, String suggestion) {
>           return Listener(
>             child: Container(
>               color: Colors.white, // or whatever color
>               child: ListTile(
>                 title: Text(suggestion),
>               ),
>             ),
>             onPointerDown: (_) => print(suggestion),
>           );
>         },

I had this problem with version 1.8.1, and I tried this workaround successfully. (thanks @jquintana53!)
