### ISSUE TITLE
Selecting Content from Dropdown Menu with Mouse is not Working on the Web

### ISSUE THREAD

**Issue by abcnow** [AbdulRahmanAlHamali/flutter_typeahead#156]
Selecting content from dropdown menu (from a search) is currently only working from ipad and iphone when you touch content but if users use the mouse from a pc browser is not allowing such selection. So it is currently non-functional for the web

**Comment by jshep23** [comment]
Just to keep things in order, this is most likely related to issue #151

**Comment by abcnow** [comment]
Thanks Jshep! I added this on that #151 to keep things organized
