### ISSUE TITLE
onSuggestionSelected not working Web.

### ISSUE THREAD

**Issue by DeepakKanyanRor** [AbdulRahmanAlHamali/flutter_typeahead#157]
I'm using  **flutter_typeahead: ^1.8.0** . All things Working correctly but when I select Item from dropdown onSuggestionSelected not called.

**Comment by DeepakKanyanRor** [comment]
```
Widget widgetDestination() {


    return TypeAheadField(


     hideSuggestionsOnKeyboardHide: false,
      textFieldConfiguration: TextFieldConfiguration(
        controller: txtDest,
        
          decoration:
              InputDecoration(border: InputBorder.none, hintText: destination?.source?? "To",

              )),
      suggestionsCallback: (pattern) async {
        return await searchStoppage(pattern);
      },
      itemBuilder: (context, suggestion) {


        return Padding(
          padding: const EdgeInsets.all(8.0),
          child: Text(suggestion),
        );
        /*var data = suggestion as Data;
        return ListTile(
          title: Text(data.source),
          subtitle: Text(data.address,style: TextStyle(fontSize: 9)),
        );*/
      },
      onSuggestionSelected: (suggestion) {

        print("DDDDDD $suggestion");

      },

    );
  }
```

**Comment by raullermen** [comment]
onTap inside itemBuilder not working either on web =\

**Comment by dan-r95** [comment]
having the same issue here!

**Comment by abcnow** [comment]
just to keep things organized .. this issue seems related to this one here ..#151

**Comment by jquintana53** [comment]
I'm facing the same issue here, using it for a **flutter web** app. 

Also the highlighted element in the suggestion box when hovering the mouse over is above the pointer by hundreds of pixels.

Below is a **quick app code to reproduce it**:

```
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_typeahead/flutter_typeahead.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    final field = TypeAheadField(
      textFieldConfiguration: TextFieldConfiguration(
          autofocus: true,
          style: DefaultTextStyle.of(context).style.copyWith(fontStyle: FontStyle.italic),
          decoration: InputDecoration(border: OutlineInputBorder())),
      suggestionsCallback: (pattern) {
        final completer = Completer<List<String>>()..complete(['a', 'b', 'c', 'd', 'e', 'f']);

        return completer.future;
      },
      itemBuilder: (context, suggestion) {
        return ListTile(
          leading: Icon(Icons.info),
          title: Text(suggestion),
        );
      },
      onSuggestionSelected: (suggestion) {
        print('suggestion is $suggestion');
      },
    );

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: field,
    );
  }
}
```

**Flutter doctor**

> [✓] Flutter (Channel beta, v1.13.6, on Mac OS X 10.14.6 18G2022, locale en-US)
>     • Flutter version 1.13.6 at /usr/local/flutter/flutter-v1.12.13+hotfix.7-stable
>     • Framework revision 659dc8129d (8 weeks ago), 2019-12-30 09:24:47 -0800
>     • Engine revision bdc9708d23
>     • Dart version 2.8.0 (build 2.8.0-dev.0.0 c547f5d933)
> 
> [✗] Android toolchain - develop for Android devices
>     ✗ Unable to locate Android SDK.
>       Install Android Studio from: https://developer.android.com/studio/index.html
>       On first launch it will assist you in installing the Android SDK components.
>       (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
>       If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
>       You may also want to add it to your PATH environment variable.
> 
> 
> [✗] Xcode - develop for iOS and macOS
>     ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
>       Download at: https://developer.apple.com/xcode/download/
>       Or install Xcode via the App Store.
>       Once installed, run:
>         sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
>         sudo xcodebuild -runFirstLaunch
>     ✗ CocoaPods not installed.
>         CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
>         Without CocoaPods, plugins will not work on iOS or macOS.
>         For more info, see https://flutter.dev/platform-plugins
>       To install:
>         sudo gem install cocoapods
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [!] Android Studio (not installed)
>     • Android Studio not found; download from https://developer.android.com/studio/index.html
>       (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
> 
> [✓] IntelliJ IDEA Community Edition (version 2019.3.2)
>     • IntelliJ at /Applications/IntelliJ IDEA CE.app
>     • Flutter plugin version 42.1.4
>     • Dart plugin version 193.6015.9
> 
> [✓] VS Code (version 1.42.0)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.8.1
> 
> [✓] Connected device (2 available)
>     • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.122
>     • Web Server • web-server • web-javascript • Flutter Tools
> 
> ! Doctor found issues in 3 categories.

**Comment by DeepakKanyanRor** [comment]
no solution!!!

**Comment by abcnow** [comment]
"deepakKanyanRor" this workaround worked for us momentarily...the mouse highlight doesn't work with this but when you point and click with the mouse it does the job...
https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/151#issuecomment-590934761

**Comment by kiaxseventh** [comment]
having the same issue
are you have solution ?

**Comment by JaviBonilla** [comment]
Any progress on this? Thanks!

**Comment by stalko** [comment]
Are there any updates?

**Comment by klokoleva** [comment]
resserved, same problem

**Comment by DhiaEddineNabli** [comment]
Hello guys check this thread 
https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/186

**Comment by pierre-gancel** [comment]
this is a duplicate, why not close this issue ?

**Comment by lordvidex** [comment]
onSuggestionSelected is not updating controllers for me as well
