### ISSUE TITLE
Would it be possible to only start autocomplete after a specific character is entered, such as "@"?

### ISSUE THREAD

**Issue by emaddoma** [AbdulRahmanAlHamali/flutter_typeahead#162]
I have the need to provide autocomplete but only in the context of a "user lookup".  Is it possible to only start the autocomplete functionality after the "@" character has been entered into the field?

**Comment by intkhabahmed** [comment]
@emaddoma You can place a check in `suggestionsCallback` and return the results only when the query contain `@` symbol

**Comment by qlssk8737** [comment]
@intkhabahmed I understand your solution but have no idea how to change it. Could you give me an example with query? Actually I want the function to be implemented when users type anything, not on tapping. I've tried if statement in the `suggestionsCallBack`, but it didn't work.
```
suggestionsCallback: (pattern) {
                                 if (_controller.text != null) {
                                  return Service.getSuggestions(pattern)};
                                },
```

**Comment by intkhabahmed** [comment]
In your if check, you can write as
````
If(controller.text != null && controller.text.endsWith("@")) {
  return... 
}
````
