### ISSUE TITLE
when keyboard_visibility and flutter_keyboard_visibility used together

### ISSUE THREAD

**Issue by showcase-budha-sanjeev** [AbdulRahmanAlHamali/flutter_typeahead#163]
Class FLTKeyboardVisibilityPlugin is implemented in both /private/var/containers/Bundle/Application/C88883F2-1D68-415B-BBC2-C37AB7EAE344/Runner.app/Frameworks/keyboard_visibility.framework/keyboard_visibility (0x102a30f40) and /private/var/containers/Bundle/Application/C88883F2-1D68-415B-BBC2-C37AB7EAE344/Runner.app/Frameworks/flutter_keyboard_visibility.framework/flutter_keyboard_visibility (0x102a18f40).

**Comment by yatindeokar** [comment]
facing the same issue, any solution

**Comment by adolfdsilva** [comment]
+1

**Comment by adolfdsilva** [comment]
@showcase-budha-sanjeev I am continuing your flutter work for the same company :D
