### ISSUE TITLE
Option to change "No items found!" message

### ISSUE THREAD

**Issue by julien100000** [AbdulRahmanAlHamali/flutter_typeahead#167]
It would be very nice if it would be possible to change this message (e.g. pass as input parameter).

**Comment by thukuwanjiku** [comment]
@julien100000  Have you checked out the [`noItemsFoundBuilder`](https://github.com/AbdulRahmanAlHamali/flutter_typeahead/blob/fc11e4cf78223a8deaddff794b51a292ce705cd9/lib/flutter_typeahead.dart#L511) I use it like below and it works fine

`noItemsFoundBuilder: (context)=> ListTile(title: Text('No matches found'))`

**Comment by julien100000** [comment]
Did not found that @thukuwanjiku . Thank you very much! :)
