### ISSUE TITLE
update flutter_keyboard_visibility to a newer version

### ISSUE THREAD

**Issue by brizaldi** [AbdulRahmanAlHamali/flutter_typeahead#176]
I'm currently having dependency conflict because my other package depends on flutter_keyboard_visibility version 2.0.0

**Comment by brizaldi** [comment]
cc @AbdulRahmanAlHamali @sjmcdowall @KaYBlitZ

**Comment by awhitford** [comment]
This issue should be closed because:
https://github.com/AbdulRahmanAlHamali/flutter_typeahead/blob/7fca7f1266bc3e8a355752bcea924a112a32e118/pubspec.yaml#L10
