### ISSUE TITLE
Suggestion list is overlapping with Appbar.

### ISSUE THREAD

**Issue by TharaniP** [AbdulRahmanAlHamali/flutter_typeahead#183]
Hi,
   While scrolling to the top, suggestion list is overlapping with the appbar.

For more clarification please refer the screenshot. 

![Overlapping issue](https://user-images.githubusercontent.com/53432405/81283062-aad8d100-9079-11ea-8c57-507b2158ed06.png)

**Comment by easazade** [comment]
how did you fix this?
