### ISSUE TITLE
Keeps Animating the Overlay

### ISSUE THREAD

**Issue by rgb1380** [AbdulRahmanAlHamali/flutter_typeahead#184]
Assume the suggestion list is

['abc', 'abcd', 'abcde']

As the user types 'abc', the suggestion list will not change. However, the widget keeps animating display of the overlay box. The animation is only a meaningful cue if the suggestion list is changing.

**Comment by yalva** [comment]
I'm also facing this issue when I try to use this on top of google map, any fix is much appreciated.

**Comment by TheManuz** [comment]
I think the suggestionbox should have an implicit transition on the size.
Currently it always animate from zero to final height.
I tried to fix this, but i'm not able to do it using the provided transitionBuilder, since we should know the previous height to interpolate.
