### ISSUE TITLE
Problem with 'paste' into TypeAheadFormField

### ISSUE THREAD

**Issue by davidSchlosser** [AbdulRahmanAlHamali/flutter_typeahead#185]
Following error is reported in the IDE console when I attempt to paste the word 'dynamic' into a TypeAheadFormField in my application. I've been able to work around the issue by providing a dummy 'onChanged' parameter in the textFieldConfiguration. ie `onChanged: (_){}`

Using flutter_typeahead version 1.6.1

[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'call' was called on null.
Receiver: null
Tried calling: call("dynamic")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      new TypeAheadFormField.<anonymous closure>.<anonymous closure> (package:flutter_typeahead/flutter_typeahead.dart)
#2      EditableTextState._formatAndSetValue (package:flutter/src/widgets/editable_text.dart:1607:14)
#3      EditableTextState.textEditingValue= (package:flutter/src/widgets/editable_text.dart:1757:5)
#4      TextSelectionControls.handlePaste (package:flutter/src/widgets/text_selection.dart:228:16)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#6      _rootRunUnary (dart:async/zone.dart:1134:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart<…>

**Comment by sjmcdowall** [comment]
@davidmartos96  -- or anyone else -- is this a specific error that occurred in 1.6.1 or before or ?  I am trying to figure out the sort of issue we are having here and if it was caused by some recent PR.

**Comment by davidmartos96** [comment]
@sjmcdowall I'm not familiar with this issue. But I don't think is related to one of my PRs. Does this occur in the latest version of the plugin? 1.6.1 is from last year.

**Comment by sjmcdowall** [comment]
@davidmartos96 -- Sorry I did mean @davidSchlosser the author of the issue.  I also sort of think maybe the version is a typo (although that's a good point).   I haven't heard anyone else complain about this so .. maybe some edge condition ..

**Comment by davidSchlosser** [comment]
Hi, thanks for looking at this. I was indeed using 1.6.1. With 1.8.1 - the problem still exists, same work around avoids it.

**Comment by awhitford** [comment]
A **Cut** or **Paste** into a **FormBuilderTypeAhead** triggers an exception: 
```
Tried calling: call("pasted_text")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      new TypeAheadFormField.<anonymous closure>.<anonymous closure> (package:flutter_typeahead/flutter_typeahead.dart:315:53)
#2      EditableTextState._formatAndSetValue (package:flutter/src/widgets/editable_text.dart:1691:23)
#3      EditableTextState.textEditingValue= (package:flutter/src/widgets/editable_text.dart:1842:5)
#4      TextSelectionControls.handlePaste (package:flutter/src/widgets/text_selection.dart:228:16)
#5      _rootRunUnary (dart:async/zone.dart:1192:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#9      Future._propagateToListeners (dart:async<…>
```

https://github.com/AbdulRahmanAlHamali/flutter_typeahead/blob/398aa83b7d3607131921153e50ee879651c44d4d/lib/flutter_typeahead.dart#L315

Note that I am actually using `FormBuilderTypeAhead` from [`flutter_form_builder`](https://github.com/danvick/flutter_form_builder/blob/3be8176931e15dbf5c998c8a31e9df8bd4b2fc66/lib/src/fields/form_builder_typeahead.dart#L132) which uses `TypeAheadFormField` which does not offer `onChanged`, so the workaround will not work for me. 😢
