### ISSUE TITLE
onSuggestionSelected not called in Web

### ISSUE THREAD

**Issue by afratul-taohid** [AbdulRahmanAlHamali/flutter_typeahead#186]
i tried both flutter_typeahead_web and flutter_typeahead. but onSuggestionSelected not called in web..

**Comment by shadowdogg** [comment]
I also have encountered this, much to my dismay, it also seems to not select in sync with the mouse

**Comment by DhiaEddineNabli** [comment]
Hello did you solve this problem?
@shadowdogg could you please tell us if GestureDetector with Overlay solved this issue? if yes a simple showcase is very appreciated

**Comment by shadowdogg** [comment]
@DhiaEddineNabli it does work, but i'm struggling with the logic regarding opening and closing of the overlay, as for me, change of focus does not perform correctly. I followed: https://medium.com/saugo360/https-medium-com-saugo360-flutter-using-overlay-to-display-floating-widgets-2e6d0e8decb9 (who actually is the same plugin OP) and then wrapped where it had:

```
      ListTile(
                  title: Text('Syria'),
                  onTap: () {
                    print('Syria Tapped');
                  },
                ),
```

To

```
      GestureDetector(
  onPanDown: (_) {
       print('Syria tapped)
 },
   child: ListTile(
           title: Text('Syria'),
                ),
),
```

**Comment by wterrill** [comment]
As far as I can tell, this isn't a problem with the plugin, per se.  This was working for quite a while, but stopped working about 3 or 4 days ago.  I've been trying to change different things to figure out what's going on... but the only thing that seemed to work was downgrading my flutter channel from master to dev.  I also tried reverting to version 1.8.0 of this plugin (which is what I started with) but that didn't change anything.  

In the case of going to the dev channel, onSuggestionSelected() worked, but the highlighted suggestion was off.  It seemed to hover one or two tiles above where the cursor was.  

Are other people seeing the same thing?

**Comment by shadowdogg** [comment]
@wterrill I wish the author would mention this. Thanks a lot for letting me know about this.

**Comment by sjmcdowall** [comment]
This package is only tested on App programs, not Web etc.  There are lots of issues with desktop/Web applications beyond what this plugin can handle.

**Comment by DhiaEddineNabli** [comment]
@shadowdogg thank you this solution worked. I didn't know GestureDetector has this onPanDown callback function which can detect mouse events. @wterrill thank you your solution works as well but I saw that many callback functions from Listener for mouse events are now deprecated somehow. Although the mouse clicks are now detected the suggestion list behaves in a way that when hovering over an element the previous list element is being highlighted while the actual one is still clicked and selected

**Comment by wterrill** [comment]
Sorry, I should have mentioned that if you set a background color, it gets rid of highlighting all together.  So, the code would look like:

If you'd like to remove the highlighting you can wrap the ListTile in a Container with a defined background color, there will be no highlighting but I think it'll be less confusing to the user. See below:

....
        itemBuilder: (context, String suggestion) {
          return Listener(
            child: Container(
              color: Colors.white, // or whatever color
              child: ListTile(
                title: Text(suggestion),
              ),
            ),
            onPointerDown: (_) => print(suggestion),
          );
        },
....

**Comment by shadowdogg** [comment]
Any advantage of doing Listener over Gesture detection?

**Comment by SeriousMonk** [comment]
onPanDown workaround makes it impossible to scroll through the suggestion list on web version of app on mobile device

**Comment by Ahmadre** [comment]
just for your information: https://pub.dev/packages/flutter_keyboard_visibility

**Comment by Ahmadre** [comment]
I already solved the error with keyboard visibility, but still: it's not working. So it's definetly an architectual error here.
