### ISSUE TITLE
If the suggestion list is open and Navigation Pops() (go back) an error is thrown

### ISSUE THREAD

**Issue by rlazom** [AbdulRahmanAlHamali/flutter_typeahead#187]
Lets say I have two views: home and details.

When I'm on details if I open the suggestions (start typing), but don't select any of the option and go back in the navigation stack an error is thrown.

`I/flutter (32100): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (32100): The following assertion was thrown while finalizing the widget tree:
I/flutter (32100): A TextEditingController was used after being disposed.
I/flutter (32100): Once you have called dispose() on a TextEditingController, it can no longer be used.`

Any help please...

**Comment by sjmcdowall** [comment]
Repeatable?  Also -- was there more of a stack trace to be had? And confirm the version you are using.

**Comment by rlazom** [comment]
First of all, thanks for the quickly answer.
I'm using: flutter_typeahead: ^1.8.0

I manage to find the issue, the error is triggered on this conditions:
- The suggestion list is open
- The dispose method was called and the TextEditingController used on the Typeahead's TextFieldConfiguration controller was disposed

`
@override
  void dispose() {
...
    _usernameCtrl.dispose();
    ...
    super.dispose();
  }
`

But testing I notice that if I click a button (or anything) that calls to a SuggestionBoxController's close method before I click the back button that trigger the dispose methods, the error is not shown.
But, if I add the SuggestionBoxController's close method on top on `@override void dispose()` 
For example:
`
@override
  void dispose() {
suggestionsBoxController.close();
...
    _usernameCtrl.dispose();
    ...
    super.dispose();
  }
`
The error is still showing...

The only way I found to "fix this" was removing the _usernameCtrl.dispose(); from dispose method, but I think this could not be the "rigth way"...
