### ISSUE TITLE
* SuggestionsCallback error !!

### ISSUE THREAD

**Issue by leanhro2812** [AbdulRahmanAlHamali/flutter_typeahead#190]
The suggestionsCallback function calls repeatedly when I enter a keyword
causing itemBuilder to keep jerking the screen continuously.
And : "No Items Found" => appeared the first time I focused  ..
...
And it seems the debounceDuration is not working properly
when I enter the suggestionsCallback keyword will be called .....after a set amount of time from debounceDuration will call again.
causes the ItemBuilder list to duplicate render

**Comment by intkhabahmed** [comment]
Yes this issue is coming. In the first time when I enter a character, the debounceDuration doesn't work, also when I delete the last character, it doesn't get deleted in the first time, need to press the back button again to delete it.
