### ISSUE TITLE
Empty suggestion list render and disappear

### ISSUE THREAD

**Issue by MartinJLee** [AbdulRahmanAlHamali/flutter_typeahead#192]
When the input textbox is empty, the empty suggestion appears then disappears.

**Comment by jlubeck** [comment]
Looks like this is the same issue I'm seeing:
![RheQteK26EGRt9Hh7E](https://user-images.githubusercontent.com/3067603/82461647-ab656480-9a88-11ea-956e-ed7b7e2bc969.gif)

**Comment by cms103** [comment]
I've found a work around that seems to fix it, add the following to the TypeAheadField constructor call:

`loadingBuilder: (context) => null,`

**Comment by MartinJLee** [comment]
> I've found a work around that seems to fix it, add the following to the TypeAheadField constructor call:
> 
> `loadingBuilder: (context) => null,`

Thank you, it seems address the issue.

**Comment by jlubeck** [comment]
> I've found a work around that seems to fix it, add the following to the TypeAheadField constructor call:
> 
> `loadingBuilder: (context) => null,`

This is not working for me... I'm still seeing the same issue when used with `hideOnEmpty: true`

**Comment by intkhabahmed** [comment]
@jlubeck use `keepSuggestionsOnLoading: false` also

**Comment by jlubeck** [comment]
@intkhabahmed still happening with `keepSuggestionsOnLoading`

**Comment by intkhabahmed** [comment]
Btw, strange, I removed this one also and it is not happening anymore

**Comment by KennyChan94P** [comment]
can try with this.
`loadingBuilder: (context) =>
                              _searchTextController.text.isEmpty
                                  ? SizedBox(
                                      height: 0,
                                    )
                                  : Loading(
                                      backgroundColor: Colors.white,
                                    ),`
