### ISSUE TITLE
Showing suggestions only if there is text?

### ISSUE THREAD

**Issue by shadowdogg** [AbdulRahmanAlHamali/flutter_typeahead#198]
Whilst it will not initially load suggestions when it has focus, if you type, then delete the content, it will try to show suggestions based on nothing. Is there anyway around this?

 thought I could achieve something reasonable with this, but ofcourse it isn't happy with null

```
          suggestionsCallback: (pattern) async {
            if (pattern.length > 0) {
              List<dynamic> b = await fetchSuggestions(pattern);
              return b[1];
            } else {
              return null;
            }
          },
```

**Comment by qbait** [comment]
I have a similar issue. I need to show suggestions after typing several letters. Have you solved it somehow?
