### ISSUE TITLE
InputField gets cleared when setState is called by another widget

### ISSUE THREAD

**Issue by TheDeveloperYJ** [AbdulRahmanAlHamali/flutter_typeahead#2]
I have two typeahead widgets and a date picker . When I click on a datepicker and select the date , the date picker sets the state to current date but the text in the typeahead disappears .

**Comment by AbdulRahmanAlHamali** [comment]
Thank you for reporting this issue

Can you please provide a small code sample that reproduces the issue?

**Comment by TheDeveloperYJ** [comment]
class RateScreen extends StatefulWidget {
  createState() => RateScreenState();
}

class RateScreenState extends State<RateScreen>
    with SingleTickerProviderStateMixin {

  String origin,destination = '';

  final Map<String,dynamic> rateObject = {
    "search":"",
    "origin":"",
    "destination":"",
    "date":"",
  };
  DateFormat formatter = DateFormat('yyyy-MM-dd');
   final dateFormat = DateFormat("yyyy-MM-dd");
  Future<Null> _selectDate(BuildContext context) async {

    final DateTime picked = await showDatePicker(
        context: context,
        initialDate: _date,
        firstDate: DateTime(2018),
        lastDate: DateTime(2030));

    if (picked != null && picked != _date) {
      setState(() {
        _date = picked;
      });
    }
  }
 @override
  Widget build(BuildContext context) {
    return Container(
        margin: EdgeInsets.all(15.0),
        child: Form(
            child: ListView(
          children: <Widget>[
 
            
            originPort(),
            destinationPort(),
           
            datepicker(),
          ],
        )));
  }

  Widget searchName() {
    return TextFormField(
      decoration: InputDecoration(
          hintText: 'Give this search a name for future reference',
          contentPadding: EdgeInsets.all(15.0),
          filled: true,
          fillColor: Colors.white,
          border: OutlineInputBorder()),
      onSaved: (String value) {
        setState(() => rateObject['search'] = value);
      },
    );
  }

 Widget originPort() {
  final TextEditingController _typeAheadController = TextEditingController();
  return TypeAheadFormField(
    textFieldConfiguration: TextFieldConfiguration(
      autocorrect: false,
      decoration: InputDecoration(
          filled: true,
          fillColor: Colors.white,
          hintText: 'Origin Port',
          prefixIcon: Padding(
            padding: EdgeInsetsDirectional.only(end: 10.0),
            child: Image.asset(
              'images/icons/from_icon.png',
              height: 15.0,
              width: 5.0,
              scale: 0.5,
            ),
          ),
          contentPadding: EdgeInsets.all(15.0),
          border: OutlineInputBorder()),
      controller: _typeAheadController,
    ),
    suggestionsCallback: (pattern) {
      if (_typeAheadController.text.length >= 3) {
        return GetPorts.getSuggestions(pattern);
      }
    },
    itemBuilder: (context, suggestion) {
      return ListTile(
        title: Text('$suggestion'),
      );
    },
    transitionBuilder: (context, suggestionsBox, controller) {
      if (_typeAheadController.text.length >= 3 &&
          _typeAheadController.text.length != null) {
        return suggestionsBox;
      }
    },
    onSuggestionSelected: (suggestion) {
      _typeAheadController.text = suggestion;
    },
    validator: (value) {
      if (value.isEmpty) {
        return 'Please specifiy a origin port';
      }
    },
    onSaved: (value){
       rateObject['origin'] = value;
      print(rateObject);
    },
  );
}

 Widget destinationPort() {
  final TextEditingController _typeAheadController1 = TextEditingController();

  return TypeAheadFormField(
    textFieldConfiguration: TextFieldConfiguration(
      textInputAction: TextInputAction.send,
      autocorrect: false,
      decoration: InputDecoration(
          filled: true,
          fillColor: Colors.white,
          hintText: 'Destination Port',
          prefixIcon: Padding(
            padding: EdgeInsetsDirectional.only(end: 10.0),
            child: Image.asset(
              'images/icons/from_icon.png',
              height: 15.0,
              width: 5.0,
              scale: 0.5,
            ),
          ),
          contentPadding: EdgeInsets.all(15.0),
          border: OutlineInputBorder()),
      controller: _typeAheadController1,
    ),
    suggestionsCallback: (pattern) {
      if (_typeAheadController1.text.length >= 3) {
        return GetPorts.getSuggestions(pattern);
      }
    },
    itemBuilder: (context, suggestion) {
      return ListTile(
        title: Text('$suggestion'),
      );
    },
    transitionBuilder: (context, suggestionsBox, controller) {
      if (_typeAheadController1.text.length >= 3 &&
          _typeAheadController1.text.length != null) {
        return suggestionsBox;
      }
    },
    onSuggestionSelected: (suggestion) {
      _typeAheadController1.text = suggestion;
    },
    validator: (value) {
      if (value.isEmpty) {
        return 'Please specifiy a destination port';
      }
    },
    onSaved: (value){
    setState(() {
       rateObject['destination'] = value;
      print(rateObject);
    });
    },
  );
}

Widget datepicker() {
    return GestureDetector(
        onTap: () {
          _selectDate(context);
        },
        child: Row(
          children: <Widget>[
            Padding(
              padding: EdgeInsetsDirectional.only(end: 10.0),
              child: Image.asset(
                'images/icons/calendar_icon.png',
                height: 25.0,
                width: 25.0,
                scale: 1.0,
              ),
            ),
            Text(
              '${formatter.format(_date)}',
              style: TextStyle(fontSize: 18.0),
            )
          ],
        )
        );
  }
}

**Comment by TheDeveloperYJ** [comment]
I have recorded my screen and as you can see as soon as I select the datepicker the origin port textfield gets cleared . Therfore I am unable to manage my state.
![screen](https://user-images.githubusercontent.com/25108461/45561474-7b9e9c00-b865-11e8-90aa-fb038eef4918.gif)

**Comment by AbdulRahmanAlHamali** [comment]
If you look at the beginning of your `originPort` and `destinationPort` functions, you can see that you're defining the `TextEditingController` controllers inside the function, which gets called at every build. Which means you are recreating the controller every time.

To solve your issue, just place the TextEditingControllers outside in the widget, and things should be solved

**Comment by AbdulRahmanAlHamali** [comment]
Does this solve your issue?

**Comment by TheDeveloperYJ** [comment]
Yes it solved my issue . Thanks man ! 
I have one more question can I make the suggestion box a listview so that a user can scroll through the fetched items ?

**Comment by AbdulRahmanAlHamali** [comment]
The current implementation does not support that, but I can provide it in the upcoming version.

However, you might want to consider keeping the number of suggestions limited, a maximum of 5, instead of fetching too many suggestions

**Comment by AbdulRahmanAlHamali** [comment]
Pushed version 0.3.0, which allows a `constraints` property in the suggestionsBoxDecoration. You can provide this property with `BoxConstaints` to set the height you see suitable
