### ISSUE TITLE
When using autofocus, the suggestions box opens and closes really fast when showing the widget for the first time

### ISSUE THREAD

**Issue by kaciula** [AbdulRahmanAlHamali/flutter_typeahead#200]
When using autofocus, the suggestions box opens and closes really fast when showing the widget for the first time. I need autofocus so I can make the keyboard pop up.

If I use hideOnLoading: true, it no longer has this behavior. However, now it does not look nice because for every letter I type, the suggestions box closes and opens again.

Let me know if there is something I can do.

**Comment by CiriousJoker** [comment]
Same issue here, luckily the "fix" solves this sufficiently for me

**Comment by Techno-Disaster** [comment]
Still facing this. Any good workarounds? turning autofocus on make the keyboard glitch
