### ISSUE TITLE
Softkeyboard cutsoff the suggestion box

### ISSUE THREAD

**Issue by zuwuko** [AbdulRahmanAlHamali/flutter_typeahead#201]
When the soft keyboard opens upon focusing on the Text Input Field, the suggestion box is limited height that was available between the input field and the soft keyboard opened. So basically the suggestion box gets limited to a height of like 3 pixels.. see picture for better understanding: https://toursvolcan.com/track/typeahead_error.png

**Comment by omartinma** [comment]
Here having same issue. The only workaround I found so far is to set autoFlipDirection: true that will display the suggestion box above. Any other solution?
