### ISSUE TITLE
Please update flutter_keyboard_visibilty dependency

### ISSUE THREAD

**Issue by xyzbilal** [AbdulRahmanAlHamali/flutter_typeahead#203]
it gives release built error with this package says that ;

`FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'flutter_keyboard_visibility'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
`

I dont use this package in my project but typeahead uses.

**Comment by dinit-bwd** [comment]
Ya it should update. Release build error

**Comment by sgehrman** [comment]
same.

**Comment by sjmcdowall** [comment]
Done --
