### ISSUE TITLE
Suggestions Expands Twice in Example 3 on Android

### ISSUE THREAD

**Issue by Parthib** [AbdulRahmanAlHamali/flutter_typeahead#206]
Hi,

I ran into a strange behavior while using this library, and I see it happening in Example 3 that this repo provides. It seems like the drop down expands twice. Is this expected behavior? Here is a gif showing the issue:

![facebookOverTimeOthers](https://user-images.githubusercontent.com/16823332/84602410-0d24ae80-ae3c-11ea-9ef3-c97f755a1cc9.gif)

Thanks!

**Comment by randika-srimal** [comment]
Same happens with me.

**Comment by Parthib** [comment]
Looking at how _waitChangeMetrics() works, it seems this is what happens:

1. We use MediaQuery to get the insets immediately after the user taps the field and before the keyboard appears.
2. We wait 170ms during which the keyboard appears.
3. We use MediaQuery to get the insets again. It is different this time because the keyboard has appeared. Because of this, we force the suggestions to resize.

Not sure how to address this, but I will take a look

**Comment by yuechaor** [comment]
Hi, same here, blink twice when focused, 
anyone found the solution for this issue
