### ISSUE TITLE
Suggestions Box doesn't close

### ISSUE THREAD

**Issue by sanilch99** [AbdulRahmanAlHamali/flutter_typeahead#207]
Is there any way to shut the suggestion Box , it is always open even when there is no text, or nothing SELECTED, no way to close the suggestion box

**Comment by BataraSurya** [comment]
wondering the same thing... what I do right now is only to show sugestionbox when something is typed (pattern.length > 0). however I have now other problem.. the suggestion box is blinking real fast

**Comment by BenevidesLecontes** [comment]
These 3 flags do do the job for me 
```
                    hideOnError: true,
                    hideOnEmpty: true,
                    keepSuggestionsOnLoading: false,
```

**Comment by duongtricn2c** [comment]
> 3 lá cờ này thực hiện công việc cho tôi
> 
> ```
>                     hideOnError: true,
>                     hideOnEmpty: true,
>                     keepSuggestionsOnLoading: false,
> ```
> 
> Vấn đề duy nhất đối với tôi là tôi muốn đóng de suggestBox khi nhấp vào bên ngoài

I'm also having the same issue. Have you solved the issue?
