### ISSUE TITLE
Bugfix - blinking loadingBuilder

### ISSUE THREAD

**Issue by comerc** [AbdulRahmanAlHamali/flutter_typeahead#208]
I have blinking loadingBuilder when change focus. Solution - flag isLoading:

```dart
      suggestionsCallback: (String pattern) async {
        _isLoading = true;
        try {
          final data = await _load(pattern);
          return data;
        } finally {
          _isLoading = false;
        }
      },
      loadingBuilder: (BuildContext context) {
        if (!_isLoading) return null; // !!!
        return Align(
          alignment: Alignment.center,
          child: Padding(
            padding: const EdgeInsets.symmetric(vertical: 8.0),
            child: CircularProgressIndicator(),
          ),
        );
      },
```

**Comment by loicsacre** [comment]
Thank you ! I had just noticed this problem when scrolling

![m](https://imgur.com/D98TSqi.gif)

**Comment by dahabit** [comment]
I confirm the the issue is existing v1.8.1 , v1.8.3 and not existing in 1.8.0

**Comment by ethel39** [comment]
hello, is there a way to fix this issue?
also got this in flutter 1.17.1 stable and plugin version 1.8.5

**Comment by yuechaor** [comment]
v1.8.5  same issue

**Comment by yuechaor** [comment]
loadingBuilder: (context) => null, add this fixed the issue for me

**Comment by AlexBacich** [comment]
@yuechaor , well done finding this.

**Comment by CosmicPangolin** [comment]
I'm still seeing this error where LoadingBuilder is called before onSuggestionSelected during initial focus.
