### ISSUE TITLE
hideSuggestionsOnKeyboardHide not working

### ISSUE THREAD

**Issue by thomasschwarzott** [AbdulRahmanAlHamali/flutter_typeahead#215]
Hey guys,

thank you for your work! Unfortunately, we're experiencing that the hideSuggestionsOnKeyboardHide setting does not work. We need to keep the suggestions displayed when the keyboard is hidden.

From debugging the plugin, I found that your implementation of hideSuggestionsOnKeyboardHide is considered some lines later in the code - anyways, the suggestions box gets closed inside of the _focusNodeListener.

```
class _TypeAheadFieldState<T> extends State<TypeAheadField<T>> with WidgetsBindingObserver {
   void initState() {
    super.initState();
    
    ...

    this._focusNodeListener = () {
      if (_effectiveFocusNode.hasFocus) {
        this._suggestionsBox.open();
      } else {
        this._suggestionsBox.close();   // gets executed anyway 
      }
    };

   ...
   }
}
```

This happens in our app but also when I take the basic examples from the readme, where you claim that the desired behaviour can be provided simply by setting hideSuggestionsOnKeyboardHide to false.

**Comment by campanagerald** [comment]
Hi, is there an update to this? The plugin is good tho.
