### ISSUE TITLE
can i navigate within suggestion that generated while texting with up & down arrow - flutter web?

### ISSUE THREAD

**Issue by anandsubbu007** [AbdulRahmanAlHamali/flutter_typeahead#219]
can I select the suggestion that generated while texting using up & down arrow in flutter web. like in google search

![image](https://user-images.githubusercontent.com/55450843/86581781-38636f00-bf9e-11ea-8102-a6264266bcd8.png)
![image](https://user-images.githubusercontent.com/55450843/86581816-43b69a80-bf9e-11ea-91ea-f7f481e06336.png)

**Comment by franarolas** [comment]
Any workaround on this?

**Comment by leifarne** [comment]
I need the same thing.

**Comment by davebound** [comment]
Need the same

**Comment by NiranjanShah** [comment]
Awaiting response, will be gr8, if you respond.....

**Comment by sjmcdowall** [comment]
If someone implements this and does a PR -- and it's backwards compatible --I will happily merge it.
