### ISSUE TITLE
suggestionsCallback not getting called on actual IOS device

### ISSUE THREAD

**Issue by fbazbo** [AbdulRahmanAlHamali/flutter_typeahead#222]
It all seems to work fine in the iphone simulator, but when on an actual device the suggestionsCallback never seems to get called.  The textFieldConfiguration onchanged is getting called, but nothing ever makes it to the callback method. I should note I'm also using the TextEditingController. Here's what the code looks like:
```  
Widget buildTypeahead({@required LocationSelected selected, String label='Enter Value', String firstValue}) {
    final TextEditingController _typeAheadController = TextEditingController(text: selected.name,);
    return TypeAheadField(

      textFieldConfiguration: TextFieldConfiguration(
        autofocus: false,
        controller: _typeAheadController,

        decoration: InputDecoration(
          labelText: label,
          border: OutlineInputBorder(),
        ),
        onTap: () {
          activeField = selected;
          if (_typeAheadController.text==firstValue || _typeAheadController.text==kCurrentName || _typeAheadController.text==kLastTappedName) {
            _typeAheadController.text = '';
          }
        },

      ),

      suggestionsCallback: (text) async {
        return await getLocations(text, firstValue);
      },
      itemBuilder: (context, item) {
        return ListTile(title: Text(item ?? firstValue));
      },
      onSuggestionSelected: (item) {
        _typeAheadController.text = item;
        if (item!=null) {
          selected.name = item;
          selected.placemark = _searchLocations[item];
        }
      },

    );
  }

**Comment by sjmcdowall** [comment]
No one else seems to be having this issue ... ??  And a code snippet may not be enough to figure out what the issue is in your code .. How do you know it's not being called and the issue isbn't in your getLocations?  I don't see any debug code (output) or anything ..

**Comment by fbazbo** [comment]
I'm going to close this since something I did seems to have fixed it.  I had minimal debug code (which I removed from the snippet), because I was relying on breakpoints in the debugger.  I have a different issue with clearing the field via an action that I'll try to create an example for.

**Comment by liveaffiliates** [comment]
> No one else seems to be having this issue ... ?? And a code snippet may not be enough to figure out what the issue is in your code .. How do you know it's not being called and the issue isbn't in your getLocations? I don't see any debug code (output) or anything ..

This is happening for me as well. It is not being called when clicking the the dropdown text. I put a simple print statement and it is not firing.

`class TextTypeAheadField extends StatefulWidget {

  final String hintText;
  final Function onChanged;
  final String value;
  final List <String> list;

  TextTypeAheadField({
    @required this.hintText,
    @required this.list,
    this.value,
    this.onChanged,
  });

  @override
  _TextTypeAheadFieldState createState() => _TextTypeAheadFieldState();
}

class _TextTypeAheadFieldState extends State<TextTypeAheadField> {
  final TextEditingController _typeAheadController = TextEditingController();

  @override
  Widget build(BuildContext context) {

    return TypeAheadField(
      textFieldConfiguration: TextFieldConfiguration(
          autofocus: false,
          style: DefaultTextStyle.of(context).style.copyWith(
              fontStyle: FontStyle.italic
          ),
          decoration: InputDecoration(
            border: OutlineInputBorder(
              borderRadius: const BorderRadius.all(
                const Radius.circular(20.0),
              ),
              borderSide: BorderSide(
                width: 0,
                style: BorderStyle.none,
              ),
            ),
            filled: true,
            fillColor: textBoxBackgroundColor,
            hintText: widget.hintText,
            hintStyle: GoogleFonts.nunito(fontSize: 18, fontWeight: FontWeight.normal, color: greyText),

          ),
          controller: _typeAheadController
      ),
      suggestionsCallback: (String pattern) {
        return RecommendationService.getSuggestions(pattern, widget.list);
      },
      itemBuilder: (context, suggestion) {
        return ListTile(
          tileColor: Colors.red,
          title: Text(suggestion),
        );
      },
      onSuggestionSelected: (suggestion) {
        setState(() {
          print('suggestion selected');
          this._typeAheadController.text = suggestion;
        });
      },
    );
  }
}

class RecommendationService {
  static List<String> getSuggestions(String query, List<String> list) {
    print ('checking recommendation');
    List<String> matches = [];
    matches.addAll(list);

    matches.retainWhere((s) => s.toLowerCase().contains(query.toLowerCase()));
    return matches;
  }
}`
