### ISSUE TITLE
hideSuggestionsOnKeyboardHide not working on Android as expected

### ISSUE THREAD

**Issue by altayhunoglu** [AbdulRahmanAlHamali/flutter_typeahead#230]
Expectation:
When user clicks "Done" button on keybord and closes the keybord, suggestions should still be displayed.

Version:
  flutter_typeahead: 1.8.8

Flutter doctor -verbose:

[√] Flutter (Channel beta, 1.19.0-4.3.pre, on Microsoft Windows [Version 10.0.14393], locale tr-TR)
    • Flutter version 1.19.0-4.3.pre at C:\Users\ASUS\AppData\Local\Android\flutter
    • Framework revision 8fe7655ed2 (10 weeks ago), 2020-07-01 14:31:18 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\ASUS\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

**Comment by Techno-Disaster** [comment]
@altayhunoglu were you able to fix this?

**Comment by altayhunoglu** [comment]
No. I accepted it as it is.

**Comment by Techno-Disaster** [comment]
@KaYBlitZ @sjmcdowall Any workaround?

**Comment by harichandu1** [comment]
You should try 
 onEditingComplete: (){
       SystemChannels.textInput.invokeMethod('TextInput.hide');
 },
