### ISSUE TITLE
using  flutter stepper the ListTile not show

### ISSUE THREAD

**Issue by marcelocajaiba** [AbdulRahmanAlHamali/flutter_typeahead#232]
Hello, I am using Stepper and ListTile not showing .
 
what will be the problem?
I see the Return ListTitle but, not show Screen ! Thanks!

 child: Center(
          child: TypeAheadField(
            textFieldConfiguration: TextFieldConfiguration(
                autofocus: false,
                style: DefaultTextStyle.of(context)
                    .style
                    .copyWith(fontSize: 18, color: Colors.black),
                decoration: InputDecoration(
                    contentPadding:
                        new EdgeInsets.fromLTRB(5.0, 10.0, 5.0, 10.0)
                    // hintText: "Digite o Modelo",
                    )),
            suggestionsCallback: (pattern) async {
              // return SerVerConfig;
              return await getSuggestions2(pattern);
            },
            itemBuilder: (context, suggestion) {
              // print("name: ${suggestion['name']} ${suggestion['value']}");
              return ListTile(
                leading: Icon(Icons.directions_car),
                title: Text(suggestion['name']),
                subtitle: Text('valor :\$${suggestion['value']}'),
              );
            },
            onSuggestionSelected: (suggestion) {
              context = suggestion['value'];
              print("value: ${suggestion['value']}");
              // Navigator.of(context).push(MaterialPageRoute(
              //     builder: (context) => ProductPage(product: suggestion)));
            },
          ),

**Comment by marcelocajaiba** [comment]
Hi , a find out the problem.

Not user  SingleChildScrollView with Stepper  in         child: TypeAheadFormField(

I change SingleChildScrollView  to Expander

 return SingleChildScrollView(
        padding: EdgeInsets.fromLTRB(0, 0, 0, 0),
        child: Stepper(
to
 return Expander(
        padding: EdgeInsets.fromLTRB(0, 0, 0, 0),
        child: Stepper(

**Comment by sjmcdowall** [comment]
Good find!

**Comment by marcelocajaiba** [comment]
Somebody  found out solution ?

**Comment by ReniDelonzek** [comment]
I have the same issue
