### ISSUE TITLE
Add resize() SuggestionsBox when open calls

### ISSUE THREAD

**Issue by romathebest** [AbdulRahmanAlHamali/flutter_typeahead#233]
I have faced with the problem of recalculating SuggestionBox size. 
When the input field is on the bottom of the screen, I scroll it up, but the size is not changing and it shows small.

Please add this.resize() on each opening SuggestionBox

**Comment by ilDeffo** [comment]
I have the problem of resizing when I have two boxes aside eachother. I set them to expand when tapped, but the suggestion dropdown does not
