### ISSUE TITLE
Show "default" suggestion when textfield is empty

### ISSUE THREAD

**Issue by c0c4i** [AbdulRahmanAlHamali/flutter_typeahead#234]
Hello I have decided to show favourites product when textfield is empty but the suggestionsCallback is called only when I type for the first time. In fact if I type one character and delete it, it will show favourites product, so do you have suggestion to implement this? It would be great, thanks
![issue](https://user-images.githubusercontent.com/45185144/93006975-5d0e3100-f563-11ea-9499-c1c6799ecf90.gif)

**Comment by xyzbilal** [comment]
add getImmediateSuggestions: true, to your widget and your products will be shown immediately.

**Comment by leifarne** [comment]
> add getImmediateSuggestions: true, to your widget and your products will be shown immediately.

I had the same question, and that solves the problem for me, thanks.
