### ISSUE TITLE
Keyboard validation button close the suggestions

### ISSUE THREAD

**Issue by Naografix** [AbdulRahmanAlHamali/flutter_typeahead#236]
Hello,

When I search something in my searchbar and I hit validation button it close the suggestion because I loose focus.

How can I fix that?

![image](https://user-images.githubusercontent.com/6979203/93687972-96deba80-fac2-11ea-9d4f-b5c22e32a65f.png)

Thank you

**Comment by xyzbilal** [comment]
maybe adding this to TextFieldConfiguration might solve your problem.

 ```
onEditingComplete: (){
          SystemChannels.textInput.invokeMethod('TextInput.hide');
        },
```
