### ISSUE TITLE
Change loading color?

### ISSUE THREAD

**Issue by Naografix** [AbdulRahmanAlHamali/flutter_typeahead#237]
Hello, it's not really an issue but I want to know how can I change the loading animation color?

Thank you, continue this amazing works!

**Comment by capemsx** [comment]
Hello,
I've found a solution for this.
You just need to change your apps primaryColor in ThemeData() for changing the color the loading animation. 

You can do it like that:
`primaryColor: Colors.deepOrangeAccent, colorScheme: ColorScheme.fromSwatch(primarySwatch: Colors.deepOrange)`
(In my case my accentColor is deepOrangeAccent)

You can find ThemeData in your app in your root widget.

Hope it helps!
