### ISSUE TITLE
Display suggestion only when the user types

### ISSUE THREAD

**Issue by ForceGT** [AbdulRahmanAlHamali/flutter_typeahead#240]
I have a use case (as shown in the example gif) of making the suggestion box appear only when the user starts typing
In my case the suggestion box appears as soon as the Field has focus 

![image](https://user-images.githubusercontent.com/31688051/94988076-45d1ca80-0588-11eb-902e-f456cc8cd3a8.png)

**Comment by Swepilot** [comment]
This is my workaround, checking if the pattern is not blank:

```
suggestionsCallback: (pattern) async {
  if (pattern != "") {
    return await getAirports(pattern);
  }
}
```
