### ISSUE TITLE
type 'String' is not a subtype of type 'int' of 'index'

### ISSUE THREAD

**Issue by asdk2006** [AbdulRahmanAlHamali/flutter_typeahead#241]
String capitalize(String s) => s[0].toUpperCase() + s.substring(1);
  var textsearching = List<String>();
  Future<List> readdatsearch(String searchname) async {
    textsearching.clear();
    ii = 0;
    print(capitalize(searchname));
    firestoreInstance
        .collection("data")
        .where('poi_name', isGreaterThanOrEqualTo: capitalize(searchname))
        .where('poi_name', isLessThan: capitalize(searchname) + 'z')
        // .where('poi_name', arrayContains: capitalize(searchname.trim()))
        .snapshots()
        .listen((value) {
     
      textsearching.add(value.docs[ii].data().toString());
      value.docs.forEach((result) {
       
      });
    });

    return textsearching;
  }

TypeAheadField(
        textFieldConfiguration: TextFieldConfiguration(
            controller: searchcontroller,
            autofocus: true,
            style: DefaultTextStyle.of(context)
                .style
                .copyWith(fontStyle: FontStyle.italic),
            decoration: InputDecoration(
                border: InputBorder.none,
                hintStyle: TextStyle(fontFamily: 'DTP Naskh S En'),
                hintText: 'Rechercher',
               
                    )
                    ),
        suggestionsCallback: (pattern) async {
         
          return readdatsearch(pattern);
        },
        itemBuilder: (context, suggestion) {
         
          return ListTile(
            leading: Icon(Icons.shopping_cart),
            title: Text(suggestion['poi_name'].toString()),
            // subtitle: Text('\$${suggestion['poi_name']}'),
          );
        },
        onSuggestionSelected: (suggestion) {
          // Navigator.of(context).push(MaterialPageRoute(
          //     builder: (context) => ProductPage(product: suggestion)));
        },
      )
and i got this error 
type 'String' is not a subtype of type 'int' of 'index'
how i solve this 

the data i retrive
{
  
    "data" : [ {
      "Adresse" : "5 Avenue Anatole France, 75007 Paris, France",
      "Affluence" : "Forte",
      "Categorie" : "1",
      "Couvert" : "0",
      "DateDebut" : "20180828",
      "DateFin" : "20180828",
      "DateModif" : "2018-08-28 19:04:15.932",
      "Devise" : "0",
      "DifficulteParcours" : "0",
      "Email" : "",
      "HorairesDimanche" : "10h00-12h00;;12h00-23h00",
      "HorairesJeudi" : "10h00-12h00;;12h00-23h00",
      "HorairesLundi" : "10h00-12h00;;12h00-23h00",
      "HorairesMardi" : "10h00-12h00;;12h00-23h00",
      "HorairesMercredi" : "10h00-12h00;;12h00-23h00",
      "HorairesSamedi" : "10h00-12h00;;12h00-23h00",
      "HorairesVendredi" : "10h00-12h00;;12h00-23h00",
      "IDLocalite" : "29663",
      "IDPOI" : "4",
      "Latitude" : "48.8583760",
      "Longitude" : "2.294501",
      "NomLocalite" : "Paris Palais-Bourbon 7e arrondissement",
      "Recommandation" : "famille",
      "Services" : "1,5,7,",
      "SiteWeb" : "www.toureiffel.paris",
      "Tarif" : "20",
      "Telephone" : "08 92 70 12 39",
      "TempsMoyen" : "120",
      "URLImagePrincipale" : "http://217.160.2.114/BACK_WHEREIN_V2_WEB/29663/Toureiffel/ImagePrincipale/architecture-1869125_1280.jpg",
      "URLImages" : "",
      "isenable" : "0",
      "long_description_fr" : "",
      "open_h24" : "0",
      "poi_name" : "Tour Eiffel",
      "schedule_details_en" : "",
      "schedule_details_fr" : "\t\nAscenseurs\n7 Juillet - 1er Septembre\n9:00 - 0:45\nEscaliers\n9:00 - 0:45\nDernier accés à minuit.\n\nAscenceurs\nLe reste de l'année\n9:30 - 23:45\nDerniére montée à 23h.\n(pour le sommet 22h30)\nEscaliers\n9:30 - 18:30\nDernier accés à 18h.",
      "short_description_fr" : "Deux ans, deux mois et 5 jours\nSa construction en 2 ans, 2 mois et 5 jours, fut une véritable performance technique et architecturale. 芦 Utopie réalisée 禄, prouesse technologique, elle fut à la fin du 19éme siécle la démonstration du génie français incarné par Gustave Eiffel, un point une tour de 300 métres est",
      "tarif_detail_en" : "",
      "tarif_detail_fr" : "Billet Sommet\n\nAscenseurs\nAdultes : 25鈧琝nGroupe scolaire 12-24 ans :12,50鈧琝nTarifs réduits : 6,30鈧琝n- 4 ans  / RSA  : Gratuit\n\nBillet 2éme étage\nEscaliers\nAdultes :10鈧琝nGroupe scolaire 12-24 ans : 5鈧琝nTarifs réduits : 2,50鈧琝n-4 ans / RSA :Gratuit\n\nBillet sommet\nEscaliers puis Ascenseur\nAdultes : 19鈧琝nGroupe scolaire 12-24 ans :9,50鈧琝nTarifs réduits : 4,80鈧琝n-4 ans  / RSA : Gratuit"
    }, {
      "Adresse" : "Place de la Bastille, 75004 Paris, France",
      "Affluence" : "Moyenne",
      "Categorie" : "1",
      "Couvert" : "0",
      "DateDebut" : "20180828",
      "DateFin" : "20180828",
      "DateModif" : "2018-08-28 19:21:29.114",
      "Devise" : "0",
      "DifficulteParcours" : "0",
      "Email" : "",
      "HorairesDimanche" : "00h00-12h00;;12h00-00h00",
      "HorairesJeudi" : "00h00-12h00;;12h00-00h00",
      "HorairesLundi" : "00h00-12h00;;12h00-00h00",
      "HorairesMardi" : "00h00-12h00;;12h00-00h00",
      "HorairesMercredi" : "00h00-12h00;;12h00-00h00",
      "HorairesSamedi" : "00h00-12h00;;12h00-00h00",
      "HorairesVendredi" : "00h00-12h00;;12h00-00h00",
      "IDLocalite" : "29667",
      "IDPOI" : "5",
      "Latitude" : "48.8531827",
      "Longitude" : "2.369144",
      "NomLocalite" : "Paris Popincourt 11e arrondissement",
      "Recommandation" : "famille",
      "Services" : "1,7,",
      "SiteWeb" : "www.parisinfo.com",
      "Tarif" : "0",
      "Telephone" : "01 49 52 42 63",
      "TempsMoyen" : "30",
      "URLImagePrincipale" : "http://217.160.2.114/BACK_WHEREIN_V2_WEB/29667/Placedelabastille/ImagePrincipale/1200px-Place_de_la_Bastille_Paris.jpg",
      "URLImages" : "",
      "isenable" : "0",
      "long_description_fr" : "",
      "open_h24" : "0",
      "poi_name" : "Place de la bastille",
      "schedule_details_en" : "",
      "schedule_details_fr" : "Ouvert en permanence",
      "short_description_fr" : "En son centre se dresse la colonne de Juillet, surmontée du fameux Génie de la Liberté, commémorant la révolution de 1830. Mais cest pour une autre révolution que la place est bien connue : celle de 1789. 脌 cette époque, elle était occupée par la prison de la Bastille, symbole du pouvoir absolu de lancien Régime. De cette ge么le, détruite peu aprés la Révolution française, il ne reste rien.\n Aujo",
      "tarif_detail_en" : "",
      "tarif_detail_fr" : ""
    }, {
      "Adresse" : "L'Arc de Triomphe de l'Etoile, 75017 Paris, France",
      "Affluence" : "Forte",
      "Categorie" : "1",
      "Couvert" : "0",
      "DateDebut" : "20180906",
      "DateFin" : "20180906",
      "DateModif" : "2018-09-06 10:38:51.372",
      "Devise" : "0",
      "DifficulteParcours" : "0",
      "Email" : "@",
      "HorairesDimanche" : "10h00-12h00;;12h00-23h00",
      "HorairesJeudi" : "10h00-12h00;;12h00-23h00",
      "HorairesLundi" : "10h00-12h00;;12h00-23h00",
      "HorairesMardi" : "10h00-12h00;;12h00-23h00",
      "HorairesMercredi" : "10h00-12h00;;12h00-23h00",
      "HorairesSamedi" : "10h00-12h00;;12h00-23h00",
      "HorairesVendredi" : "10h00-12h00;;12h00-23h00",
      "IDLocalite" : "29664",
      "IDPOI" : "6",
      "Latitude" : "48.8737940",
      "Longitude" : "2.295027",
      "NomLocalite" : "Paris 脡lysée  8e arrondissement",
      "Recommandation" : "famille",
      "Services" : "3,4,5,",
      "SiteWeb" : "www.paris-arc-de-triomphe.fr",
      "Tarif" : "12",
      "Telephone" : "01 55 37 73 77",
      "TempsMoyen" : "30",
      "URLImagePrincipale" : "http://217.160.2.114/BACK_WHEREIN_V2_WEB/29664/Arcdetriomphe/ImagePrincipale/places-2569259_1280.jpg",
      "URLImages" : "http://217.160.2.114/BACK_WHEREIN_V2_WEB/29664/Arcdetriomphe/ImagesSecondaires/Arc-de-Triomphe-de-face-630x405-C-Thinkstock.jpg;;;http://217.160.2.114/BACK_WHEREIN_V2_WEB/29664/Arcdetriomphe/ImagesSecondaires/triumphal-arch-1031191_1280.jpg;;;http://217.160.2.114/BACK_WHEREIN_V2_WEB/29664/Arcdetriomphe/ImagesSecondaires/france-2592252_1280.jpg;;;",
      "isenable" : "0",
      "long_description_fr" : "",
      "open_h24" : "0",
      "poi_name" : "Arc de Triomphe",
      "schedule_details_en" : "",
      "schedule_details_fr" : "FERMETURES\n\n1er janvier, 1er mai, 8 mai (matin), 14 juillet (matin), 11 novembre (matin) et 25 décembre.",
      "short_description_fr" : "Un point de vue unique. Du haut de la terrasse panoramique, le regard embrasse tout Paris.  \r\n \r\nL'antique revisité. L'architecte Jean-François Chalgrin s'inspire de l'arc romain de Titus à arche unique, mais s'en émancipe par des dimensions exceptionnelles (environ 50 m de hauteur, 45 m de longueur et 22 m de largeur) et l'abandon des colonnes. \r\n \r\nUn haut lieu des grandes manifestations nationa",
      "tarif_detail_en" : "",
      "tarif_detail_fr" : "TARIF R脡DUIT\n\nProfessionnels du tourisme, jeunes (18-25 ans) hors Union Européenne, et enseignants étrangers. \n9鈧琝n"
    } ]
  
}

**Comment by sjmcdowall** [comment]
@asdk2006 -- Can't help but believe this is just a general coding error in your code as no one else this iissue.  Have you running it through a debugger and seeing where the stack trace and variable values are etc etc?  Maybe a simple test program showing the error that you can share if its still a problem.

**Comment by ValeraT1982** [comment]
**@asdk2006,** **readdatsearch** returns list of strings, so your **suggestion** in **itemBuilder** is a string but you are accessing it like it's dynamic (**suggestion['poi_name']**).
