### ISSUE TITLE
Exceptions thrown for certain user inputs (including in the Example app), when navigating away from a screen

### ISSUE THREAD

**Issue by jesper372** [AbdulRahmanAlHamali/flutter_typeahead#243]
Exceptions are thrown for certain user inputs, as described below. I initially noticed them in my own app, but confirmed that they occur in the Example app as well.

To reproduce:

**iOS**
In Example 1, don't enter any text. Instead, just select Example 2 from the tab bar. You might get an exception already at this point. If not, continue to select Example 3, and an exception is thrown (see below for details).

The same thing happens if, instead of navigating instantly away from Example 1, you enter some text (say, '0') and then (without pressing return/enter to enter the selection) proceed to navigate as above.

The problem is not unique to Example 1. Remove Example 1 from the code, and then, in Example 2, just select the field (without typing anything into it) - the overlay comes up. Now, without selecting or typing anything, navigate away from the page - you get an exception. The same issue occurs if you type something in the field but navigate away from the page without making a selection (and without pressing return/enter to enter the selection).

The issue persists even when hideOnEmpty is set to true for Example 2; typing in something for which there is no match again results in an exception, even though (of course) the overlay doesn't appear.

**Android**
In Android, the behaviour is similar to that for iOS for Example 1. For Example 2, the exception is not thrown anywhere near as reliably; it can take a lot more switching back and forth between tabs before it happens, if it happens at all.

The exceptions thrown are always some combination of the following two:

> ════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
BoxConstraints has a NaN value in maxHeight.
The relevant error-causing widget was: MaterialApp file:///flutter_app/lib/material_app.dart:9:12

and/or

> ════════ Exception caught by rendering library ═════════════════════════════════════════════════════
RRect argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 37: ''
The relevant error-causing widget was:
TypeAheadField file:///flutter_app/lib/material_app.dart:48:11
The following RenderObject was being processed when the exception was fired: RenderEditable#42870 relayoutBoundary=up15
parentData: (can use size)
constraints: BoxConstraints(w=287.0, 0.0<=h<=Infinity)
size: Size(287.0, 17.0)
cursorColor: Color(0x4f2196f3)
showCursor: ValueNotifier#cbdbb(true)
maxLines: 1
minLines: null
selectionColor: Color(0xff90caf9)
textScaleFactor: 1.0
locale: en_US
selection: TextSelection(baseOffset: 0, extentOffset: 0, affinity: TextAffinity.downstream, isDirectional: false)
offset: ScrollPositionWithSingleContext#7b29d(offset: 0.0, range: 0.0..0.0, viewport: 287.0, ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#12636, ScrollDirection.idle)
text: TextSpan
debugLabel: ((englishLike body1 2014).merge(blackCupertino bodyText2)).copyWith
inherit: false
color: Color(0xdd000000)
family: .SF UI Text
size: 14.0
weight: 400
style: italic
baseline: alphabetic
decoration: TextDecoration.none
""
RenderObject: RenderEditable#42870 relayoutBoundary=up15
parentData: (can use size)
constraints: BoxConstraints(w=287.0, 0.0<=h<=Infinity)
size: Size(287.0, 17.0)
cursorColor: Color(0x4f2196f3)
showCursor: ValueNotifier#cbdbb(true)
maxLines: 1
minLines: null
selectionColor: Color(0xff90caf9)
textScaleFactor: 1.0
locale: en_US
selection: TextSelection(baseOffset: 0, extentOffset: 0, affinity: TextAffinity.downstream, isDirectional: false)
offset: ScrollPositionWithSingleContext#7b29d(offset: 0.0, range: 0.0..0.0, viewport: 287.0, ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#12636, ScrollDirection.idle)
text: TextSpan
debugLabel: ((englishLike body1 2014).merge(blackCupertino bodyText2)).copyWith
inherit: false
color: Color(0xdd000000)
family: .SF UI Text
size: 14.0
weight: 400
style: italic
baseline: alphabetic
decoration: TextDecoration.none
""
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by jesper372** [comment]
I've found out that this is actually a bug in Flutter as opposed to the typeahead package - see https://github.com/flutter/flutter/issues/66457 for details. I'm therefore closing this issue.

**Comment by sjmcdowall** [comment]
@jesper372  -- Thanks for digging into this.  Seemed odd from a first glance!

**Comment by minhdanh** [comment]
@jesper372 I'm still having this issue with Flutter 2.2.3. Could you managed to find a solution?

**Comment by jesper372** [comment]
@minhdanh I haven't followed up on it, but AFAICT the place to check is https://github.com/flutter/flutter/issues/70610.
