### ISSUE TITLE
NoSuchMethodError: tried to call a non-function, such as null: 'dynamicToLvoid(...).as(...)'

### ISSUE THREAD

**Issue by franarolas** [AbdulRahmanAlHamali/flutter_typeahead#245]
I'm getting this error when I'm typing in the TypeAheadFormField on each char:

`NoSuchMethodError: tried to call a non-function, such as null: 'dynamicToLvoid(...).as(...)'`

It is happening on Flutter Web in the last beta version, it delays a bit the suggestions.
I tested it on Android and I'm receiving the following error on the same situation too:
```
The method 'call' was called on null.
Receiver: null
Tried calling: call()
```

I thought it was my project so I tested it on the example project and I got the same output(That's why I'm not posting any code fragment).

Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [VersiÃ³n 10.0.18363.1139], locale es-ES)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
[√] VS Code, 64-bit edition (version 1.42.1)
[√] Connected device (4 available)

• No issues found!
```

**Comment by emmett-deen** [comment]
Also having this issue

**Comment by franarolas** [comment]
@emmett-deen Found out that I was using a form field without any validation, Flutter accepts that but not TypeAhead, just change to normal field and it will work.
