### ISSUE TITLE
Does not always show total list of possible outcomes if Future return in suggestionsCallback

### ISSUE THREAD

**Issue by sjmcdowall** [AbdulRahmanAlHamali/flutter_typeahead#25]
<img width="423" alt="screen shot 2019-01-18 at 7 36 43 am" src="https://user-images.githubusercontent.com/2034925/51387396-e56cd200-1af3-11e9-86b8-fdc19bea296c.png">
<img width="423" alt="screen shot 2019-01-17 at 4 11 54 pm" src="https://user-images.githubusercontent.com/2034925/51387102-e7826100-1af2-11e9-814b-e9e84ebfc457.png">
Please see the screenshot .. I changed the TypeAhead to use a Future in the suggestionsCallback .. however, as can be seen it doesn't always render the full list upon entry and it being invoked if 'getImmediateSuggestions' == true. 

Also -- I can't help but notice that the suggestions box is overlaying on top of the Widgets I have .. which is ok .. just .. weird?  Is this proper behavior?  I basically have a simple layout like

```

  Widget _buildMainBody() {
    return Column(
      children: <Widget>[
        _buildSearchField(),
        _buildShowTemplate(),
        SizedBox(
          height: 20.0,
        ),
        _buildNavButtons(),
      ],
    );
  }

Where buildSearchField() is the TypeAhead .. and the showTemplate is a simple Text if there is one select and the _buildNavButtons is the Next button ... 

However, the main issue is the lack of proper rendering of the list upon entry .. not sure if I am doing something wrong?  

Oh I can also confirm the itemBuilder IS being called all 5 times (in this case) -- I have a print() in there .. so it's getting all the data.. <shrug> 

Cheers!

**Comment by KaYBlitZ** [comment]
Hi @sjmcdowall. I can't seem to replicate the Future problem you are having. I wrapped my suggestions callback in a Future.delayed() with a 1 second delay, but was still able to get the full list of results rendered. Not sure if you're doing something different.

As for the suggestions list overlaying your other widgets, ie: the next button, I believe that is proper behavior. The user would have to either make a selection or cancel their input to proceed.

**Comment by sjmcdowall** [comment]
The delay maybe too long .. try a 100 ms delaybor 50?  I can reproduce pretty much at will do maybe I can get the timing of the delay .. also the amount it shows is not consistent - sometimes it’s one item sometimes two - sometimes two and 1/2 ... ! 

And ok - the hiding part is fine - just sort of looked odd

**Comment by sjmcdowall** [comment]
Not reproducible since last few updates..
