### ISSUE TITLE
unable to set textScaleFactor

### ISSUE THREAD

**Issue by sureace** [AbdulRahmanAlHamali/flutter_typeahead#253]
Hi 
   Not able to set textScaleFactor for the component. Will you please add this to the component.
Thanks

**Comment by awhitford** [comment]
Have you tried adjusting the `textScaleFactor` by wrapping the component with a [MediaQuery](https://api.flutter.dev/flutter/widgets/MediaQuery-class.html)?  Like:
```dart
MediaQuery(
  data: MediaQueryData(textScaleFactor: 2.0),
  child: TypeAheadField( ... ),
),
```
