### ISSUE TITLE
flutter_typeahead bug No podspec found for `flutter_keyboard_visibility_web` 

### ISSUE THREAD

**Issue by blue492** [AbdulRahmanAlHamali/flutter_typeahead#259]
Iam using Flutter in Mac -> Android studio and when I write pod install in the terminal. It show me

  ```
  Analyzing dependencies
[!] No podspec found for `flutter_keyboard_visibility_web` in .symlinks/plugins/flutter_keyboard_visibility_web/ios`

  ```
flutter_typeahead plugin has a Dependencies with flutter_keyboard_visibility 

Iam using flutter from one year ago, It is the first time it happen for me. 
I cannot run the app. I dont have a plugin with this name flutter_keyboard_visibility_web in pubspec

How to fix it, thanks

**Comment by shero1111** [comment]
I have the same issue...any idea how to solve?

I even added the flutter_keyboard_visibility_web dependency in pubspec.yaml...but didn´t has any effect.

**Comment by blue492** [comment]
@AbdulRahmanAlHamali
@awhitford  @kika  @sterlp  how to solve it, thanks

**Comment by blue492** [comment]
The solution is here:
https://github.com/MisterJimson/flutter_keyboard_visibility/issues/52
