### ISSUE TITLE
package has misleading name

### ISSUE THREAD

**Issue by RandalSchwartz** [AbdulRahmanAlHamali/flutter_typeahead#260]
This is not "typeahead". This is "autocomplete".  Typeahead is when you can type characters before the system has echoed them, but they are in a queue waiting to process for you.  You kids have probably never seen that. 👍 This is autocomplete (or autocorrect {grin}) where further characters are guessed or proposed by the system.

**Comment by sjmcdowall** [comment]
You are correct sir!  And yes i have seen real typeahead, I am as old as you (or close) and fondly remember programming in Perl (so yes, you are recognized!). The name wasn't mine to choose and of course, unless I am missing something, changing it would break countless projects.

**Comment by RandalSchwartz** [comment]
You could deprecate this package, and inform people in your docs that they should be using the other (properly named) package.
