### ISSUE TITLE
Expected 0 type arguments

### ISSUE THREAD

**Issue by Silfalion** [AbdulRahmanAlHamali/flutter_typeahead#270]
Getting this issue since this morning:

`/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.1.0/lib/src/fields/form_builder_typeahead.dart:184:9: Error: Expected 0 type arguments.
  final TextFieldConfiguration<T> textFieldConfiguration;
        ^
`

in the fomr builder plugin depended on flutter typehead.

This is most likely caused by the 1.9.2 update, as adding and fixing the plugin to "<=1.9.1" in pubspec.yaml fixes the issue. Is it possible to look into it?

**Comment by nstrelow** [comment]
Having the same problem

**Comment by sjmcdowall** [comment]
Anyway to test if removing the <T> from line 184 of that package fixes the issue?

**Comment by Silfalion** [comment]
@sjmcdowall you can use the version 1.9.1 but if you prefer/need 1.9.2, this person gave a code editing level fix, on the other issue:

https://github.com/danvick/flutter_form_builder/issues/674#issuecomment-756436310

**Comment by karimkod** [comment]
@sjmcdowall Tried to find any way to surpass this, couldn't find any. I think this is causing issues with written code. We should move the update to the 2.0.0 version of the package. Thanks

**Comment by evhfla** [comment]
I have the same issue when using version 1.9.2 in combination with the the latest version of flutter_form_builder (4.2.0).  I had to downgrade the latter to version 3.14.1 to get my application to compile.  Downgrading the former to version 1.9.1 did not work if I still kept the latest version of flutter_form_builder.

**Comment by nstrelow** [comment]
For me downgrading to 1.9.1 worked. What's your error?
If you have the same error, execute `flutter pub get` and check again

**Comment by sjmcdowall** [comment]
OK -- created 1.9.3 which is a reversion back to 1.9.1 to solve the backward compatibility issue. Will create 2.0 "soon" which is the old 1.9.2. :)  Hope that's not confusing.

**Comment by Silfalion** [comment]
Crystal, man. Thank you!

**Comment by sjmcdowall** [comment]
OK -- V 2.0.0 has the type changes .. and V 1.9.3 has the old Types

**Comment by sjmcdowall** [comment]
Going to close this with the 2 releases.
