### ISSUE TITLE
return List<dynamic> form backend service get error

### ISSUE THREAD

**Issue by YouSour** [AbdulRahmanAlHamali/flutter_typeahead#271]
hi , i got a problem , i try to return list<dynamic> from backend service , but it keep getting error 
`Failed assertion: line 299 pos 16: 'T == String || selectionToTextTransformer != null': is not true.
`
any idea about this issue , or did i miss something ?

![Screenshot_1610439736](https://user-images.githubusercontent.com/9318106/104288292-2f71ce00-54ea-11eb-8527-3516523f7773.png)

**Code :**

> FormBuilderTypeAhead(
                          decoration: fbTextFieldStyle(labelText: "Location"),
                          name: 'location',
                          suggestionsCallback: (pattern) async {
                            return await GlobalLookUpList.getSuggestions(
                                pattern);
                          },
                          itemBuilder: (context, suggestion) {
                            return ListTile(
                              leading: Icon(Icons.shopping_cart),
                              title: Text(suggestion['name']),
                              subtitle: Text('\$${suggestion['price']}'),
                            );
                          },
                          onSuggestionSelected: (suggestion) {
                            print(suggestion);
                          },
                        ),

**Comment by sjmcdowall** [comment]
What version?  2.0.0 has the new Types and 1.9.3 has the old ones for backward compatibility.

**Comment by YouSour** [comment]
version ^1.9.1 @sjmcdowall

**Comment by sjmcdowall** [comment]
@YouSour -- but what version are you running?  You either want 1.9.3 or 2.0.0 depending on your code (I can't tell which is the proper one) ..  Make sure to update to 1.9.3  .. and if the same error -- try 2.0.0 :)

**Comment by YouSour** [comment]
@sjmcdowall by the way i'm using flutter_form_builder package that depend on this package and i want to know this package can return only List<String>  or what ?

**Comment by YouSour** [comment]
@sjmcdowall solved , my bad i forgot implement some params
