### ISSUE TITLE
Grouping suggestions

### ISSUE THREAD

**Issue by ashemetov** [AbdulRahmanAlHamali/flutter_typeahead#282]
Thank you for the excellent plugin.
There is one thing that I think can improve user experience - categories of suggestions aka grouping suggestions.
Let's say every suggestion will have a category:
'Test Site 1' - 'Online Tests'
'Test Site 2' - 'Online Tests'
'Test Book 1' - 'Books'
'Test Book 2' - 'Books'
So when user enter 'test' dropdown will show suggestions like:

Online Tests
- Test Site 1
- Test Site 1

Books
- Test Book 1
- Test Book 1

Here is an example of js library that does it: https://github.com/kraaden/autocomplete#grouping-suggestions

**Comment by kaseyrossanderson** [comment]
Why was this ticket closed? I would really like this feature if at all possible.
