### ISSUE TITLE
suggestionsCallback called Immediate 

### ISSUE THREAD

**Issue by Sachinsowri** [AbdulRahmanAlHamali/flutter_typeahead#288]
I use flutter_typeahead :^2.0.0

flutter_typeahead version 1.8.0 above  suggestionsCallback called immediately while textfiled got focus and then not result found message showed,

in flutter_typeahead : ^1.8.0  worked fine suggestion callback called while typeing

how solve this suggestionsCallback  issue i am also set getImmediateSuggestions : false even suggestion callback called,  and now i switch to version 1.8.0

**Comment by mzdm** [comment]
Same, it is a pretty big breaking change.

Also `debounce` seems to be ignored, which is bad as well

@sjmcdowall could you have a look at it, please.

I use `3.0.0-nullsafety.0`, flutter_typeahead: `2.0.0` didn't do this.

**Comment by SardorbekR** [comment]
Has anyone found a solution?

**Comment by mzdm** [comment]
FYI there's Autocomplete widget implemented in Flutter 2. https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/293
It's probably better to switch to that.

**Comment by sjmcdowall** [comment]
Is it actually out and available now?  THe new Autocomplete widget?  But yes -- switching over to that would seem to make sense

**Comment by mzdm** [comment]
Don't know really.. if I didn't see it mentioned I wouldn't know that widget exists. I will have yet to try. But the widget is available in the docs so it should be stable (Flutter 2), however, it probably does not offer many features (like debounce) so please do not deprecate this package yet.
