### ISSUE TITLE
AutocompleteCore in Flutter 2

### ISSUE THREAD

**Issue by wiradikusuma** [AbdulRahmanAlHamali/flutter_typeahead#293]
Flutter 2 now has an official autocomplete, https://github.com/flutter/flutter/pull/62927 -- just wondering what's the plan for this plugin in the future?

**Comment by sjmcdowall** [comment]
Good headsup -- I think when this feature has been fully made in GA -- then in most liklihood this package will be deprecated. That's my guess anyway

**Comment by juzimmer** [comment]
I must be missing something but I don't see async functionality with Flutters Autocomplete for on the fly api calls. Am I overlooking something ?

**Comment by gustav3d** [comment]
> I must be missing something but I don't see async functionality with Flutters Autocomplete for on the fly api calls. Am I overlooking something ?

Its a correct observation.
They kinda missed the entire point.

**Comment by vaind** [comment]
> I must be missing something but I don't see async functionality with Flutters Autocomplete for on the fly api calls. Am I overlooking something ?

`optionsBuilder` is probably what you are looking for?

```dart
Autocomplete<T>(
  optionsBuilder: (TextEditingValue input) async {}
  ...
)

// typedefed as
AutocompleteOptionsBuilder<T extends Object> = FutureOr<Iterable<T>> Function(
TextEditingValue textEditingValue
)
```
