### ISSUE TITLE
Desktop - Arrow keys support

### ISSUE THREAD

**Issue by selvam920** [AbdulRahmanAlHamali/flutter_typeahead#298]
Is there any possible to select dropdown item by keyboard arrow down or up keys

**Comment by sjmcdowall** [comment]
This hasn't been -- well -- anything for Desktop support -- however, I would think arrow key support would be built into the main Desktop logic (i.e. Flutter) and not have to be dealt with in all I/O packages .. You sure there isn't something else you need to do for this in the main logic?

**Comment by Sunbreak** [comment]
The built-in `Autocomplete` supports arrow keys now: https://github.com/flutter/flutter/issues/82783

**Comment by flutter-painter** [comment]
How about preventing keyboard up and down from having any effect to begin with ?
On the first touch of downkey users are confused into thinking arrows are going to work but next touch nothing happens.
Simply removing this counter-intuitive behaviour might already avoid this disorienting behaviour.

line 747 :

```dart
KeyEventResult _onKeyEvent(FocusNode _, RawKeyEvent event) {
    if (event.isKeyPressed(LogicalKeyboardKey.arrowUp) ||
        event.isKeyPressed(LogicalKeyboardKey.arrowDown)) {
        // do nothing to avoid puzzling users until keyboard arrow nav is implemented
    } else {
      _keyboardSuggestionSelectionNotifier.onKeyboardEvent(event);
    }
    return KeyEventResult.ignored;
  }
```
