### ISSUE TITLE
Bug: suggestions The getter 'isEmpty' was called on null.

### ISSUE THREAD

**Issue by blue492** [AbdulRahmanAlHamali/flutter_typeahead#299]
I get the following error messages when I tap on flutter_typeahead textbox and shows loading animation, and I cannot search about something.
 please fix that  
```
E/flutter (25987): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: NoSuchMethodError: The getter 'isEmpty' was called on null.
E/flutter (25987): Receiver: null
E/flutter (25987): Tried calling: isEmpty
E/flutter (25987): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
E/flutter (25987): #1      _SuggestionsListState._getSuggestions.<anonymous closure> (package:flutter_typeahead/flutter_typeahead.dart:1092:44)
E/flutter (25987): #2      State.setState (package:flutter/src/widgets/framework.dart:1267:30)
E/flutter (25987): #3      _SuggestionsListState._getSuggestions (package:flutter_typeahead/flutter_typeahead.dart:1090:9)
E/flutter (25987): <asynchronous suspension>
```

I solved the issue by removing from following if `|| suggestions.isEmpty`
```
 if (error != null || suggestions.isEmpty) {
            animationStart = 1.0;
          }
```

**Comment by sjmcdowall** [comment]
What version of the package??

**Comment by blue492** [comment]
> What version of the package??

flutter_typeahead: ^3.1.1

**Comment by sjmcdowall** [comment]
I looked at the code -- this condition should, in theory, never happen.  What is a re-createable git repo that shows how to reproduce the error?  My gut is telling me you have some bad code in your getSuggestions that's returning an illegal value (i.e. null) .. it should always return an empty Iterable list or an error ..

**Comment by blue492** [comment]
> I looked at the code -- this condition should, in theory, never happen. What is a re-createable git repo that shows how to reproduce the error? My gut is telling me you have some bad code in your getSuggestions that's returning an illegal value (i.e. null) .. it should always return an empty Iterable list or an error ..

The error messages appear in Terminal when I tap on flutter_typeahead textbox at the first time where the textbox is empty,  it just shows loading animation.  I tested again now and I see it dont call getSuggestions function because I have a condition  ` if (pattern.length >= 3) `  in `suggestionsCallback` which says the user need write 3 letters at minimum and then call getSuggestions . And

**Comment by sjmcdowall** [comment]
Show the code .. if that condition is met (length < 3) you still need to return an empty list back ..

**Comment by blue492** [comment]
> Show the code .. if that condition is met (length < 3) you still need to return an empty list back ..

   suggestionsCallback: (pattern) async {
                if (pattern.length >= 3) {
                  return await Search_Users.getSuggestions(pattern);
                }
              },

**Comment by sjmcdowall** [comment]
Yes correct ..

**Comment by MOhsain** [comment]
@sjmcdowall I was using this version flutter_typeahead: ^1.7.0. This version was working fine but now i ugrade this to 3.1.1. now it not showing any list.
if i pass empty list then it show not item found error. kindly help me
And here is my Code ->
 suggestionsCallback: (value) async {
                            if (value != null && value != '') {
                              if (value.length >= 1)
                                return await UserData.getSuggestions(value);
                              else
                                return null;
                            } else
                              return null;
                          },
