### ISSUE TITLE
Is there any way to turn off focus on the textfield when user clicks outside the suggestion list 

### ISSUE THREAD

**Issue by skylum1** [AbdulRahmanAlHamali/flutter_typeahead#302]
Currently one needs to press back button  to exit the input field .

**Comment by duongtricn2c** [comment]
I'm also having the same issue. Have you solved the issue?

**Comment by skylum1** [comment]
@duongtricn2c  , nope , I am not using it in my current project , will try to find a solution once I need  it in future . Hopefully the OC
(Original Coder ) will  add this functionality by then .

**Comment by mat100payette** [comment]
Do you guys @skylum1 and @duongtricn2c experience this issue in both Debug and Release mode ? It seems that this only happens in Release mode on my end.

**Comment by Batflash5** [comment]
Try wrapping the parent of the `TypeAheadFromField` with Gesture detector and in it's `onTap` add this:
```

            if (FocusScope.of(context).isFirstFocus) {
              FocusScope.of(context).requestFocus(new FocusNode());
              suggestionBoxController.close();
            }
```
