### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by JoseETeixeira** [AbdulRahmanAlHamali/flutter_typeahead#311]
Is there any supported way to internationalize the text field? When I try entering my name for instance (José), it doesn't get the special characters even though localizations are properly set up on the app 

`MaterialApp(
      supportedLocales: const [
        Locale('pt', 'BR'),
      ],
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        SfGlobalLocalizations.delegate
      ],
      locale: Locale('pt', 'BR'),
...
`

`  Container(
                      width: MediaQuery.of(context).size.width * 0.5,
                      height: MediaQuery.of(context).size.height * 0.025,
                      child: TypeAheadFormField(
                        textFieldConfiguration: TextFieldConfiguration(
                            controller: pagarAController),
                        direction: AxisDirection.up,
                        noItemsFoundBuilder: (context) {
                          return ListTile(
                            title: Text(
                              "Nenhuma sugestão encontrada",
                            ),
                          );
                        },
                        onSuggestionSelected: (suggestion) {
                          setState(() {
                            pagarAController.text = suggestion.toString();
                          });
                        },
                        itemBuilder: (context, suggestion) {
                          return ListTile(
                              title: Text(suggestion.toString(),
                                  style:
                                      TextStyle(fontWeight: FontWeight.w900)));
                        },
                        suggestionsCallback: (pattern) {
                          return BackendService(suggestionList: chequesPagarA)
                              .getSuggestions(pattern);
                        },
                      ))`

**Comment by sjmcdowall** [comment]
Gosh -- I don't think there is anything in the code that prevents Unicode characters from being used anywhere ... If you find a place let me know .. but no one else has complained about not being able to use any Unicode character .. sooo scratching my head on this .

**Comment by JoseETeixeira** [comment]
I managed a workaround by using
 ` inputFormatters: [
                              FilteringTextInputFormatter.allow(
                                  RegExp("[a-z A-Z á-ú Á-Ú 0-9]"))
                            ]`. 
However it still doesn't show characters such as 'é', only accepts them and inputs as e

**Comment by sjmcdowall** [comment]
I am stumped -- if you run it through a debugger maybe you can spot what is happening to it??

**Comment by sjmcdowall** [comment]
Can we close this?

**Comment by JoseETeixeira** [comment]
Sure. You might wanna add that input formatter as a default if none is passed though.
