### ISSUE TITLE
Implementation of onEditingComplete in TypeAheadFormField

### ISSUE THREAD

**Issue by alexobviously** [AbdulRahmanAlHamali/flutter_typeahead#313]
This package is very nice, and well designed, but it doesn't work for some use cases because the form field widget lacks some callbacks that TextFormField has, notably onChanged and onEditingComplete. onSaved is good to have but doesn't work for cases where you have a field that's standalone or not part of a form, and you need to know when it has been filled in, rather than having to hit a submit button.

**Comment by sjmcdowall** [comment]
I am not sure I understand the exact use cases.  The widget performs a call back any time the user enters another character and when they choose a selection.  What else is needed?

**Comment by alexobviously** [comment]
The use case I'm referring to is when you enter something that doesn't match any suggestions, and you want to call a callback with that string. (i.e. you press enter on web, or the 'finished' button on a mobile keyboard)

For example, you have a list of tags for some item (a store item, a podcast episode, etc), and use TypeAheadFormField inline to add a new tag. The list of suggestions is all of the tags that have been used for other items, but you also sometimes need to add a new tag that hasn't been used before.

**Comment by alexobviously** [comment]
Or maybe `TypeAheadField.onSubmitted`, to match this: https://api.flutter.dev/flutter/material/TextField/onSubmitted.html ?

**Comment by arne314** [comment]
@alexobviously have you found a workaround for the missing implementation?

**Comment by nullbtb** [comment]
Not sure if this has been added recently, but the requested functionality (onEditingComplete and onSubmitted) are already supported by providing a TextFieldConfiguration.

**Comment by logemi** [comment]
Hi, I am using this package for the first time and it is very useful. I'm going back to the explanation of alexobviously because I'm having the same problem on the web. It is impossible to initialize the onSubmitted property like this for example => onSubmitted: (pattern) {}. This generates an Invalid constant value error. It is therefore impossible to leave the field without selecting a suggestion.
