### ISSUE TITLE
How to continue typing after selected.

### ISSUE THREAD

**Issue by lequyhien98** [AbdulRahmanAlHamali/flutter_typeahead#315]
![image](https://user-images.githubusercontent.com/52742851/119224197-88e8aa00-bb27-11eb-9b30-3afceaee0e4c.png)

My code:
![image](https://user-images.githubusercontent.com/52742851/119224253-c77e6480-bb27-11eb-8b01-ae9567b97a4c.png)

**Comment by Marcosmaliki** [comment]
Also wondering how to achieve this. I guess we can manipulate the text controller?

**Comment by clragon** [comment]
yes, that is correct.
In my code I do something like this:

```dart
  controller.selection = TextSelection(
    baseOffset: controller.text.length,
    extentOffset: controller.text.length,
  );
```

inside of `onSuggestionSelected`
