### ISSUE TITLE
How Can I Add Separator Between Suggestions?

### ISSUE THREAD

**Issue by ayberkcal** [AbdulRahmanAlHamali/flutter_typeahead#316]
I would like to add separator between each suggestions but there is no option or builder for ListView separator. I can add separator in itemBuilder but I cannot determine item index, unfortunately. Can I miss this feature or any workaround for this? Thanks!

**Comment by kimphuc0000** [comment]
You have to custom function createSuggestionsWidget() to return a ListView.separated
