### ISSUE TITLE
Display suggestions above the typeahead field when less space is available below the field and the keypad

### ISSUE THREAD

**Issue by rsree1210** [AbdulRahmanAlHamali/flutter_typeahead#318]
Does the current package support showing the suggestions above the field when there is no much space available below the type ahead field and the keypad?

I am fetching 10 suggestions for the search text entered in the typeahead field, but I can see only 1 suggestion at a time on the UI, I have to scroll down to see the other suggestions and this is because there is no much space available between keypad and the typeahead field. So in such cases where there is less space available for the suggestions box, is it possible to show it above the type ahead field rather than showing it below the field.

Can anyone please help me with this.

**Comment by elgansayer** [comment]
Looking for this too. I want to show the suggestions above the field

Following :)

**Comment by octocat-1** [comment]
@rsree1210, @elgansayer, @mnarsely 
`autoFlipDirection: true`
