### ISSUE TITLE
Fetch more on scroll

### ISSUE THREAD

**Issue by SanjiKir** [AbdulRahmanAlHamali/flutter_typeahead#321]
Hey guys, thank you for this awesome library. Unfortunately, flutter Autocomplete is not good at all. 

I wanted to ask if it's possible to add an opportunity to 

1. Add ScrollController to suggestions box.
2. Add an event to trigger fetch more on scroll.

The use case is when I have a big list, even after the search narrows it down, I will never fetch all the items. So on scroll, we should continue fetching more.

I think it's even nice for basic functionality, when no value was entered, we show some default list sorted alphabetically and on scroll, we can show more to the user. 

Is it possible to add this by current contributors and if no, do you accept PRs?

**Comment by sjmcdowall** [comment]
This widget is really community controlled to a large part -- I don't have time to actually code anything these days (haven't coded Dart in over 2 years now) but will merge PRs etc. if there are some tests etc. Sounds like a great feature above though!

**Comment by SanjiKir** [comment]
@sjmcdowall Then I will take a look and try to add it :)

**Comment by royhanrahim** [comment]
Yes, it's true what @SanjiKir said, I'm really waiting for the next update for this package, thank you very much for making this package @sjmcdowall :)
