### ISSUE TITLE
The operator '[]' isn't defined for the type 'Object'. 

### ISSUE THREAD

**Issue by juzimmer** [AbdulRahmanAlHamali/flutter_typeahead#322]
After updating to null safety sdk version "**>=2.12.0 <3.0.0**" I'm getting **The operator '[]' isn't defined for the type 'Object'.** 

`onSuggestionSelected: (suggestion) {
          setState(() {
              addressController.text = suggestion["ADDRESS"];
           });
  },`

**Comment by adpmhel24** [comment]
same error

**Comment by juzimmer** [comment]
> same error

I found out that all you have to do is create a local variable something like `var myVariable = suggestion as Map;` then all should work fine.

**Comment by AamilSilawat26** [comment]
` itemBuilder: (context,dynamic suggestion) {
                          return ListTile(
                            title: Text(suggestion["Name"]),
                          );
                        },`
                        
   Define with **dynamic** keyword, It is working for me.

**Comment by prathamesh-mali** [comment]
> 

Thanks for solution this is working for me as well
