### ISSUE TITLE
Duplicated typedefs

### ISSUE THREAD

**Issue by vasilich6107** [AbdulRahmanAlHamali/flutter_typeahead#324]
A bunch of typedefs are defined in both files.

error: The name 'SuggestionsCallback' is defined in the libraries 'package:flutter_typeahead/flutter_typeahead.dart' and 'package:flutter_typeahead/cupertino_flutter_typeahead.dart'. (ambiguous_export at [reactive_flutter_typeahead] lib/reactive_flutter_typeahead.dart:4)

![image](https://user-images.githubusercontent.com/6721286/123848512-7b8dbf00-d920-11eb-92fa-2fe4a5fe7db8.png)

**Comment by sjmcdowall** [comment]
That's because they ARE defined in both files .. they need to be, right?  No idea on how to resolve this but there should be a standard way because many widgets have cupertino and normal versions??

**Comment by wbusey0** [comment]
I think you can define them once in a separate file and import / export them in both `flutter_typeahead.dart` and `cupertino_flutter_typeahead.dart`

**Comment by vasilich6107** [comment]
Hi @sjmcdowall 
I'm writing a wrapper `reactive_flutter_typeahead` to use with `reactive_forms` package.

I need to reexport `flutter_typeahead` to give users ability to import some typedefs like `CupertinoTextFieldConfiguration`

In current dir structure it causes errors.

![image](https://user-images.githubusercontent.com/6721286/125127154-ca97d900-e104-11eb-8a16-c27015608102.png)

**Comment by vasilich6107** [comment]
@sjmcdowall @AbdulRahmanAlHamali 

My PR reorganises dir structure a little to match preferred dir structure for packages.
Here is some examples

https://github.com/rrousselGit/freezed/tree/master/packages/freezed/lib
https://github.com/google/json_serializable.dart/tree/master/json_serializable/lib

And many others.
I would appreciate if you'll merge my PR.
I fixed `example` and added `CHANGELOG` and bumped version.

**Comment by sjmcdowall** [comment]
Great!  Thanks!

**Comment by vasilich6107** [comment]
@sjmcdowall one moment. I'll fix conflicts
