### ISSUE TITLE
DropDown Hidden by Keyboard

### ISSUE THREAD

**Issue by AnuPrajapati** [AbdulRahmanAlHamali/flutter_typeahead#345]
When there is multiple feild--TextField and the dropdown is at the bottom of the page, Then there we found the issue that, the keyboard just hide all the items listed in dropdown. As the user have to scroll up which look inconvenient. 
![image](https://user-images.githubusercontent.com/54139344/135811551-094ceaee-c291-4c59-9263-0fd847176d73.png)

**Comment by mariusschroeter** [comment]
My suggestion to this is using suggestionsBoxVerticalOffset with a negative value to put the suggestions on top of your input box.

**Comment by mjablecnik** [comment]
This problem can be solved by: `direction: AxisDirection.up`

Which change direction of showed suggestions:

![image](https://user-images.githubusercontent.com/2686906/141533161-ea6a9214-6bf3-40c0-b346-af84072fd2e4.png)

**Comment by ktravelet** [comment]
I came here with the exact same problem.  This would ideally be solved by being compatible with [showSearch](https://api.flutter.dev/flutter/material/showSearch.html)

[Example of using showSearch](https://medium.com/comerge/location-search-autocomplete-in-flutter-84f155d44721)

**Comment by vmkgalvatron** [comment]
> My suggestion to this is using suggestionsBoxVerticalOffset with a negative value to put the suggestions on top of your input box.

Can you explain a bit more?

**Comment by TheCarpetMerchant** [comment]
It would be great to have `direction` be handled by the widget itself if not provided. It would use `AxisDirection.up` only if there's more space up then there is down (taking the keyboard into account).
