### ISSUE TITLE
SuggestionsCallback starts by itself when TypeAheadField is focused.

### ISSUE THREAD

**Issue by kokikudo** [AbdulRahmanAlHamali/flutter_typeahead#348]
SuggestionsCallback call by itself when TypeAheadField is focused.

```
TypeAheadField(
              textFieldConfiguration: TextFieldConfiguration(
                  style: DefaultTextStyle.of(context).style.copyWith(
                      fontStyle: FontStyle.italic
                  ),
                  decoration: InputDecoration(
                      border: OutlineInputBorder()
                  ),
              ),
              suggestionsCallback: (pattern)  {
                print(pattern);
                return [Text('suggest')];
              },
              itemBuilder: (context, suggestion) {
                return ListTile(
                  leading: Icon(Icons.shopping_cart),
                  title: suggestion as Text,
                );
              }, onSuggestionSelected: (Text suggestion) {},
            )
```
![画面収録-2021-10-24-9 39 05](https://user-images.githubusercontent.com/51766366/138575654-c94535d8-1ae5-4b3c-85ff-5903c3b7647f.gif)

**Comment by gustav3d** [comment]
Any workaround ?.

**Comment by clragon** [comment]
I guess if we ever get #350, it could fix that, by setting the minimum to 1.

**Comment by liemeon** [comment]
transitionBuilder: (context, suggestionsBox, animationController) {
            return Visibility(
                visible: controller.searchController.value.text.length == 0
                    ? false
                    : true,
                child: suggestionsBox);
          },

**Comment by mark8044** [comment]
> transitionBuilder: (context, suggestionsBox, animationController) {
>             return Visibility(
>                 visible: controller.searchController.value.text.length == 0
>                     ? false
>                     : true,
>                 child: suggestionsBox);
>           },

This works!
