### ISSUE TITLE
Minimum number of characters before suggestionsCallback is called

### ISSUE THREAD

**Issue by alfredjingle** [AbdulRahmanAlHamali/flutter_typeahead#350]
Re-opening discussion on the feature described in #83 

As stated in the latest comments on that issue, the solution of returning null from the suggestionsCallback no longer works due to the null-safety update, and returning an empty array causes the "No items found!" box to be displayed when suggestions are loaded for the first time.

Suggestion is to add an explicit option to the typeahead fields which allows specifying the minimum number of characters which have to be entered before the suggestionsCallback is called.

This change should also solve the issue described in #348.

I have opened #349 with the proposed changes.

**Comment by jeshpren** [comment]
I spent way too much time looking for an answer to this problem, until I found out that github repositories have the "Issues" tab.

@alfredjingle's suggestion would be a wonderful addition to this awesome widget.

**Comment by devmgs** [comment]
Now after null safety we cannot return null from callback so if we return empty list then noItemsFoundBuilder is called. Any way to have both the features?
