### ISSUE TITLE
cannot disable field

### ISSUE THREAD

**Issue by clragon** [AbdulRahmanAlHamali/flutter_typeahead#355]
The normal Flutter `TextField` has a parameter called `enabled`.
That parameter makes the textfield ignore interactions.
The parameter is not available in `TypeAheadField`.

I would appreciate if it was possible to pass this parameter through.
I assume the suggestions would need to hide if the field is disabled.

**Comment by joaobaronisilva** [comment]
Hi, clragon!

Using `textFieldConfiguration` propertie in `TypeAheadField` component, you are able to set the enabled propertie that you want.

**Comment by SittiphanSittisak** [comment]
Hi, can we only disable user typing?
