### ISSUE TITLE
onSuggestionSelected is never hit

### ISSUE THREAD

**Issue by toekneema** [AbdulRahmanAlHamali/flutter_typeahead#356]
I think this method is never hit because the device is not even registering that I'm touching one of the suggestions for some reason. Any thoughts on how to solve this issue? I've attached a video below

https://user-images.githubusercontent.com/42778379/142565950-9c5928bf-c5ed-4cf6-a41a-78e070e63844.MP4

.

**Comment by hortegag91** [comment]
any solution?

**Comment by hortegag91** [comment]
I was on main channel, change it to stable works for me

**Comment by BenjiFarquhar** [comment]
Mine only hits the first time then doesn't hit again. Anyone else have this?

Have tried version 3.2.7 and 4.0.0 with same result

**Comment by BenjiFarquhar** [comment]
Update -  In my specific case, I had recently added a `FocusNode` to the `TextFieldConfiguration` which caused the bad behaviour. Deleting it fixed the issue.

**Comment by blitzdose** [comment]
Sorry for responding to a closed Issue but I found the reason why I had this behavior. It was my Bitwarden App (a password manager) that uses an Accessibility Service to find username and password fields. I turned that off in my accessibility system settings and immediately everything works as it was supposed to. Seems like an issue with accessibility services reading the displayed text. That's why only a few people have this problem.

**Comment by sjmcdowall** [comment]
@blitzdose -- Thank you for sharing this tidbit of information.  Good to know!

**Comment by zoltanbalog** [comment]
I have the same problem too in Android, onSuggestionSelected is never called if the user have an application which use accessibility options, for example: Bitwarden, Sophos, etc. So this is not a unique problem, because it doesn't affect just one application, do you have any idea or solution?

**Comment by GustavoFigueira** [comment]
> I have the same problem too in Android, onSuggestionSelected is never called if the user have an application which use accessibility options, for example: Bitwarden, Sophos, etc. So this is not a unique problem, because it doesn't affect just one application, do you have any idea or solution?

[#https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/463](https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/463#issuecomment-1482018642)
