### ISSUE TITLE
Add documentation to README about the new `hide` properties

### ISSUE THREAD

**Issue by AbdulRahmanAlHamali** [AbdulRahmanAlHamali/flutter_typeahead#36]

**Comment by KaYBlitZ** [comment]
Added the documentation in version 1.0.2. Also fixed #37 in 1.0.2. I pushed to dart already. Hope you don't mind. I didn't think the changes were too crazy to merit reviews.

**Comment by AbdulRahmanAlHamali** [comment]
Hahaha no it's ok. Great job man!
