### ISSUE TITLE
BoxConstraints has a NaN value in maxHeight.

### ISSUE THREAD

**Issue by tr0jan666** [AbdulRahmanAlHamali/flutter_typeahead#362]
I have a **PageView** that has 2 child. They are 2 **Statefulls** which has **State** with **AutomaticKeepAliveClientMixin**. Each child has a **TypeAheadField**.

step:

1. focus in TypeAheadField
2. call _pageController.jumpToPage(index);

then i got err
![image](https://user-images.githubusercontent.com/38048839/146430054-2a09731d-e5cd-4f32-9fb0-9bf3955d260a.png)

**Comment by ftore** [comment]
any update on this?
