### ISSUE TITLE
noItemsFoundBuilder not getting call if type ahead field is empty and return suggestions are also empty

### ISSUE THREAD

**Issue by iamrohitsuthar** [AbdulRahmanAlHamali/flutter_typeahead#370]
When TypeAheadField is focused initially and if we do not type anything and if ```SuggestionsCallback``` returns non-empty suggestions then suggestions list is shown. But if ```SuggestionsCallback``` returns empty suggestions then ```noItemsFoundBuilder``` should gets invoked but currently it not getting invoked.

If we type something in field and if suggestions are empty then in this case only ```noItemsFoundBuilder``` is invoked.

**I have attached below outputs for better understanding.**

**When field is focused and we do not have type anything: non-empty suggestions in SuggestionsCallback**
<img src="https://user-images.githubusercontent.com/37514288/149722507-9e635f88-a913-4ddb-be60-2c1bd5c8b909.png" width="600" height="400" />

**When field is focused and we do not have type anything: empty suggestions in SuggestionsCallback**
![image](https://user-images.githubusercontent.com/37514288/149722632-77d51220-ecf1-4ac1-a813-ad11e7683da2.png)

**We have type something in field**
![image](https://user-images.githubusercontent.com/37514288/149722670-ea355e18-9996-4e85-9e51-1098d4388bb3.png)

**Comment by prathmesh-jadhav** [comment]
I am facing exact same issue.

**Comment by sjmcdowall** [comment]
If this is still the case in Flutter 3 / TypeAhead 4.x -- then if someone makes a PR with a test case I will merge.
