### ISSUE TITLE
Suggestions are returning by google API but this widget is returning empty List

### ISSUE THREAD

**Issue by arslankaleem7229** [AbdulRahmanAlHamali/flutter_typeahead#374]
I am using google APIs with this package but I have seen that google is returning the correct address and everything but this widget is keep returning empty list as there is no data fetched... Also it is detecting the exact keywords and its case sensitive which is making difficult to search

**Comment by faranmemon** [comment]
You have to map the response returned form google api correctly like this.

```
itemBuilder: (context, yourCustomLocationModel) {
     return ListTile(title: Text(yourCustomLocationModel.locationText));
}
```

User suggestionsCallback to fetch the places from Google API and then user your model to update the list using itemBuilder. 

If still not clear then share the code.
