### ISSUE TITLE
Very Useful, Very Easy To Implement Enhancements

### ISSUE THREAD

**Issue by bryanCancelWT** [AbdulRahmanAlHamali/flutter_typeahead#378]
This plugin is great! But for my purposes 
I need *autofillHints* because they provide yet another way for users to get help to fill a field
I also noticed other parameters that are not in TextFieldConfiguration
so they are not passed to the underlying TextField( widget

I listed them below, I suspect most will be a super easy lift (simply parameter passing and updating of TextFieldConfiguration code)

*Easier Lifts*
autofillHints
restorationId

toolbarOptions
showCursor
obscuringCharacter
smartDashesType
smartQuotesType
maxLengthEnforcement
scrollPhysics
selectionControls
scrollController
enableIMEPersonalizedLearning

*Harder Lifts* (might require other code to change accordingly)
strutStyle 
buildCounter (maybe shift down suggestions so this can show)
enableSuggestions 
expands (maybe shift down suggestions so this can show)
cursorHeight 

I'd love to see at least autofill hints in the next update, but I figure I'd at least suggest it

**Comment by clragon** [comment]
as of right now, I do not think that the repo maintainers will implement code themselves anymore, I assume they do not have time for it. But if you were to provide a PR with those changes, its very likely they will accept it and merge your code.

**Comment by sjmcdowall** [comment]
@clragon -- you are correct.  :)
