### ISSUE TITLE
build issue - master branch

### ISSUE THREAD

**Issue by selvam920** [AbdulRahmanAlHamali/flutter_typeahead#381]
[   +1 ms]   [   +9 ms]
/C:/Users/sksso/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_typeahead-3.2.4/lib/src/flutter_type
ahead.dart(936,9): error GC6690633: No named parameter with the name 'maxLengthEnforced'.
[D:\_sksmarket\sksmarket\build\windows\flutter\flutter_assemble.vcxproj]
[   +2 ms]   [   +4 ms]
/C:/Users/sksso/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_typeahead-3.2.4/lib/src/cupertino_fl
utter_typeahead.dart(746,9): error GC6690633: No named parameter with the name 'maxLengthEnforced'.

**Comment by Musharaf13** [comment]
I'm having the same issue. My production project failed.


../.pub-cache/hosted/pub.dartlang.org/flutter_typeahead-3.2.4/lib/src/flutter_typeahead.dart:936:9:
--
08:49:56.250 | Error: No named parameter with the name 'maxLengthEnforced'.
08:49:56.250 | maxLengthEnforced: widget.textFieldConfiguration.maxLengthEnforced,
08:49:56.250 | ^^^^^^^^^^^^^^^^^

**Comment by 0xC316c** [comment]
> You can clone this repo and use like this in pubspec file. It solved my problem. "All thanks goes to selvem920" https://github.com/selvam920/flutter_typeahead <img alt="image" width="499" src="https://user-images.githubusercontent.com/48816448/158463950-447a9d0d-bb10-4701-ba95-32c7a1cfb27a.png">

I did the same by deleting all references of `maxLengthEnforced` to fix build errors in my project.

**Here its:** https://github.com/0xC316c/flutter_typeahead

Anyone from the team mind fixing that without us hosting this repository in our own GitHub accounts?

**Comment by davidmartos96** [comment]
@0xC316c you can update the package to version 4.0.0

**Comment by 0xC316c** [comment]
> @0xC316c you can update the package to version 4.0.0

I have a project which doesn't have Null safety enabled and I am not planning to migrate the project to to use Null safety.

**Comment by sjmcdowall** [comment]
There is no plan to maintain a non-null safety version of this package.

**Comment by 0xC316c** [comment]
I understand, thank you :)
