### ISSUE TITLE
Error on Samsung devices

### ISSUE THREAD

**Issue by gincsait** [AbdulRahmanAlHamali/flutter_typeahead#386]
On Samsung devices, the following flutter issue affects this library:
https://github.com/flutter/flutter/issues/98505
While this issue persist, can you replace TextField with TextFormField?

**Comment by KuldeepAIP** [comment]
@gincsait 
I am facing the same issue. Let me know if you found any solution.

**Comment by sjmcdowall** [comment]
Can you use this work around I read 

Hey, I don't have a Samsung device to test it, so I would need someone to test an idea.
I noticed that the autofillHints property has not the same default value in TextFormField and TextField. In TextFormField it's null and it's set to an empty list in TextField.
Can someone test to use a TextField and set explicitly autofillHints to null to test if there is still an issue with SmartSuggestions ?
 @letsar

Contributor
[letsar](https://github.com/letsar) commented [5 days ago](https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/386#issuecomment-1151033318)
Setting autofillHints to null is working great on our side. It seems to be a wanted decision (see https://github.com/flutter/flutter/pull/86312), so I won't make a PR to change the default value. We should tell Samsung to fix this issue on their side.
Does anyone knows how to contact the team responsible for this app?

I.e. can you someone (I don't remember) pass in a null for autofillHints and see if it fixes it?

**Comment by gincsait** [comment]
As i wrote in my original post, i think using TextFormField instead of TextField in the TypeAheadFormField implementation would solve the problem.
Should be thought through carefully, as the TextField does not appear in the TypeAheadFormField, but in the TypeAhedField, where it seems logical.

This has helped in other projects: https://github.com/xaynetwork/xayn_design/pull/90#issue-1175215063. If no one else does it, i might do a pull request later (in a few months), but i don't have the capacity at the moment, anyone else?

**Comment by sjmcdowall** [comment]
Closed due to lack of activity
