### ISSUE TITLE
Flutter Keyboard Visibility issues

### ISSUE THREAD

**Issue by onegeekypal** [AbdulRahmanAlHamali/flutter_typeahead#389]
I'm working on project with flutter elements inside native iOS apps. Plugin called "Flutter Keyboard Visibility" causes build issues of that project for iOS simulator on Apple Silicon devices. I cannot find a way to exclude arm64 architecture in this native project for that package. 

Using alternative to flutter keyboard visibility or native way to listen to keyboard events would fix that problem.

**Comment by sjmcdowall** [comment]
Closed to lack of activity (and lots of patches since)
