### ISSUE TITLE
[Feature request] Remove selected entry with keepSuggestionsOnSuggestionSelected set to true

### ISSUE THREAD

**Issue by jcblancomartinez** [AbdulRahmanAlHamali/flutter_typeahead#390]
Hi,

I would like to be able to remove the selected entry from the list of suggestions when setting keepSuggestionsOnSuggestionSelected to true.

Currently it is not possible.

As a workaround, I tried adding `_suggestionsBoxController.open();` to onSuggestionSelected with keepSuggestionsOnSuggestionSelected set to false but _focusNodeListener doesn't get triggered and therefore there is no way to call open on _suggestionsBox.

I prefer an approach where keepSuggestionsOnSuggestionSelected is set to true to avoid unnecessary calls to suggestionsCallback.

Thanks.

Regards.

**Comment by jcblancomartinez** [comment]
@AbdulRahmanAlHamali Could you please take a look at this?

Thank you very much.

**Comment by tushardubey121** [comment]
Please update the plugin with the following code 

`
this._focusNodeListener = () {
      if (_effectiveFocusNode!.hasFocus) {
        this._suggestionsBox!.open();
      } else {
          if (widget.hideSuggestionsOnKeyboardHide){
            this._suggestionsBox!.close();
          }
      }
    };
`  

this solves the problem 🥂

**Comment by jcblancomartinez** [comment]
Hi @tushardubey121 @AbdulRahmanAlHamali ,

I see above changes have been pushed, thanks for that, however, those don't make any difference when hideSuggestionsOnKeyboardHide is set to true.

Furthermore, we are still missing the functionality to delete the entry from the list of available options without requiring an additional call to suggestionsCallback (with keepSuggestionsOnSuggestionSelected set to true).

Thanks.

**Comment by tushardubey121** [comment]
> Hi @tushardubey121 @AbdulRahmanAlHamali ,
> 
> I see above changes have been pushed, thanks for that, however, those don't make any difference when hideSuggestionsOnKeyboardHide is set to true.
> 
> Furthermore, we are still missing the functionality to delete the entry from the list of available options without requiring an additional call to suggestionsCallback (with keepSuggestionsOnSuggestionSelected set to true).
> 
> Thanks.

Okay I will check more for this if you find any solution let me know. Or you can do one thing which I was done first hide they keyboard using `SystemChannels.textInput.invokeMethod('TextInput.hide');` then wait for 1 second then fetch data from the API that work for me. 

Untill not resolving this use what I explain maybe that resolve your problem for now

**Comment by jcblancomartinez** [comment]
Hi @tushardubey121,

I've indeed tried to look for a elegant workaround but unfocusing and requesting focus again to get the list of options refreshed, however, the following [keyboard visibility listener](https://github.com/AbdulRahmanAlHamali/flutter_typeahead/blob/master/lib/src/flutter_typeahead.dart#L798-L800) gets executed always after all the calls to unfocus/focus and therefore options get hidden:

```
    this._keyboardVisibilitySubscription =
        _keyboardVisibility?.listen((bool isVisible) {
      if (widget.hideSuggestionsOnKeyboardHide && !isVisible) {
        _effectiveFocusNode!.unfocus();
      }
    });
```
Adding additional wait time might work but it is not a robust solution as it is not deterministic.

I can think of two different approaches to this:
* Plugin could accept a new boolean constructor argument to indicate if selected item would be removed when selected.
* Plugin could accept a new function to filter available suggestions. That function would be called when refreshing the options and after selecting an item. The function would accept Iterable<T> as input (fetched from suggestionsCallback) and would return Iterable<T>. The list of selected items could be kept and used to remove them from the list.

What do you think?

**Comment by clragon** [comment]
As of version 5.x, its now possible to directly set the suggestions through the controller.
