### ISSUE TITLE
Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null

### ISSUE THREAD

**Issue by plabon** [AbdulRahmanAlHamali/flutter_typeahead#392]
After **flutter upgrade to 3.0.0** the following waring pops up:

`flutter_typeahead-3.2.5/lib/src/cupertino_flutter_typeahead.dart`
`Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.`

We don't need null aware operations i guess.

**Comment by bhattaraigirija** [comment]
@plabon had you fix this problem ?  if yes then how ?

**Comment by sjmcdowall** [comment]
This should be fixed - closing.
