### ISSUE TITLE
Suggestion box height is incorrect when TypeAhead is in an scrollable

### ISSUE THREAD

**Issue by davidmartos96** [AbdulRahmanAlHamali/flutter_typeahead#40]
maxHeight calculation in the method `resize()` in the source code is not correct. Specifically the variable `textBoxAbsY` which is calculated as `double textBoxAbsY = box.localToGlobal(Offset.zero).dy;`

Creating a TypeAhead at the top of the scrollable works fine but once you scroll an take the focus of the textField, then the variable `textBoxAbsY` is not being calculated properly.

Maybe this can be fixed using the viewport and/or the ScrollPosition. I would PR, but I have never used these classes:
```
RenderAbstractViewport viewport = RenderAbstractViewport.of(box); // is not null when using a scroll
double offsetToRevealTop = viewport.getOffsetToReveal(box, 0.0).offset;

ScrollPosition scrollPosition = Scrollable.of(context).position;
double pixels = scrollPosition.pixels;
```

**Comment by KaYBlitZ** [comment]
Would you like to take a stab at it? You seem to know the solution already.
You can fork the current revision and make a PR. I won't be able to look at
this until this weekend.

**Comment by davidmartos96** [comment]
I am closing because inspecting it more close, it seems like an issue on my end.
I did PR a scroll related fix though.
