### ISSUE TITLE
Build error on Flutter v2.10.5

### ISSUE THREAD

**Issue by mehdico** [AbdulRahmanAlHamali/flutter_typeahead#400]
Error:

`../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_typeahead-4.0.0/lib/src/flutter_typeahead.dart:754:29: Error: Method 'removeObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../development/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.removeObserver(this);
                            ^^^^^^^^^^^^^^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_typeahead-4.0.0/lib/src/flutter_typeahead.dart:767:29: Error: Method 'addObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../development/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.addObserver(this);
                            ^^^^^^^^^^^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_typeahead-4.0.0/lib/src/flutter_typeahead.dart:803:29: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../development/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.addPostFrameCallback((duration) {
                            ^^^^^^^^^^^^^^^^^^^^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_typeahead-4.0.0/lib/src/cupertino_flutter_typeahead.dart:558:29: Error: Method 'removeObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../development/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.removeObserver(this);
                            ^^^^^^^^^^^^^^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_typeahead-4.0.0/lib/src/cupertino_flutter_typeahead.dart:571:29: Error: Method 'addObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../development/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.addObserver(this);
                            ^^^^^^^^^^^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_typeahead-4.0.0/lib/src/cupertino_flutter_typeahead.dart:605:29: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../development/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.addPostFrameCallback((duration) {
                            ^^^^^^^^^^^^^^^^^^^^`

**Comment by sjmcdowall** [comment]
Version 4.0 is for Flutter 3.x and above.  Use the latest of the 3.X versions ...
