### ISSUE TITLE
unable to use up and arrow key in keyboard for selecting suggestions

### ISSUE THREAD

**Issue by yamamz** [AbdulRahmanAlHamali/flutter_typeahead#402]

**Comment by sjmcdowall** [comment]
Well at a minimum much more information like steps to reproduce etc.  But also -- are you on the very latest Flutter/Dart 3.X and 4.x of this library?  Seems like this would be a core Flutter problem to me <shrug>

**Comment by yamamz** [comment]
hi AutoComplete widget works arrow down and up and enter selected it is not on flutter itself can you take a look on this widget https://api.flutter.dev/flutter/material/Autocomplete-class.html#material.Autocomplete.1

**Comment by mi1971** [comment]
Hey Guys, I agree - absolutely this should be handled by the widget, and should be imperative that the suggestion can be chosen via the keyboard.  I've done it on one of mine...its quite easy. You just need to keep track of a _suggestionIndex that starts at -1, and then instantiate the focusnode for the textfield like this:
`FocusNode(
      onKey: (FocusNode node, RawKeyEvent event) {
        //discard the keyup event, and use the keydown only since this fires twice for every keypress
        if (event.runtimeType.toString() == 'RawKeyUpEvent')
          return KeyEventResult.ignored;

        //Up and down arrow keys...
        if (event.logicalKey == LogicalKeyboardKey.arrowDown) {
          if (_suggestionIndex.value < _suggestions.length - 1) {
            _suggestionIndex.value++;
          }
          return KeyEventResult.handled;
        }
        if (event.logicalKey == LogicalKeyboardKey.arrowUp) {
          if (_suggestionIndex.value > 0) {
            _suggestionIndex.value--;
          }
          return KeyEventResult.handled;
        }

        //Tab Key...
        if (event.logicalKey == LogicalKeyboardKey.tab &&
            _suggestionIndex > -1) {
          if (_textEditingController.text.length > 0) {
            _submitSuggestion(_suggestions[_suggestionIndex.value]);
            return KeyEventResult.handled;
          }
        }`

...and then when you output the suggestions, you hilight the one that matches the current _suggestionIndex

**Comment by sjmcdowall** [comment]
If someone wants to submit a PR with tests, etc. I'll happily merge ..
