### ISSUE TITLE
Recent merge breaks functionality

### ISSUE THREAD

**Issue by bagintz** [AbdulRahmanAlHamali/flutter_typeahead#403]
https://github.com/AbdulRahmanAlHamali/flutter_typeahead/pull/395

This disables the programatic use of SuggestionBoxController .close() method.  If you set hideSuggestionsOnKeyboardHide to false, it will never close.  A suggested fix would be to add some sort of way to allow the SuggestionBoxController .close() method to bypass the hideSuggestionsOnKeyboardHide if called programatically.

Our use case is that some of our users need to close the keyboard to view the suggestions and we gave a programatic way to close the suggestions after they were done.

**Comment by Noob-2-pro** [comment]
I am facing the same issue
