### ISSUE TITLE
Null Safety Error

### ISSUE THREAD

**Issue by nathanielajayi7** [AbdulRahmanAlHamali/flutter_typeahead#407]
Apparently, this package isn't fully null safety compliant 

/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_typeahead-4.0.0/lib/src/flutter_typeahead.dart:803:29: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
Try calling using ?. instead.
    WidgetsBinding.instance.addPostFrameCallback((duration) {

**Comment by pratamarama** [comment]
same here..

**Comment by Tecmesh** [comment]
Use the previous version[3.2.7](https://pub.dev/packages/flutter_typeahead/versions/3.2.7). It worked for me.

**Comment by sjmcdowall** [comment]
Yes the major version change is for the new flutter and the older version is for the old flutter -- and type safety .. The WAY WAY older version is for non-type safety and will not longer be maintained .. 

So make your app null-safe and Flutter 3 compatible and use Typeahead V4 .. that's the only version going forward that will be maintained ..
