### ISSUE TITLE
Changing the pop up from bottom to the top

### ISSUE THREAD

**Issue by gbbest15** [AbdulRahmanAlHamali/flutter_typeahead#410]
i am using this package to suggestion but is coming from the bottom. 

i wan to be coming from the top

example here in the [Image](https://drive.google.com/file/d/1o3e8LVLkaEIZH7yYO98DUBXg2_RDye16/view?usp=sharing)

**Comment by vinodh013** [comment]
Hey, have you found any solution? I am also trying to achieve the same thing in my project.

**Comment by gbbest15** [comment]
@vinodh013  i did not, i decided to go for another method instead of waiting.. i did not have time to clone and make changes to repo, because there alot of project i am working on... i will check if i can contribute to the package later
