### ISSUE TITLE
Issues with `(`, `)`, `|`, `\` chars in search query

### ISSUE THREAD

**Issue by powerworr** [AbdulRahmanAlHamali/flutter_typeahead#411]
Hello,
I've seen that when the search query has one of `(`, `)`, `|`, `\` the `suggestionsCallback` and `itemBuilder` throw errors. I'm catching for them with a regex, but would be nice to be solved by the library itself.

**Comment by Mohdx** [comment]
You can make pull request of your solution and it'll be solved in the library itself
