### ISSUE TITLE
TypeAhead doesn't show any suggestions. Even though it finds elements by query, it doesn't build any suggestions list

### ISSUE THREAD

**Issue by Lazizbek97** [AbdulRahmanAlHamali/flutter_typeahead#414]
`TypeAheadField(
**suggestionsCallback**: (searchText) =>
                                                      controller.getAllCustomers(
                                                          searchText), 
**itemBuilder**:  (context, index) =>
                                                      SuggestedCustomerCard(
                                                    customer: controller
                                                        .suggestionCustomers[index],
                                                    query: controller
                                                        .customerSearchController
                                                        .text,
                                                  ), 
**onSuggestionSelected**:  (index) =>
                                                      controller.addCustomer(controller
                                                              .suggestionCustomers[
                                                          index]),
 
 **hideOnLoading**: true,
                                                          **errorBuilder**: (context, index)=> Text("Errorr"),
                                                          **noItemsFoundBuilder**: (context)=> Text("No item found"),
                                                          ),`

**Comment by maxy-hi** [comment]
Does the item builder work when just showing listtile?

**Comment by Lazizbek97** [comment]
Yes

**Comment by maxy-hi** [comment]
Would it be possible to have a look inside the `SuggestedCustomerCard` to see what that is building. I'm wondering if the builder just doesn't support cards.

**Comment by sjmcdowall** [comment]
Closed due to lack of followup
