### ISSUE TITLE
pressing down down-arrow on keyboard the suggestion items not focused

### ISSUE THREAD

**Issue by ara-kurd-dev** [AbdulRahmanAlHamali/flutter_typeahead#415]
I'm using your library for my application which runs on Windows and macOS, so I want it to make more user-friendly, that just the user pressed down-arrow or up-arrow on the keyboard the suggestion item is selected, and on pressing enter on the desired one be selected like its tapped by hand on smartphones.

**Comment by techttiru** [comment]
@ara-kurd-dev Hi, i am also looking for the same capability. were you be able to find any solution for this?

**Comment by jobypthomas** [comment]
@ara-kurd-dev  @techttiru How did you accomplish this? I am looking for this feature so that users can use arrow up and down to navigate and select the list

**Comment by ara-kurd-dev** [comment]
until now I have not found the solution either. Honestly, I didn't test the last update of the package maybe they resolved it. and @sjmcdowall  marked it as completed maybe they added the feature.
