### ISSUE TITLE
Outdated contributing instructions

### ISSUE THREAD

**Issue by alexanderFell** [AbdulRahmanAlHamali/flutter_typeahead#421]
The contribution instructions are outdated. There, it says that contributors should create a feature branch from the develop branch. However, the last rebase from the master branch to the develop branch is around 2 years ago and hence the develop branch is outdated. In fact, it does not compile anymore without major changes. Contributors following the instructions will have a hard time merging their work.

As a solution, either rebase the develop branch to the current master branch and enforce the rule or replace develop branch by master branch.

**Comment by sjmcdowall** [comment]
Updated.
