### ISSUE TITLE
How can we enable keyboard arrow up and down keys to scroll down or up in textfield suggestion list in flutter web?

### ISSUE THREAD

**Issue by techttiru** [AbdulRahmanAlHamali/flutter_typeahead#423]
how can we enable keyboard arrow down and up keys for scrolling the textfield suggestion scrolling in flutter web? I am using TypeAheadFormField widget to show suggestion when user type character in text field and scrolling works when we use mouse. but i want to scroll this suggestion list using keyboard arrow keys. how can we do this? any input would be really appreciated.

**Comment by flutter-painter** [comment]
duplicate of https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/298

**Comment by sarbogast** [comment]
That would be an awesome feature indeed

**Comment by selvam920** [comment]
any update on this?

**Comment by jobypthomas** [comment]
any update?
