### ISSUE TITLE
suggestionCallback always called on focus?

### ISSUE THREAD

**Issue by ethel39** [AbdulRahmanAlHamali/flutter_typeahead#425]
Hello i tried this package but everytime focus to TypeAheadFormField it always call suggestionsCallback even if it is empty or have value that i didn't change yet, is this expected behavior ?

i tried to run example and it is still happening

i already tried to set getImmediateSuggestions to false and it is still run callback

i used Flutter (Channel stable, 3.3.1, on Microsoft Windows [Version 10.0.19044.1889], locale en-VU)

Thank you

**Comment by DCrow** [comment]
Hey!

Have you tried changing `minCharsForSuggestions`? 
It's 0 by default, so `suggestionsCallback` always gets fired.

**Comment by ethel39** [comment]
ah i see, thank you
it works as what i wanted now
