### ISSUE TITLE
Key selection issue in release mode

### ISSUE THREAD

**Issue by Pierre-Monier** [AbdulRahmanAlHamali/flutter_typeahead#426]
There is buggy behavior on web and desktop with the key selection feature. This only happen in release mode. 

I will check that out, just wanted to report this issue

**Comment by sjmcdowall** [comment]
Sounds good -- thanks!

**Comment by Pierre-Monier** [comment]
I fixed most of it. Just one last thing, when a suggestion item is focused, clicking back to the TextField does give TextField focus back, but clicking outside FlutterTypeahead doesn't make the suggestion item lose his focus. I'm struggling with that but when it's done I'm making a PR.

Note that I've tried this feature on macos and windows today, I discovered that the behavior is not the same as the web platform (which was the platform I test this feature on). I will check that out

**Comment by sjmcdowall** [comment]
Sounds good !  I'll be o the lookout for the PR .. And BTW -- I LOVE Lyon France -- one of my favorite food destination cities in the world :)

**Comment by Pierre-Monier** [comment]
Man, you have great taste. I'm very glade to hear that :)

**Comment by sjmcdowall** [comment]
Closing w/ PR Merged
