### ISSUE TITLE
Error: Bad state no element

### ISSUE THREAD

**Issue by Lazizbek97** [AbdulRahmanAlHamali/flutter_typeahead#427]
I'm using typeahead on the desktop app. But sometimes I face such problems (Bad State no element). After that, I cannot use typeahead until I restart the app.
How can I fix or protect users from reproducing such cases?
![typeahead error](https://user-images.githubusercontent.com/91660256/189965542-9da5ec1d-3a62-4d39-b9d5-6bbd81fe28f0.png)

**Comment by sjmcdowall** [comment]
Will need a lot more detail including sample code -- stack trace if possible -- steps to reproduce -- also the desktop Dart/Flutter stuff is still very very early...  so closing.
