### ISSUE TITLE
Need a way to hide the suggestion box

### ISSUE THREAD

**Issue by magnus-lpa** [AbdulRahmanAlHamali/flutter_typeahead#43]
When the suggestion box is showing, there seems to be no way to hide it except for tapping on one of the items. Since the suggestion box covers widgets that are placed underneath it, I need some way to close the box, either by tapping outside it or with a "X"-button inside the box itself. Is this possible to do somehow?

**Comment by sjmcdowall** [comment]
What platform? Is this Android?  I think on iOS you can tap on the input text box to close the box? 

I was wondering about this myself -- one of our users was complaining about this .. but I hadn't looked too deeply into it yet.

**Comment by KaYBlitZ** [comment]
Created a PR that hides the suggestions box when keyboard is dismissed #45 . I believe this is a better solution than having the user manually dismiss the box. Will this work in your case?

**Comment by sjmcdowall** [comment]
Fixed in 1.1.0 (by default) with an option to change the behavior.

**Comment by vikalpnagar** [comment]
I am also having this problem. I need a way to dismiss the suggestion box when tapped outside its bounds. Is there a way to do it other than setting hideSuggestionsOnKeyboardHide to true?

**Comment by g-akshay** [comment]
Any updates?

**Comment by vikalpnagar** [comment]
> Any updates?

[Check this comment](https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/169#issuecomment-612319465), it might be of some help.
