### ISSUE TITLE
Long list suggestion laggy after update to flutter 3.3

### ISSUE THREAD

**Issue by fahdboudakim** [AbdulRahmanAlHamali/flutter_typeahead#439]
Hello,
I have a problem with the last update from flutter (3.3->3.3.8).
The suggestion list laggy when is long (10000 item).

**Comment by sjmcdowall** [comment]
I think there is actually a fix for that but its stuck because the tests won't pass due to a PR .. the test is perfectly failing because the PR changed the behavior .. still .. sigh ..

**Comment by fahdboudakim** [comment]
Fix into flutter or in flutter_typeahead?

**Comment by sjmcdowall** [comment]
@fahdboudakim -- any better with the last set of patches?  Re-open if not.

**Comment by fahdboudakim** [comment]
@sjmcdowall problem persist with flutter last version

**Comment by sjmcdowall** [comment]
So make sure -- you are on Flutter 3.7.1 and type_ahead 4.3.3?

**Comment by fahdboudakim** [comment]
Flutter 3.7.3 and type_ahead 4.3.3

**Comment by erdzan12** [comment]
I guess it is laggy because of the property `shrinkWrap` which is enabled inside of the `ListView.separated` widget, as it does leverage the lazy building functionality that way.
https://github.com/AbdulRahmanAlHamali/flutter_typeahead/blob/master/lib/src/common/box/suggestions_list.dart#L207

**Comment by clragon** [comment]
Right, that is a concious decision we made to allow the suggestions box to be smaller than the entire screen.
Generally, I would just recommend not loading 10000 items into your suggestions because no user can meaningfully scroll all those.
