### ISSUE TITLE
[Feature request] Add divider between suggested items

### ISSUE THREAD

**Issue by DartAndrik** [AbdulRahmanAlHamali/flutter_typeahead#441]
It would be great to have property of type `Widget` named like `divider`.  Or maybe configure somehow the divider between suggested items.

**Comment by sjmcdowall** [comment]
There is a PR on this but not sure if its the right solution -- also needs tests, doc, etc. take a look at it.

**Comment by DartAndrik** [comment]
The solution lgtm, thanks)
