### ISSUE TITLE
[suggestion]: Add query String to noItemsBuilder

### ISSUE THREAD

**Issue by Ahmadre** [AbdulRahmanAlHamali/flutter_typeahead#445]
At first: I love this package ❤️ 

Thank you so much!

I was trying: 

```dart
Text(
  I18Next.of(context)!.t('common:no_results', variables: {'query': query}),
  style: Theme.of(context).textTheme.bodyLarge,
),
```

where I want to make the user aware of which query is not finding any elements. 

I will try to open a PR on this.

**Comment by shatanikmahanty** [comment]
@Ahmadre, since the api exposes the TextEditingController, can't we directly access the value like ctrl.text where ctrl is of type TextEditingController?
