### ISSUE TITLE
`onSuggestionSelected` method is not able to called with flutter 3.7 version (extra)

### ISSUE THREAD

**Issue by alphamikle** [AbdulRahmanAlHamali/flutter_typeahead#448]
Hey! I created this issue to highlight the [previous one](https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/446#event-8380177099), for which I found a more or less appropriate solution to the problem.

**Comment by shihuayong** [comment]
Same issue!

**Comment by sjmcdowall** [comment]
Well if we can get a clean PR with a test case then that would be cool (that obviously doesn't break current behavior) :)

**Comment by klokoleva** [comment]
Same issue!

**Comment by acamenhas** [comment]
Same here

**Comment by federico-conte** [comment]
Same here

**Comment by tahaalqadhi** [comment]
Same issue!

**Comment by kstang** [comment]
same

**Comment by sabikrahat** [comment]
same issue!

**Comment by dnkoulouris** [comment]
Same issue here

**Comment by razor-99** [comment]
same issue(

**Comment by razor-99** [comment]
@AbdulRahmanAlHamali help please

**Comment by sjmcdowall** [comment]
@razor-99 -- Hasn't been active on this project in > 3 years.   Others need to step up their game and help.

**Comment by bags4439** [comment]
I'm facing the same issue!

**Comment by arunspacek** [comment]
Please fix this issue. I'm having the same problem. Right now I'm using the previous version.

**Comment by sjmcdowall** [comment]
If someone would actually look into the issue and fix it -- Ill apply the PR .. Not sure what changed in 3.7 to break this

**Comment by sramac2** [comment]
Same issue noticed. On suggestion selected is not triggering

**Comment by AbdulRahmanAlHamali** [comment]
Folks, I haven't been active with Flutter for a few years now, as @sjmcdowall pointed out. The repo lives on thanks to your contributions and to @sjmcdowall's work and follow up.

PRs to solve the issue are more than welcome

**Comment by ShrirangaB** [comment]
+1

**Comment by sjmcdowall** [comment]
I applied a PR to fix this yesterday -- try the latest version?

**Comment by kstang** [comment]
in web platform , after I enter some keywords and get the search result , down arrow key cannot go to search result directly , I must use mouse to click on search result . 

the version for flutter 3.7 or lower can use down arrow key and enter to access to the result directly

**Comment by snakeshift** [comment]
I noticed that onPanDown() recognized the suggestion not onTap().

```
itemBuilder: (context, suggestion) {
            return GestureDetector(
              onPanDown: (_) {
                controller.text = suggestion.name;
              },
              child: Container(
```
