### ISSUE TITLE
(ios) Member not found: 'Scrollable.maybeOf'. final scrollableState = Scrollable.maybeOf(context);

### ISSUE THREAD

**Issue by kleyos** [AbdulRahmanAlHamali/flutter_typeahead#449]
The issue appeared after the latest update. Stopped building ios build due to ```../.pub-cache/hosted/pub.dartlang.org/flutter_typeahead-4.3.1/lib/src/flutter_typeahead.dart:898:40: Error: Member not found: 'Scrollable.maybeOf'.
    final scrollableState = Scrollable.maybeOf(context);
                                       ^^^^^^^
../.pub-cache/hosted/pub.dartlang.org/flutter_typeahead-4.3.1/lib/src/cupertino_flutter_typeahead.dart:649:40: Error: Member not found: 'Scrollable.maybeOf'.
    final scrollableState = Scrollable.maybeOf(context);```

**Comment by samueladekunle** [comment]
Hello @kleyos, I'm currently experiencing this issue on the latest update, I had to downgrade to a lower version. What did you do to solve it?

**Comment by samueladekunle** [comment]
Got it, thank you.
