### ISSUE TITLE
On tap on suggestion in search bar not working in flutter web using flutter_typeahead package

### ISSUE THREAD

**Issue by Sourav-Guleria** [AbdulRahmanAlHamali/flutter_typeahead#451]
i'm using flutter_typeahead: ^4.3.3 package for search bar, onChange it will call api and suggestion were shown on that but it's running one keyword behind the actual search and whenever I try to tap on suggestion it will not navigate to next screen.

I had try to navigate on onSuggestionSelected, onTap and suggestionsCallback but it will not navigate to next screen.

**Comment by Fakerinc** [comment]
I have the same issue. Version: "4.3.2" installed

**Comment by sjmcdowall** [comment]
Try 4.3.3

**Comment by Fakerinc** [comment]
> Try 4.3.3 @Fakerinc

thanks, the upgrade solved it.
