### ISSUE TITLE
SuggestionsBox and Voiceover/Screen Reader

### ISSUE THREAD

**Issue by W2NJL** [AbdulRahmanAlHamali/flutter_typeahead#454]
Hi there,

I have an implementation of the TypeAheadForm with a SuggestionsBox, and I was wondering if anyone has had success with Apple's Voiceover in being able to tap one of the shown suggestions with Voiceover other than the first one in the list?  I am able to get Voiceover to recognize the first result in the list in an example like below by tapping on it (at least on its left side), but any other results in the list are not recognized.  I've spent some time trying to figure out some sort of implementation with the Semantic widget to try remedy this and I can't figure it out.  Has anyone encountered such an issue?
![IMG_4444](https://user-images.githubusercontent.com/55940428/217349887-9ebf2943-516f-4dba-990a-1c600d4a25df.PNG)

       ```


          return ListTile(




            title: Text(suggestion.toString()),
          );
        },
        transitionBuilder: (context, suggestionsBox, controller) {
          return suggestionsBox;
        },
```

**Comment by rmartinez-semillero** [comment]
Hi i have the same problem, i can only select the first item, but the last 2 or 3 not
