### ISSUE TITLE
Suggestions box inside scrollview not updating suggestion box height when we scroll scrollview

### ISSUE THREAD

**Issue by ketanphpdots** [AbdulRahmanAlHamali/flutter_typeahead#455]
I've used TypeAheadFormField inside scrollview in separate screen as well as in showModalBottomSheet in both the screens TypeAheadFormField widget is located like mentioned below.

ScrollView
Column
WidgetA
WidgetB
WidgetC
.
.
.
.
.
TypeAheadFormField
.
WidgetY
WidgetZ

When I click on TypeAheadFormField the keyboard opens and the form scrolls to upside in a such a way that TypeAheadFormField gets visible just above the keyboard area and suggestions are not displayed properly. So, When we scroll our form in upward direction at that time also the suggestions box remains as it is. 

You can refer to below images.

![Screenshot_1675851352](https://user-images.githubusercontent.com/108521156/217503982-2d15b682-1904-489f-aed7-88aeb20d86d5.png)

Further I've tried below solution also but it's not working

When scrollview scroll changes at that time I've called resize() method of SuggestionsBoxController but no luck.

```
TextEditingController tcCounterparty = TextEditingController();
final ScrollController _scrollController = ScrollController();
final SuggestionsBoxController _suggestionsBoxController = SuggestionsBoxController();


@override
void initState() {
  super.initState();
  if (mounted) {
    _scrollController.addListener(() {
      setState(() {
        _suggestionsBoxController.resize();
      });
    });
  }
}

indie Widget build(BuildContext context)

SingleChildScrollView(
  controller: _scrollController,
  child: Column(
    mainAxisSize: MainAxisSize.min,
    children: [

        WidgetA(),
        WidgetB(),
        WidgetC(),

        TypeAheadFormField(
          suggestionsBoxController:_suggestionsBoxController,
          textFieldConfiguration: TextFieldConfiguration(
            controller: tcCounterparty,
            autofocus: false,
          ),
          suggestionsCallback: (pattern) async {
            return myFunction();
          },
          itemBuilder: (context, suggestion) {
            return Container(
              padding: const EdgeInsets.symmetric(
                vertical: 5,
                horizontal: 7,
              ),
              child: Text(
                '${suggestion.value}',
                style: AppStyles.primaryTextStyle(
                  fontSize: 12,
                ),
              ),
            );
          },
          onSuggestionSelected: (suggestion) { },
        ),

        WidgetY(),
        WidgetZ(),
    ],
  ),
),
```

**Comment by felipecastrosales** [comment]
Can you share minimal code example?

**Comment by deandreamatias** [comment]
Related to
- https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/413
- https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/384

**Comment by clragon** [comment]
In the new version 5.x, this issue still exists.
The way the suggestionsbox size is calculated caps at the size of the surrounding Overlay.
To "fix" this, we would need to account for the case where the starting position of the SuggestionsBox is _outside_ of the Overlay.

This might not be too difficult.
However, I find that indefinitely extending the SuggestionsBox in ScrollViews might not be a very desirable behaviour.

@ketanphpdots could you test the behaviour in 5.x and tell us if you still think this functionality would be useful? 
That would be great. Thanks!
