### ISSUE TITLE
What's the purpose of autoFlipListDirection ?

### ISSUE THREAD

**Issue by TheCarpetMerchant** [AbdulRahmanAlHamali/flutter_typeahead#456]
Looking at the comments, `autoFlipListDirection` enables `autoFlipDirection`.
That doesn't seem to make much sense. If you want to deactivate `autoFlipDirection`, just deactivate it. What am I not getting here ?

**Comment by gokhancvs** [comment]
https://github.com/AbdulRahmanAlHamali/flutter_typeahead/pull/431
