### ISSUE TITLE
material 3 default theming

### ISSUE THREAD

**Issue by jobypthomas** [AbdulRahmanAlHamali/flutter_typeahead#457]
Hi,
I am working to convert my app to material3. Do you have any plans to apply the M3 themes to the TypeAhead component?

Thanks!

<img width="1478" alt="Screenshot 2023-02-14 at 9 43 18 AM" src="https://user-images.githubusercontent.com/5605476/218771604-bc3f31a4-cbf2-46ed-940a-cccd6e76af80.png">

**Comment by sjmcdowall** [comment]
I actually am not sure what this means or entails .. This would have to be done in a backwards compatible manner .. but I don't know of anyone working on this .. this is a community sponsored project .. no dedicated programmers ..

**Comment by nawed-alam** [comment]
may i try this??

**Comment by sjmcdowall** [comment]
@nawed-alam -- of course!  Just try to have examples / doc / and a test or two (especially if the desire is to support old and new somehow)

**Comment by jobypthomas** [comment]
@sjmcdowall Thanks for fixing. Can you please advice which version has the fix?

**Comment by sjmcdowall** [comment]
The new one?  5.0
