### ISSUE TITLE
The name 'SuggestionsBoxDecoration' isn't a class. Try correcting the name to match an existing class.

### ISSUE THREAD

**Issue by felipecastrosales** [AbdulRahmanAlHamali/flutter_typeahead#459]
Hi,

In the last hour (coincidentally after the release of the new version) I get this error.

`The name 'SuggestionsBoxDecoration' isn't a class. Try correcting the name to match an existing class.`

It didn't appear before.

I've run the command below in the terminal and it didn't work.

`flutter clean && flutter pub cache repair && flutter pub get`.

Any suggestions here?

**Comment by felipecastrosales** [comment]
Update.

In this way: 
`flutter_typeahead: 4.3.3`

Works good. 

But I think for the above case, we need to check.

**Comment by sjmcdowall** [comment]
Well that's a bit odd -- is your flutter up to date?  The last change dealt with more examples in the examples side, etc. from what I could -- and it passed the (rather limited granted) test suite .. hmmm

**Comment by felipecastrosales** [comment]
I'm in Flutter 3.7.3, @sjmcdowall. 

My tests also broke.

**Comment by ivofernandes** [comment]
Oh maybe it needs to be exported too, I will try to fix it

**Comment by sjmcdowall** [comment]
Well something odd is happening -- many use 3.7.3 (I think) w/o issues .. are you guys on some beta branch ??  I.e. non-stable?

**Comment by ivofernandes** [comment]
Check here, I guess now everything is visible, maybe the example should also use that decoration on the list?

https://github.com/AbdulRahmanAlHamali/flutter_typeahead/pull/460

**Comment by felipecastrosales** [comment]
@ivofernandes I performed a test with your branch and it solved the problem I had in the tests. 

@sjmcdowall, could you confirm with us?

**Comment by ivofernandes** [comment]
Then probably was a problem with the visibility of this classes.
 
The example is not really using that decoration classes in the suggestion box

Can you double check if this visibility makes sense?

<img width="1506" alt="Screenshot 2023-02-17 at 19 19 33" src="https://user-images.githubusercontent.com/606568/219766958-c84a108d-a8f0-4575-aa88-05f65a06efe0.png">

**Comment by felipecastrosales** [comment]
@ivofernandes for me yes. 

When I'm creating barrel files, I like to use [this extension](https://marketplace.visualstudio.com/items?itemName=miquelddg.dart-barrel-file-generator).

**Comment by luis901101** [comment]
Definitely a problem of class not being exported, this will require new version release

**Comment by ivofernandes** [comment]
The PR is ready

https://github.com/AbdulRahmanAlHamali/flutter_typeahead/pull/460

**Comment by sjmcdowall** [comment]
Should be fixed in 4.3.5

**Comment by znromonk** [comment]
Not sure if I should open another issue, but `CupertinoSuggestionsBoxDecoration` is having the same issue. I can get around the issue by manually adding it to my source file as below

```dart
import 'package:flutter_typeahead/src/cupertino/suggestions_box/cupertino_suggestions_box_decoration.dart';
```
It does introduce a dart linter warning:
>Import of a library in the 'lib/src' directory of another package.
Try importing a public library that exports this library, or removing the import.

**Comment by sjmcdowall** [comment]
Well that doesn't sound good .. ugh.  @ivofernandes  ??

**Comment by ivofernandes** [comment]
I can add it too, and will add it to the example file and fix the format to get the package to 140 points

**Comment by ivofernandes** [comment]
Now all the files are being exported

<img width="1506" alt="Screenshot 2023-02-18 at 20 43 41" src="https://user-images.githubusercontent.com/606568/219898703-5c0c3798-9161-42bb-9e0f-0f1fcf89f9e9.png">

**Comment by ivofernandes** [comment]
It's here 
https://github.com/AbdulRahmanAlHamali/flutter_typeahead/pull/461

**Comment by ivofernandes** [comment]
Everything is fine? :) This probably can be closed now?

**Comment by znromonk** [comment]
@ivofernandes 
I added the master branch as dependency and it works. Thank you.

**Comment by felipecastrosales** [comment]
Perfect! I will close this issue. 
Thanks for the quick response, @ivofernandes.
