### ISSUE TITLE
uso das teclas de seta do teclado parou de funcionar a partir da versão flutter_typeahead: ^4.3.1

### ISSUE THREAD

**Issue by jefrabelo** [AbdulRahmanAlHamali/flutter_typeahead#462]
hello, not this browsing with the arrow keys of the keyboard, from the version ^4.3.1, i've tried everything, desperate, if anyone can help me, I thank you.

i use flutter web.

**Comment by sjmcdowall** [comment]
Since I don't speak Portuguese -- can you try the latest of both flutter and typeahead (4.3.6?) .

**Comment by jefrabelo** [comment]
hello, not this browsing with the arrow keys of the keyboard, from the version ^4.3.1, i've tried everything, desperate, if anyone can help me, I thank you.

i use flutter web.

esta atualizado para versao  (3.7.3) and typeahead (4.3.6) .onde so funciona o evento onclick, parou funcionar as setas do teclado

**Comment by ivofernandes** [comment]
I guess you are talking about the suggestion box behaviour?

It's quite strange what you are saying because the user is writing and you expect that the arrows to have an effect on the suggestion list instead of the text field?

**Comment by jefrabelo** [comment]
yes it would be in the suggestion box, sorry

**Comment by sjmcdowall** [comment]
If this is reproducible -- can you add a test case to the test suite that shows it failing? Then we'll know when it actually gets fixed and make sure it doesn't happen again in a future change.

**Comment by matthieurosset** [comment]
This PR #435 removed keyboard usage (up & down).

**Comment by sjmcdowall** [comment]
@matthieurosset I think you are correct -- because it was causing other issues on other platforms, etc.  We need someone to create a clean unified way to handle keyboard usage on all the platforms, with tests, examples, etc.

**Comment by matthieurosset** [comment]
Yes. Totally agree with you @sjmcdowall.

I think about give it a try. I'm pretty sure I can achieve something like Flutter did with its RawAutocomplete (https://github.com/flutter/flutter/pull/83696)

**Comment by sjmcdowall** [comment]
Sounds good!!
