### ISSUE TITLE
onPressed for TextButton inside noItemsFoundBuilder not working for web

### ISSUE THREAD

**Issue by tonynguyen98** [AbdulRahmanAlHamali/flutter_typeahead#469]
I'm using ^4.3.7 and I am trying to create a "Create New" button for when there is no item found. The onPressed for this button is called perfectly fine on Android and iOS, but for web, the function is never reached. 

```
noItemsFoundBuilder: _searchController.text.length < 4
    ? (context) => TextButton(
          onPressed: () {
            print("hello world");
          },
          child: Text('Create new: ${_searchController.text}', style: Styles.uiMedium),
        )
    : null,
```

**Comment by jonbhanson** [comment]
I was able to solve this by copying the fix in #450 and wrapping the child widget in a [`TextFieldTapRegion`](https://api.flutter.dev/flutter/widgets/TextFieldTapRegion-class.html).

**Comment by tonynguyen98** [comment]
That fixed it, thanks!

**Comment by sjmcdowall** [comment]
@jonbhanson -- should that be a PR??

**Comment by BenjiFarquhar** [comment]
@jonbhanson Could you please post the code?
