### ISSUE TITLE
How do I retrigger suggestionsCallback?

### ISSUE THREAD

**Issue by greenking19** [AbdulRahmanAlHamali/flutter_typeahead#471]
My buildItem can remove functionality, but I want to rebuildItem after deleting it, so I want to know how to trigger suggestionsCallback

**Comment by justincbeck** [comment]
I also need to know this.

**Comment by NiranjanShah** [comment]
Yes,

the same approach of callback is used.

if the text user is searching returns list count of 0, then we reduce 1 character of the text typed and then search the list again.




Regards,

Niiranjan G Mandan

**Comment by sjmcdowall** [comment]
Can we close this issue now? Seems like there is a solution @greenking19

**Comment by greenking19** [comment]
> Can we close this issue now? Seems like there is a solution @greenking19

I found a workaround, but it's not perfect@sjmcdowall 
👨🏻‍💻
