### ISSUE TITLE
TypeAheadFormField in BottomSheet no keyboard (physical mobile only)

### ISSUE THREAD

**Issue by jobypthomas** [AbdulRahmanAlHamali/flutter_typeahead#472]
Hi,

When using TypeAheadFormField in BottomSheet along with other TextFormField does not work. I tried with autofocus:true/false but without luck. Current setup is with autofocus:true for TextFormField and autofocus:false for TypeAheadFormField
This only happens in real mobile devices. Works fine on my Mac and even mobile simulators.

Thanks!

https://user-images.githubusercontent.com/5605476/224482465-357169c2-ddc1-4741-a11a-583be2f2dfa2.MOV

**Comment by jobypthomas** [comment]
@natesitton80 @jonbhanson any thoughts?

**Comment by sjmcdowall** [comment]
Anyone!?  Seems odd ..

**Comment by jobypthomas** [comment]
@sjmcdowall Works find in real devices when TypeAheadFormField in in a Page. Only issue is when it is in the BottomSheet!

**Comment by jobypthomas** [comment]
@sjmcdowall Many thanks! Which version includes this fix?
