### ISSUE TITLE
Expose the current pattern to noItemsFoundBuilder

### ISSUE THREAD

**Issue by lockieRichter** [AbdulRahmanAlHamali/flutter_typeahead#473]
Hi,

This package is great, thanks for all your hard work!

Is there an easy way to get the current search pattern in the `noItemsFoundBuilder`? I would like to display a message that contains the search term, and then in the future actually display a button that allows a user to create the option that is not present in the list.

Thanks!

**Comment by clragon** [comment]
You can pass your own TextEditingController and access the current search through that.
