### ISSUE TITLE
Loading indicator - when is it visible?

### ISSUE THREAD

**Issue by Mik77o** [AbdulRahmanAlHamali/flutter_typeahead#474]
When is the loader visible? Only when `TypeAheadField` is first built? It should be visible when searching for suggestions...

**Comment by Mik77o** [comment]
Probably I should set `keepSuggestionsOnLoading: false`, yes?

**Comment by sjmcdowall** [comment]
Seems like something to try -- did it work @Mik77o ?? IF so can you close this item?

**Comment by Mik77o** [comment]
@sjmcdowall yes, we can close it.
