### ISSUE TITLE
Bug in Typeahead on Android 13 (physical device)

### ISSUE THREAD

**Issue by brandaoti** [AbdulRahmanAlHamali/flutter_typeahead#475]
Hi,

https://user-images.githubusercontent.com/49381250/227955737-f47b2790-e7d4-49bf-bfff-929da5a59665.mp4

We have identified a bug in the Typeahead feature on Android 13. After clicking on the form, it is not possible to select a suggestion. We have tested the code and confirmed that the issue only occurs on Android 13.

On the android emulator 13 it works but on the physical device it doesn't

**Comment by sjmcdowall** [comment]
I don't think then this is a bug within Typeahead itself.  It's m ore likely some underlying core Flutter issue?

**Comment by brandaoti** [comment]
Thanks for bringing that up. You may be right that the issue is not specifically related to Typeahead, but rather a more general problem with Flutter on Android 13.

I'm thinking of implementing a workaround for this particular issue, such as using a modal to display the search results instead of Typeahead.

**Comment by aman246149** [comment]
Hi, i also faced this issue, Is there any way to overcome this??

**Comment by brandaoti** [comment]
I tried to implement this new suggestion, but it's not functional on Android 13. The bug occurs because the item build is not clickable; it basically clicks on the information below the suggestion. But thank you for the feedback.

I decided to remove the package for now and created another normal search field since it was an urgent fix that only affects Android 13.

**Comment by Mecharyry** [comment]
I was seeing the same issue on my Android 13 device and tracked it down to `Semantics` causing the issue. Removing this section from the lib made it work again: https://github.com/AbdulRahmanAlHamali/flutter_typeahead/blob/master/lib/src/material/field/typeahead_field.dart#L826-L836

Not ideal if you have users that rely on accessibility settings to navigate the app.

**Comment by Mecharyry** [comment]
It works perfectly when using talkback, so it seems likely this is a bug in Flutter where it is reporting accessibility required even though the device doesn't use anything like talkback, switch access etc.

**Comment by Mecharyry** [comment]
I now have more details for anyone else facing the same issue. If any of your apps have accessibility features e.g. 1Password, any mobile security etc. They will be under `Accessibility` -> `downloaded apps` this will mark the device as having accessibility enabled, which means you'll fall into the Semantics block, which is why you likely see the issue on your devices. Here's my device, accessibility settings. If I turn all of these off then the typeahead library works again

![flutter_1](https://user-images.githubusercontent.com/3380092/229761067-cc769553-6197-4e7f-9946-e6524011ab63.png)

**Comment by sebastianbuechler** [comment]
> I now have more details for anyone else facing the same issue. If any of your apps have accessibility features e.g. 1Password, any mobile security etc. They will be under `Accessibility` -> `downloaded apps` this will mark the device as having accessibility enabled, which means you'll fall into the Semantics block, which is why you likely see the issue on your devices. Here's my device, accessibility settings. If I turn all of these off then the typeahead library works again
> 
> Disable apps
> <img alt="" width="300/" src="https://user-images.githubusercontent.com/3380092/229761067-cc769553-6197-4e7f-9946-e6524011ab63.png">

Thank you very much for this information. It helped us very much to test the bug locally!
