### ISSUE TITLE
using the flutter_typeahead package and facing an issue where you can't select the items from the suggestions, 

### ISSUE THREAD

**Issue by s2yed** [AbdulRahmanAlHamali/flutter_typeahead#479]
flutter_typeahead: ^4.3.7
  sdk: ">=2.19.0 <3.0.0"

**Comment by ajk99** [comment]
When debugging I see this problem with an actual Pixel 6 Api 33, but it works ok with a Pixel 6 Api 33 simulator. The tap is ignored by type_ahead and goes through to whatever is underneath, if that's tappable.

**Comment by s2yed** [comment]
The same thing is happening, how do I solve the problem?

**Comment by concernedrat** [comment]
Any ideas? I'm facing the same problem using an iPhone 12 Pro

**Comment by mohanadshaban** [comment]
Same here with flutter version 3.7.3

**Comment by mohanadshaban** [comment]
I've tried rolling back flutter_typeahead to 4.3.1 and sometimes it's working fine

**Comment by Abolfazlnezami2000** [comment]
I have the same problem. how to fix it?

**Comment by affanminhas** [comment]
I am also facing this issue in Android 11 where it does not select any item from the suggestion box.

**Comment by programmermager** [comment]
same here, facing same issue

**Comment by programmermager** [comment]
> I've tried rolling back flutter_typeahead to 4.3.1 and sometimes it's working fine

i try your suggestion, but still doesnt work in my case

**Comment by AlexandreKueny** [comment]
Same issue on OnePlus 9 pro

**Comment by wendreof** [comment]
Having the same problem
Flutter: 3.7.12
flutter_typeahead: ^4.1.1

I need some fix ASAP

**Comment by riyanto978** [comment]
i try this solutions and work for me

https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/463#issuecomment-1460966010

**Comment by tebalink** [comment]
Having the same problem

**Comment by justincbeck** [comment]
@sjmcdowall - Does PR 495 also fix this issue? I'm grabbing it and testing now but wanted to see if that was intentional or if it is resolved. Thanks for tackling either way.

**Comment by sjmcdowall** [comment]
Well damn :(   Doesn't this almost seem to be a low level Flutter issue if it doesn't work on only SOME Android devices?  I don't think there is much (any?) Android device code within this package?  Although I never delved deep into the device side of things..

**Comment by justincbeck** [comment]
> > Well damn :( Doesn't this almost seem to be a low level Flutter issue if it doesn't work on only SOME Android devices? I don't think there is much (any?) Android device code within this package? Although I never delved deep into the device side of things..
> 
> Unsure. I am on Flutter 3.7.10 in my app (iOS and Android, soon to be web also) and I see the issue. I am considering trying to upgrade to 3.10.0 but that has it's own set of headaches.
> 
> It is an elusive and odd bug for sure.

Upgraded to Flutter 3.10.4 and Dart 3.0.3 and I still experience the problem with version 4.6.1 of this lib.

**Comment by justincbeck** [comment]
So, is this just totally broken for 60% of the world on Android right now? For a library that's so popular I'm surprised there isn't more being said about this issue.

I don't think I have the capability (or the time at the moment) to resolve this. If it's truly a flutter core problem how do we get Google to pay attention?

**Comment by BenjiFarquhar** [comment]
@justincbeck I think it is broken because of the new versions of Flutter as I can't get it working with very old versions of this package.

**Comment by HaniKhaledAli** [comment]
I have this issue (Flutter 3.11, Dart 3.1.0) I can't select first item in suggestion box and sometimes the first three items can't selected (Android 13) note 20 ultra.

**Comment by sebastianbuechler** [comment]
Can reproduce this bug on Android 13 in combination with Dart 3 and Dart 2. 

May I ask what people did to solve the issue as it seems a bug fix is not around the corner? Did anybody of the issue commentators here (@HaniKhaledAli, @BenjiFarquhar, @justincbeck, @sjmcdowall, @Mecharyry, @tebalink, @riyanto978, @wendreof, @AlexandreKueny, @programmermager, @affanminhas, @Abolfazlnezami2000, @mohanadshaban, @s2yed, @ajk99) use a different library or found a work-around?

**Comment by justincbeck** [comment]
I went back to using RawAutoComplete but it's been a big challenge trying to get it working the way I need. The power of this library is how flexible it is. It's a pity users are facing this issue.

**Comment by sjmcdowall** [comment]
Agreed -- been hoping someone can figure this out who is an Android guru .. it seems odd its on a specific android device (?) or is it the OS that caused it?  I have no idea .. and I THINK I remember the Android emulators work fine, it's just the real device on some manufacturers?

**Comment by sjmcdowall** [comment]
Well @AbdulRahmanAlHamali hasn't been active on this project in over 3+ years, so I doubt he has any clout nor do I.  I just maintain this from PR's other people provide, etc. to keep it going.  Someone much more talented than I will need to go in-depth into the issue and track it down and see what in the world is the root cause here.

**Comment by justincbeck** [comment]
Sadly, I also don't have what it takes to resolve this. I'm giving up, I have what I need (mostly) from the stock RawAutoComplete widget; I'll just go with that.

**Comment by AlexandreKueny** [comment]
> Can reproduce this bug on Android 13 in combination with Dart 3 and Dart 2.
> 
> May I ask what people did to solve the issue as it seems a bug fix is not around the corner? Did anybody of the issue commentators here (@HaniKhaledAli, @BenjiFarquhar, @justincbeck, @sjmcdowall, @Mecharyry, @tebalink, @riyanto978, @wendreof, @AlexandreKueny, @programmermager, @affanminhas, @Abolfazlnezami2000, @mohanadshaban, @s2yed, @ajk99) use a different library or found a work-around?

This is working for me: https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/463#issuecomment-1460966010
I dont need accessibility in my case, but for a publicly available app it might be better to use RawAutoComplete as @justincbeck did.

**Comment by sebastianbuechler** [comment]
> > Can reproduce this bug on Android 13 in combination with Dart 3 and Dart 2.
> > May I ask what people did to solve the issue as it seems a bug fix is not around the corner? Did anybody of the issue commentators here (@HaniKhaledAli, @BenjiFarquhar, @justincbeck, @sjmcdowall, @Mecharyry, @tebalink, @riyanto978, @wendreof, @AlexandreKueny, @programmermager, @affanminhas, @Abolfazlnezami2000, @mohanadshaban, @s2yed, @ajk99) use a different library or found a work-around?
> 
> This is working for me: [#463 (comment)](https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/463#issuecomment-1460966010) I dont need accessibility in my case, but for a publicly available app it might be better to use RawAutoComplete as @justincbeck did.

Thanks for the answers. I saw that there's a PR open that uses a similar approach but on a package basis and it resolved my issue: https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/463#issuecomment-1619063676

However, it will still take away accessibility from the dropdown widget and thus is not a long-term solution. Just wanted to point out that it worked for me.

**Comment by Mecharyry** [comment]
I've written in a few places where the issue crops up: https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/463#issuecomment-1495833267

I just don't have the time or the knowledge of the component causing the issue to be able to fix it atm unfortunately. The app I am working on has implemented the same fix as https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/463#issuecomment-1460966010 for now, however, this is a hack IMO and not an actual solution to the underlying problem. 

Again, if anyone has any knowledge on what I have documented in https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/463#issuecomment-1495833267 then you might be able to solve the issue. If anyone can impart some knowledge on me for that component I can try to fix it myself. I have a feeling we can just remove it and all will be well, but I haven't had the time to test the library in detail to confirm my hypothesis.

**Comment by justincbeck** [comment]
Has this been "fixed" or is it closed as "won't fix"? If it's fixed, in what version is the patch?

**Comment by justincbeck** [comment]
Will do, thanks so much.
