### ISSUE TITLE
Feature request: show previous suggestion on focus after select suggestion

### ISSUE THREAD

**Issue by shehabmohamed0** [AbdulRahmanAlHamali/flutter_typeahead#487]
after selecting on of the suggestions, suggestion box close, and it does not show the suggestions again unless you change the text in the text field manually.

**Comment by steveny909** [comment]
I thought I was doing something wrong with controller, but then realized that after you select one of the suggestions you don't show suggestions again.   Is this a bug or feature request?

**Comment by shehabmohamed0** [comment]
> I thought I was doing something wrong with controller, but then realized that after you select one of the suggestions you don't show suggestions again. Is this a bug or feature request?

when you set minCharsForSuggestions to 0 the suggestions callback get called immediately when text field get the focus and show the suggestions with a new request not with the last one.
So I think it's a feature request to cache the previous response.

**Comment by clragon** [comment]
You can set `hideOnSelect` to false to disable closing the box.
