### ISSUE TITLE
Request to add validator and autovalidate options

### ISSUE THREAD

**Issue by kaseyrossanderson** [AbdulRahmanAlHamali/flutter_typeahead#488]
Hello,

It would be nice to be able to validate the TypeAheadField using both the validator and autovalidateMode options available to normal text form fields.

Is it possible to get this feature implemented sometime in the future?

**Comment by sumitsharansatsangi** [comment]
Use  `TypeAheadFormField()` instead of  `TypeAheadField()`. As you use, `TextFormField()` instead of `TextField()`.

**Comment by milindgoel15** [comment]
Hi, i have been trying to use the validator in TypeAheadFormField() but it returns nothing. The only way I have to check validation is by checking the value using textEditingController.

This is my code for typeaheadformfield.
https://katb.in/sexajikoful
