### ISSUE TITLE
Could not find method disable() for arguments [InvalidPackage] on task ':flutter_keyboard_visibility:lint'

### ISSUE THREAD

**Issue by RasheeqZaman** [AbdulRahmanAlHamali/flutter_typeahead#490]
A problem occurred evaluating project ':flutter_keyboard_visibility'.
> Could not find method disable() for arguments [InvalidPackage] on task ':flutter_keyboard_visibility:lint' of type com.android.build.gradle.tasks.LintGlobalTask.

Any solutions?

**Comment by sjmcdowall** [comment]
Isn't this an error in the flutter_keyboard_visibility package itself not typeahead?  And to be accurate this is a LINT error right because all the tests passed in the package when run.

**Comment by isamuhiro** [comment]
Were you able to get rid of this lint issue? My problem is to ignore the transitive dependency lint.

**Comment by SM-SHIFAT** [comment]
fixed it by upgrading my gradle version from 4.1.1 to 7.4.1
just add this line below in android > build.gradle :
```classpath 'com.android.tools.build:gradle:7.4.1'```

It should look like this.
![image](https://github.com/AbdulRahmanAlHamali/flutter_typeahead/assets/60544576/eba59127-b9fb-40ac-b145-ed60b58be035)
