### ISSUE TITLE
Keyboard not showing when focus

### ISSUE THREAD

**Issue by royhanrahim** [AbdulRahmanAlHamali/flutter_typeahead#496]
The keyboard doesn't appear when it's focused, is there something missing from me?

![Screenshot_1686196670](https://github.com/AbdulRahmanAlHamali/flutter_typeahead/assets/31684850/7ddc6923-5c6b-44fe-93ae-0018fa950de1)
![Screenshot_1686196745](https://github.com/AbdulRahmanAlHamali/flutter_typeahead/assets/31684850/b655cfc4-a5bf-443e-9667-0141ac036313)

**Comment by sjmcdowall** [comment]
Is this perchance on an Android thing?  If so -- sadly a known issue for some Android devices -- but no one is sure why or where or how to fix .. :(  If not, then must be something else since fundamentally this project appears to work in other environments decently.

**Comment by royhanrahim** [comment]
On an iOS device, the keyboard doesn't come out the same, I've also done this before in another project, absolutely no bugs like this, everything runs smoothly, only this project found a bug like that, I'm also confused :D

**Comment by royhanrahim** [comment]
Is it because I'm using the "responsive_builder" package ?

**Comment by royhanrahim** [comment]
is there a way out ? :'(

**Comment by royhanrahim** [comment]
I've found the error, apparently if "TextInputType.none" the keyboard won't appear :D
thank you very much for answering my question ;)

**Comment by royhanrahim** [comment]
I've found the error, apparently if "TextInputType.none" the keyboard won't appear :D
thank you very much for answering my question ;)
