### ISSUE TITLE
onSuggestionSelected is not called on some android devices on flutter 3.7

### ISSUE THREAD

**Issue by akash1238** [AbdulRahmanAlHamali/flutter_typeahead#497]

**Comment by sumitsharansatsangi** [comment]
@akash1238, can you please list some devices here, so that we can also check.

**Comment by akash1238** [comment]
> @akash1238, can you please list some devices here, so that we can also check.

samsung m30s, oneplus nord, oneplus 6

**Comment by akash1238** [comment]
> 

that solution is not working
