### ISSUE TITLE
How can I make the scrollbar always visible?

### ISSUE THREAD

**Issue by super1947** [AbdulRahmanAlHamali/flutter_typeahead#499]
How can I make the scrollbar always visible?

**Comment by sumitsharansatsangi** [comment]
@super1947, May I understand, why you always need visible scrollbar. Based on the content,  `flutter_typeaheadfield` automatically displays scrollbar.

**Comment by super1947** [comment]
Thank you for answer. 
I already know that scrollbars appear when scrolling. 
But I want it to always be visible so the user knows they can scroll.
This is because the first time the textfield is clicked, the user may not know whether it scrolls because no scrollbar is displayed.
Thank you.

**Comment by eivihnd** [comment]
@super1947 
I also need that functionality. I have created a pull request that will set the [thumbVisibility](https://api.flutter.dev/flutter/material/Scrollbar/thumbVisibility.html) of the Scrollbar widget to `thumbVisibility: widget.scrollbarAlwaysVisible`.

**Comment by super1947** [comment]
@eivihnd 
Thank you so much😀

**Comment by brun0xon** [comment]
Something like a workaround. Pass builder function to `layoutArchitecture` params and make sure param `hasScrollbar` is false in `suggestionsBoxDecoration`
```
return ScrollbarTheme(
      data: ScrollbarTheme.of(context).copyWith(
          trackVisibility: const MaterialStatePropertyAll(true),
          thumbColor: const MaterialStatePropertyAll(AppColors.black)),
      child: Scrollbar(
        controller: controller,
        thickness: 2,
        thumbVisibility: true,
        child: ListView.builder(
          itemCount: items.length,
          controller: controller,
          itemBuilder: (context, index) => items.elementAtOrNull(index),
        ),
      ),
    );
```
