### ISSUE TITLE
Quick question is all

### ISSUE THREAD

**Issue by sjmcdowall** [AbdulRahmanAlHamali/flutter_typeahead#5]
Using this package and it's awesome -- I have a quick question -- our users want the "search" to automatically load the first N items upon entry to the screen .. or if they click on the search field (if its empty) etc.  How can we invoke the suggestionsCallback() and that logic immediately before they have to type anything -- or if they click on the field (I don't see it called on a touch) ?? 

Something in the order of the TextController ??  But I'm pretty new on that .. 

Thanks!

**Comment by sjmcdowall** [comment]
Did you happen to just add this to TypeAheadField but not TypeAheadFormField ??   It is working on the one but getting an error on the other... ??

**Comment by AbdulRahmanAlHamali** [comment]
You're right!

I apologize for that, I just pushed version 0.4.1 to fix that, give it a try and let me know :)

**Comment by sjmcdowall** [comment]
LOL -- I realized I was using the TypeAheadFormField in a non-form so changed them to TypeAheadField .. sooo... I am sure it's working fine -- the TypeAheadField is working flawlessly!!  NICE!

**Comment by AbdulRahmanAlHamali** [comment]
Great! Glad I could help :)
