### ISSUE TITLE
Is there a way to show suggestions on top of text filed instead below?

### ISSUE THREAD

**Issue by harshapulikollu** [AbdulRahmanAlHamali/flutter_typeahead#50]
Showing suggestions list on below of text field is being covered by the keyboard is there any option or workarround such that the suggestions listview will be shown on top of the textfield which will make easier for user to select the option from suggestions.

**Comment by sjmcdowall** [comment]
Yes that feature was added a few mini releases ago -- see the direction:  thing and maybe offset etc.  Does that work?

**Comment by harshapulikollu** [comment]
Sorry I figured it out when I saw the code. Thank you.
