### ISSUE TITLE
KeySelection is not working on MacOS 

### ISSUE THREAD

**Issue by Vera-Spoettl** [AbdulRahmanAlHamali/flutter_typeahead#502]
Typing "Key down" key on the physical keyboard (MacOS) has no effect.

Changing the onKeyboardEvent in KeyboardSuggestionSelectionNotifier slightly seems to fix the problem.

```
class KeyboardSuggestionSelectionNotifier
    extends ValueNotifier<LogicalKeyboardKey?> {
  KeyboardSuggestionSelectionNotifier() : super(null);

  void onKeyboardEvent(RawKeyEvent event) {
    // * we only handle key down event
    // ---> this seems to be the problem --->
    // if (event.runtimeType == RawKeyUpEvent) return;
    // ---> therefore comment this out ... --->

    if (event.logicalKey == LogicalKeyboardKey.arrowDown ||
        event.logicalKey == LogicalKeyboardKey.arrowUp) {
      if (value == event.logicalKey) {
        notifyListeners();
      } else {
        value = event.logicalKey;
      }
    } 
    // ---> ... and move it here --->
    else if (event.runtimeType == RawKeyUpEvent) return;
  }
}

```

As this seems a too easy fix for the problem I'm not sure if nobody else had this problem before or if I miss a side effect that causes problems.
Or do I miss a property / callback / ... that would solve the problem without changing code?

**Comment by sjmcdowall** [comment]
This seems familiar sounding to be honest .. but I can't remember at all the details and what the work around etc. is -- have you looked at the prior issues?  I think there is some pretty hefty code needed to be added to handle physical up/down arrows for Web desktop stuff .. but its been months since anyone mentioned this and no PR was ever submitted...

**Comment by Vera-Spoettl** [comment]
It seems that the mentioned code change is only a partial solution. When I implement it, it works for the first item in the suggestion box but the second arrowup event sets the focus outside of the list to the next widget. :-( 
So I better don't submit a PR as it is not a real solution.
