### ISSUE TITLE
TypeAheadFormField cannot be disabled

### ISSUE THREAD

**Issue by royale1223** [AbdulRahmanAlHamali/flutter_typeahead#503]
TypeAheadFormField is not disabled even when 'enabled' property is set to false.

Using flutter_typeahead: ^4.6.1

**Comment by sjmcdowall** [comment]
This seems pretty basic -- maybe a code snippet example ??  Hard to believe no one has noticed this in 3+ years .. :)

**Comment by Rokasurba** [comment]
Look at the issue below
https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/355
