### ISSUE TITLE
Possible to put an icon at the bottom right of the suggestions box?

### ISSUE THREAD

**Issue by jooikwanw** [AbdulRahmanAlHamali/flutter_typeahead#521]
I am using flutter typeahead for Google address autocomplete and according to this:
https://developers.google.com/maps/documentation/places/web-service/policies#logo

I will need to put the logo at the bottom right of the suggestions box. Is this possible?

**Comment by AlexandrePB-za** [comment]
noItemsFoundBuilder: (context) => ListTile(
                            leading: CircleAvatar(
                              child: Icon(Icons.add),
                            ),
                            title: Text(
                              'add',
                              style: TextStyle(
                                color: Colors.black87,
                              ),
                            ),
                            onTap: () => {
                             
                            },
                          ),
