### ISSUE TITLE
Issue of onTapOutside function

### ISSUE THREAD

**Issue by khaledmorshed** [AbdulRahmanAlHamali/flutter_typeahead#533]
TypeAheadFormField(
              textFieldConfiguration: TextFieldConfiguration(
                controller: textController,
                focusNode: focusNode,
                onChanged: (value){
                },
                onTapOutside: (value){
                  print("onTapOutside.............TypeAheadFormField");
                }
              ),
              suggestionsCallback: (value){
                return list;
              },
              itemBuilder: (context, dynamic suggestion) {
                return  DropdownMenuItem(
                  child: Padding(
                    padding: EdgeInsets.all(12),
                    child: Text(suggestion,
                      style:  const TextStyle(
                        color: Colors.black,
                        fontSize: 15,
                        fontWeight: FontWeight.w400,
                      ),
                    ),
                  ),
                );
              },
              onSuggestionSelected: (suggestion) {
                textController.text = suggestion;
                setState(() {

                });
                //return suggestion;
              },
            ),
Here onTapOutside function not working after clicking outside anywhere on screen. Could you give me solution?

**Comment by khaledmorshed** [comment]
Thank you brother for your resposne. I do not want to go with that snippet code. I want solution with this function wich is given bellow.
onTapOutside: (value){
print("onTapOutside.............TypeAheadFormField");
}

**Comment by 69-69** [comment]
Ok...there is new update released...check pub.dev
