### ISSUE TITLE
enableSuggestions=false not working

### ISSUE THREAD

**Issue by sqcsabbey** [AbdulRahmanAlHamali/flutter_typeahead#535]
We're getting suggestions above the keyboards, on both Android and iOS, even though we're setting enableSuggestions to false, like:

```
TypeAheadFormField(
                    hideOnEmpty: true,
                    direction: AxisDirection.up,
                    textFieldConfiguration: TextFieldConfiguration(
                        autocorrect: false,
                        enableSuggestions: false, ...
```

**Comment by clragon** [comment]
the current code does no longer use this value.
however, this parameter is in the wrong place anyways.
`TextFieldConfiguration` is meant to mirror the `TextField` parameters, 
so it should not have a parameter related to configuring the suggestions itself.

I will see if I can add a new parameter that enables or disables suggestions to the `TypeAheadFormField` itself.

**Comment by sqcsabbey** [comment]
I gave it a shot, I tried setting enableSuggestions (`enableSuggestions: widget.textFieldConfiguration.enableSuggestions,`) on the TextField in _TypeAheadFieldState.build (and the related Cupertino version), but this didn't make the keyboard suggestions go away. Any tips for me?
