### ISSUE TITLE
Issue cleanup

### ISSUE THREAD

**Issue by clragon** [AbdulRahmanAlHamali/flutter_typeahead#536]
Please close the following issues:

- [x] #390
- [x] #410
- [x] #412
- [x] #416
- [x] #423
- [x] #430 
- [x] #441
- [x] #442
- [x] #445 
- [x] #454 
- [x] #456 
- [x] #457 
- [x] #462 
- [x] #463
- [x] #469
- [x] #473 
- [x] #477
- [x] #479 
- [x] #481 
- [x] #482
- [x] #483
- [x] #487
- [x] #488
- [x] #490
- [x] #497
- [x] #498
- [x] #499
- [x] #502
- [x] #503
- [x] #506
- [x] #511
- [x] #515
- [x] #517
- [x] #518
- [x] #521
- [x] #527
- [x] #529
- [x] #532
- [x] #533
- [x] #535

@sjmcdowall

**Comment by sjmcdowall** [comment]
Done
