### ISSUE TITLE
Add "`keepSuggestionsOnLoading` has been renamed to `retainOnLoading`" on Migration guide

### ISSUE THREAD

**Issue by MorosophDude** [AbdulRahmanAlHamali/flutter_typeahead#537]
Seems like this was missed on **Migrations From 4.x to 5.x** section in readme. 

I know this change is listed under `Changelog` for `v5.0.0` but it would be nice to have it in migration guide as well.

**Comment by masewo** [comment]
For me I had to change a lot of stuff to keep my previous behaviour. Figuring out what, was quite painful:

- Introduce a `builder`, that returns a `TextFormField` with all the configuration from `TextFieldConfiguration`.
- Change text color in `itemBuilder` for dark mode.
- Replace `SuggestionsBoxDecoration` by a `decorationBuilder` that returns a `Material` Widget with type card and elevation 4 (somehow I did not need the `offsetX` anymore)
- Move the `BoxConstraints` from the `SuggestionsBoxDecorration` to constraints
- Replace `getImmediateSuggestions` by `debounceDuration` zero
- Replace `suggestionsBoxVerticalOffset` by `Offset`
- Replace `AnimationController` of transitionBuilder by `Animation<double>`
- Replace `onSuggestionSelected` by `onSelected`

And the worst was to find out how to handle my special usecase, where I use the text value of one text field for the suggestions of another text field.
At the end I had to introduce a virtual `TextEditingController`, that mirrors the values.
The clue was to delay the setting of the `TextEditingController` value with a zero duration to not interfer with the focus/show/hide logic.

Anyway: Thank you for the changes! The API is now a lot more clear.

**Comment by clragon** [comment]
Sorry about that, I tried catching all the changes!

If you need specific custom logic for suggestions, in the new version you can directly control the suggestions through the `SuggestionsController`. You may even extend and make your own Controller for more fine grained needs.

I'll see if I can add some of the things I missed to the migration guide when I have time. Thanks!

**Comment by masewo** [comment]
Don't worry. All good.

I tried my luck with the SuggestionsController, but it behaved unpredictable for me, e. g. it did not open when I called open. But maybe I did a mistake.

**Comment by clragon** [comment]
I have added this to the migration guide now.

If you find that the SuggestionsController is not working as expected, please open an issue!
Thanks!
