### ISSUE TITLE
flutter TypeAheadField onSuggestionSelected not work in real android device but work on emulatur

### ISSUE THREAD

**Issue by kia1349** [AbdulRahmanAlHamali/flutter_typeahead#540]
I have a Flutter project in Android Studio In this program there is a section to edit or add addresses The list of countries is loaded, and after the user selects the desired country, then the list of provinces is loaded, and after the user selects a province, the list of cities in that province is loaded, and the user can choose his city. This program works properly in the emulator

In the emulator, when the list of countries is loaded, by clicking the mouse on the country, that country is selected and the values of that country are displayed in the next box. But in the real mobile phone (my device is xiaomi me 11 ultra), when I tap on the country, nothing happens and the program does not react I am using and test both of flutter_typeahead: ^4.0.0 and flutter_typeahead: ^4.8.0 but the problem still remains

my complete code is large and i can not paste here but shared here: [link](https://mega.nz/file/H8AgUbZB#xfsfGC0ChMhNwMLxp57o_bvuWNk8PabYVgh1QPHiWlw)

**Comment by clragon** [comment]
please upgrade to `flutter_typeahead: ^5.0.0` and lets us know if the issue still occurs.

**Comment by kia1349** [comment]
> please upgrade to `flutter_typeahead: ^5.0.0` and lets us know if the issue still occurs.

hi @clragon 
special thanks
My problem was solved with version 5.0.0 and 5.0.1 and now everything works fine         (👍 ͡❛ ͜ʖ ͡❛)👍

**Comment by clragon** [comment]
thank you!
