### ISSUE TITLE
TextField text doesnot update after change

### ISSUE THREAD

**Issue by kuromadara** [AbdulRahmanAlHamali/flutter_typeahead#546]
I'm trying to update textfield text after a item is selected but its not working

import 'package:flutter/material.dart';
import 'package:flutter_typeahead/flutter_typeahead.dart';
import 'package:pragya/models/models.dart';

class CommonDropdown extends StatefulWidget {
  final List<CommonIdName> dropdownList;
  final int? selectedIndex;
  final ValueSetter<int?>? onChanged;

  const CommonDropdown({
    super.key,
    required this.dropdownList,
    required this.selectedIndex,
    required this.onChanged,
  });

  @override
  _CommonDropdownState createState() => _CommonDropdownState();
}

class _CommonDropdownState extends State<CommonDropdown> {
  final TextEditingController slectedTextController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return TypeAheadField<CommonIdName>(
      suggestionsCallback: (pattern) async {
        return widget.dropdownList
            .where((element) =>
                element.name.toLowerCase().contains(pattern.toLowerCase()))
            .toList();
      },
    
      builder: (context, slectedTextController, FocusNode focusNode) {
        return TextField(
          controller: slectedTextController,
          focusNode: focusNode,
          // autofocus: true,
          decoration: const InputDecoration(
            labelText: 'Select',
          ),
        );
      },
      itemBuilder: (context, CommonIdName suggestion) {
        return ListTile(
          title: Text(suggestion.name),
        );
      },
      onSelected: (CommonIdName suggestion) {
        final index = widget.dropdownList.indexOf(suggestion);
        widget.onChanged?.call(index + 1);
        setState(() {
          slectedTextController.text = suggestion.name; // Set the text here
        });
        print("after selecting: ${slectedTextController.text}");
      },
      loadingBuilder: (context) => const Text('Loading...'),
      errorBuilder: (context, error) => const Text('Error!'),
      emptyBuilder: (context) => const Text('No items found!'),
    );
  }
}

**Comment by kuromadara** [comment]
ok found a solution in closed issue

**Comment by ronsrebro** [comment]
> ok found a solution in closed issue

Next time it would be great if you added a link to the issue here, so other won't need to go find it too
