### ISSUE TITLE
When i set autoflip for suggestions it goes overlay on app bar which looks not good kindly provide solution.

### ISSUE THREAD

**Issue by harithm918** [AbdulRahmanAlHamali/flutter_typeahead#547]
![61370105-372dc380-a8af-11e9-9c69-782b1c94f2da](https://github.com/AbdulRahmanAlHamali/flutter_typeahead/assets/13028171/cd09cc64-51e3-4ae8-8c9e-4acbe1b65c3a)

**Comment by clragon** [comment]
I've answered over in #115. 
please see that issue instead.
