### ISSUE TITLE
suggestionsCallback is not called at all with ios emulator

### ISSUE THREAD

**Issue by gpernelle** [AbdulRahmanAlHamali/flutter_typeahead#549]
Same as #542 . Is there any solution for that?

**Comment by clragon** [comment]
could you please provide a code sample and reproduction steps?

**Comment by linsvensson** [comment]
I have the same problem. Except it's called once when it gets focused, but not when typing.

**Comment by LerryGO** [comment]
Im waiting for solution, same problem here, its just called when tap in the first time on textfield

**Comment by clragon** [comment]
please provide us with a code sample and reproduction steps.

otherwise, we will not be able to investigate this issue.

**Comment by LerryGO** [comment]
Sorry, in my case, it was my mistake. I forgot to include the TextEditingController parameter in the constructor of my textfield controller in the code
