### ISSUE TITLE
Update pointer_interceptor dependency

### ISSUE THREAD

**Issue by dnkoulouris** [AbdulRahmanAlHamali/flutter_typeahead#553]
### Steps to reproduce

update package to the latest version

### Expected results

pub get should succeed

### Actual results

pub get fails with message: Because flutter_typeahead 5.0.1 depends on pointer_interceptor ^0.9.3+6 and no versions of flutter_typeahead match >5.0.1 <6.0.0, flutter_typeahead ^5.0.1 requires pointer_interceptor ^0.9.3+6.
So, because XXX depends on both flutter_typeahead ^5.0.1 and pointer_interceptor ^0.10.0, version solving failed.

### Package Version

^5.0.1

### Platform

Android, iOS, Web

### Code sample

<details open><summary>Code sample</summary>
```dart
[Paste your code here]
```
</details>

### Logs

<details open><summary>Logs</summary>
```console
[Paste your logs here]
```
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
[Upload media here]
</details>

**Comment by MonsieurZbanowanYY** [comment]
I've created a pull request for this issue, waiting to be approved.
For now, you can update your pubspec.yaml to use my fork:
  ```yaml
flutter_typeahead: #^5.0.1
    git:
      url: https://github.com/MonsieurZbanowanYY/flutter_typeahead.git
```
