### ISSUE TITLE
How to prevent suggestionsCallback while input focus

### ISSUE THREAD

**Issue by Sachinsowri** [AbdulRahmanAlHamali/flutter_typeahead#556]
hi i am using flutter_typeahead: ^5.0.1 
in previous i was used 4.8.0,
there is no issue in 4.8.0 , after update 5.0.1  i have some problem
in this version getImmediateSuggestions parameter removed minCharsForSuggestions remove , 
now how should i prevent suggestionsCallback while input got focus, 
if i return empty list on suggestionsCallback it lead emptybuilder to display no records found . is this correct way.
suggestionsCallback has some api calls to get details from backend,

is any way to solve this issue

**Comment by clragon** [comment]
Hi,
You can either disable the empty builder with `hideOnEmpty`
or customize it to be an empty `SizedBox` while you do not wish to show it.

**Comment by Sachinsowri** [comment]
emptyBuilder needed in my case. will try empty sizedBox.

**Comment by Sachinsowri** [comment]
yes it worked now.

**Comment by clragon** [comment]
They add complexity for niche features that can be achieved without specific code inside of the package.
Therefore, to simplify the package, I have removed them.

**Comment by clragon** [comment]
Hi,

in the latest version 5.1.0 you can now also return `null` inside of the suggestions callback 
to indicate that you do not wish to show the list.

Best regards.
