### ISSUE TITLE
Add Clear button on top of suggestion builder

### ISSUE THREAD

**Issue by kururu-abdo** [AbdulRahmanAlHamali/flutter_typeahead#558]
### Use case

![clear search](https://github.com/AbdulRahmanAlHamali/flutter_typeahead/assets/45058799/3f9970d8-ab2d-47af-9b43-6b4eff077050)

### Proposal

add this button with a callback function , so I can make an HTTP request or remove suggestions from database.

**Comment by clragon** [comment]
Hi @kururu-abdo,

It is not necessary for the package itself to add such a button as you should be able to add it yourself from the outside.

We prefer keeping the package itself slim so it can be maintained easier.

**Comment by kururu-abdo** [comment]
thanks for response
but itemBuilder. has no **index** variable so I can put clear button in the first line

**Comment by clragon** [comment]
You should be able to use the `decorationBuilder` to add extra elements around the list of items.
This can contain both the text `recent searches` as well as the `clear` button.

**Comment by kururu-abdo** [comment]
thanks
