### ISSUE TITLE
[Bug] Properties not found after update

### ISSUE THREAD

**Issue by mdmota** [AbdulRahmanAlHamali/flutter_typeahead#559]
### Steps to reproduce

validator: and getImmediateSuggestions:
How do I use these properties now?

### Expected results

validator: and getImmediateSuggestions:

### Actual results

compile error in validator: and getImmediateSuggestions:

### Package Version

5.0.1

### Platform

Android

### Code sample

 validator: (value) {
                            if (value == null || value.trim().isEmpty) {
                              return 'Selecione o codigo';
                            }
                            if (!CodsHelper.isCodExist(value)){
                              return 'codigo inválido';
                            }
                            if (isEdicao && value != propA!.cod){
                              return 'codigo inválido';
                            }
                            return null;
                          },
 getImmediateSuggestions: false,

### Logs

error: The named parameter 'validator' isn't defined. (undefined_named_parameter at [app_xxx] 
error: The named parameter 'getImmediateSuggestions' isn't defined. (undefined_named_parameter at [app_xxxx]

**Comment by clragon** [comment]
You can use your own TextFormField with its own validator.
Your code shows you have set `getImmediateSuggestions` to false, which was the default behaviour in version 4,
so this does not need any replacement.
