### ISSUE TITLE
[Feature] - Possibility to open suggestion box only when user types a text, not when user clicks on the textfield.

### ISSUE THREAD

**Issue by arthurgiani** [AbdulRahmanAlHamali/flutter_typeahead#560]
### Use case

Using the package on the newest version (5.X.X), the following behavior happens

- The suggestion box opens right after the text field click.

https://github.com/AbdulRahmanAlHamali/flutter_typeahead/assets/45671820/9d82ad43-cd5b-4ce7-b31c-ce82f00ec9a2

### Proposal

- have a 'showSuggestionOnAction' boolean that allows me to only open the suggestion box when there's a value on the textfield.

**Comment by clragon** [comment]
The behaviour you describe is a bit specific for us to add an option.
We would like to keep things general and niche functionality to be added from outside the package.

I have come up with a general solution I believe will enable you to achieve your goal.

In the next version, the `suggestionsCallback` will allow returning `null.`
When it does return `null`, the suggestions box will be hidden.

This allows the user to add any conditions for showing or hiding the box without the package needing to support them directly.
This is also different from the `emptyBuilder` which is only shown when an empty list is returned.
`null` is therefore an explicit instruction for not showing the box.

When the update is released, you can therefore return `null` in your callback when the given pattern is empty.

**Comment by arthurgiani** [comment]
> Hi @arthurgiani,
> 
> Thank you for your issue. The behaviour you describe is a bit specific for us to add an option. We would like to keep things general and niche functionality to be added from outside the package.
> 
> I have come up with a general solution I believe will enable you to achieve your goal.
> 
> In the next version, the `suggestionsCallback` will allow returning `null`. When it does return `null`, the suggestions box will be hidden.
> 
> This allows the user to add any conditions for showing or hiding the box without the package needing to support them directly. This is also different from the `emptyBuilder` which is only shown when an empty list is returned. `null` is therefore an explicit instruction for not showing the box.
> 
> When the update is released, you can therefore return `null` in your callback when the given pattern is empty.
> 
> Let me know if this satisfies your needs. Thank you.

It helps a lot! Thank you!

**Comment by eshfield** [comment]
> In the next version, the `suggestionsCallback` will allow returning `null`.

It will be very helpful

**Comment by clragon** [comment]
this feature has now been released with 5.1.0
