### ISSUE TITLE
[Feature] add "load/reload suggestion" in suggestionsController

### ISSUE THREAD

**Issue by azeunkn0wn** [AbdulRahmanAlHamali/flutter_typeahead#561]
### Use case

in v4.x, I set the `search` in suggestionsCallback to empty (`''`) when the suggestion box just opened, so all the items will be displayed in suggestions, ignoring the value in the text field.

```
...
suggestionsCallback: ((search) {
  if (!wasOpen) {
    search= '';
  }
  return mySuggestionsCallback(search);
}),
...
```

in v5.x, I can't do that anymore since opening the suggestion box will not trigger the suggestionCallback until I change the text field value. It will always show the suggestions that are filtered by `search` value.

### Proposal

Add a way to call a reload of suggestions with the SuggestionsController.

**Comment by clragon** [comment]
Hi,

You can force a reload of the suggestions by setting the list of suggestions on the `SuggestionsController` to `null` manually.
I hope that helps. 

Best regards.

**Comment by clragon** [comment]
Sorry, turns out I am wrong.
As of right now, the package will not refresh your suggestions even when you explicitly tell the controller to do so.

I have fixed this behaviour and in the next minor release, there will also be a `refresh` method available on the suggestions controller that allows you to explicitly trigger a reload.

**Comment by clragon** [comment]
this feature has now been released in version 5.2.0

**Comment by azeunkn0wn** [comment]
thank you

**Comment by consu** [comment]
works like a charm, thx

now this is possible:

```dart
itemBuilder: (context, suggestion) {
        final suggestionsController = SuggestionsController.of<String>(context);
        return ListTile(
          leading: const Icon(Icons.history),
          title: Text(suggestion),
          trailing: IconButton(
            icon: const Icon(Icons.clear),
            onPressed: () {
              _removeSuggestion(suggestion);
              suggestionsController.refresh();
            },
          ),
        );
 },
```
