### ISSUE TITLE
How can I still focus on the textfield when I set suggestion box controller close ?

### ISSUE THREAD

**Issue by SuYungCheng** [AbdulRahmanAlHamali/flutter_typeahead#562]
### Steps to reproduce

1.  I need to hide suggestion box when typing in the textfield.
2. I use onChanged and set  suggestionsBoxController.close() inside.
3. The textfield is unfoucs.

### Expected results

The textfield is still focus, but suggestion box is gone.

### Actual results

The textfield unfocus and suggestion box is gone.

### Package Version

4.6.2

### Platform

iOS

### Code sample

<details open>
<summary>Code sample</summary>

```dart
suggestionsCallback: (pattern) {
                              return cardList;
                            },
...
textFieldConfiguration: TextFieldConfiguration(
                              textAlign: TextAlign.end,
                              onChanged: (value) {
                                _suggestionsBoxController.close();
                              },
```
</details>

### Logs

<details open>
<summary>Logs</summary>

```console
[Paste your logs here]
```
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
[Upload media here]
</details>

**Comment by clragon** [comment]
The `SuggestionsController.close` method allows passing `retainFocus: true` for cases like this.
