### ISSUE TITLE
[Feature] Hide dropdown in certain contexts

### ISSUE THREAD

**Issue by darkfrog26** [AbdulRahmanAlHamali/flutter_typeahead#563]
### Use case

I'm using this module to provide context-based results, so under certain circumstances, I don't want the dropdown to appear at all. If I return an empty List, it says no results but still shows the dropdown.

### Proposal

If `null` was a valid response for `suggestionsCallback` it would offer a convenient way to specify that no dropdown should appear.

**Comment by clragon** [comment]
Duplicate of #560
