### ISSUE TITLE
[Bug] TypeAheadField with 'direction' property set to VerticalDirection.up is not focused.

### ISSUE THREAD

**Issue by yj-abe** [AbdulRahmanAlHamali/flutter_typeahead#565]
### Steps to reproduce

1.  Write a program like the following.

```dart
      Column(
        children: [
          TextFormField(
            textInputAction: TextInputAction.next,
          ),
          TypeAheadField<String>(
            direction: VerticalDirection.up,
            itemBuilder: (context, value) {
              return Text(value);
            },
            onSelected: (value) {},
            suggestionsCallback: (search) {
              return ['test'];
            },
          ),
        ],
      ),
```

2.  Enter text in the first TextFormField and click the `next` button on the keyboard.

### Expected results

Focus moves to next TypeAheadField.

### Actual results

TypeAheadField is not focused.
If I set `direction` of TypeAheadField to VerticalDirection.down, it works fine.

### Package Version

5.1.0

### Platform

Android, iOS

### Code sample

<details open>
<summary>Code sample</summary>

```dart
      Column(
        children: [
          TextFormField(
            textInputAction: TextInputAction.next,
          ),
          TypeAheadField<String>(
            direction: VerticalDirection.up,
            itemBuilder: (context, value) {
              return Text(value);
            },
            onSelected: (value) {},
            suggestionsCallback: (search) {
              return ['test'];
            },
          ),
        ],
      ),
```
</details>

### Logs

<details open>
<summary>Logs</summary>

nothing
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
nothing
</details>

**Comment by clragon** [comment]
Reproducible on 5.1.0

**Comment by clragon** [comment]
This issue is most likely related to #579 and will be fixed when the changes there are implemented.
Please follow that issue instead. Thank you!
