### ISSUE TITLE
[Bug] clearing text controller triggers suggestions callback even when closed

### ISSUE THREAD

**Issue by Aa11220** [AbdulRahmanAlHamali/flutter_typeahead#567]
### Steps to reproduce

- Call clear on the attached TextEditingController
- Observe calls to suggestions callback even when the suggestions box is closed

### Expected results

no unnecessary calls are made 

### Actual results

calls are made even when not necessary

### Package Version

 5.1.0 

### Platform

Android

### Code sample

<details open>
<summary>Code sample</summary>

```dart
 N/A
```
</details>

### Logs

<details open>
<summary>Logs</summary>

```console
[Paste your logs here]
```
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
[Upload media here]
</details>

**Comment by clragon** [comment]
Thank you for your issue.
In the next release, the `suggestionsCallback` will only ever be called if the suggestions box is open at the time.

**Comment by clragon** [comment]
a fixed has now been released in version 5.2.0
