### ISSUE TITLE
[Feature] While Using ItemBuilder It Would Be Great If We Could Get Index 

### ISSUE THREAD

**Issue by Dev-Adnani** [AbdulRahmanAlHamali/flutter_typeahead#569]
### Use case

Suppose at the end of list i want to show a add option to user and on clicking that user could add data to existing list

### Proposal

Adding index option to make each item build differently

**Comment by clragon** [comment]
Hi,

Thank you for your proposal. I dont think it would be necessary to add an index to the item builder, especially since this would be a breaking change. You can figure out the index of each item via the suggestions controller:

```dart
itemBuilder: (context, suggestion) {
  final suggestionsController = SuggestionsController.of<String>(context);
  final index = suggestionsController.suggestions.indexOf(suggestion);
  // ...
}
```

I hope that satisfies your usecase. 
Best regards!

**Comment by Dev-Adnani** [comment]
Okay Quick Hack If Someone wants to achieve this , in my list i added 1-2 variables and used them to built a different view accordingly
