### ISSUE TITLE
[Bug] I updated from 4.8.0 to 5.2.0. The code is compiling but the list of suggestions is not being displayed.

### ISSUE THREAD

**Issue by mdmota** [AbdulRahmanAlHamali/flutter_typeahead#574]
### Steps to reproduce

When typing or entering the screen the list should appear.

### Expected results

When typing or entering the screen the list should appear.

### Actual results

Does not display suggestions when entering the screen and when typing

### Package Version

5.2.0

### Platform

Android

### Code sample

```
Expanded(
  child: TypeAheadField<MyObject>(
	builder: (context, controller, focusNode) {
	  return TextFormField(
		controller: this._txtController,
		autofocus: true,
		enableSuggestions: false,
		enabled: isEnabledAutocomplete,
		decoration: InputDecoration(
		  labelText: 'Valor',
		  hintText: 'Digite e escolha',
		),
		validator: (value) {
		  if (value == null || value.trim().isEmpty) {
			return 'Selecione o valor';
		  }
		 
		  return null;
		},
	  );
	},
	emptyBuilder: (context) {
	  return Padding(
		padding: const EdgeInsets.all(8.0),
		child: Text("Nenhum item encontrado"),
	  );
	},
	suggestionsCallback: (pattern) {
	  return MyHelper.getSuggestions(pattern);
	},
	itemBuilder: (context, MyObject suggestion) {
	  return Container(
		child: Padding(
		  padding: const EdgeInsets.all(11.0),
		  child: Row(
			crossAxisAlignment: CrossAxisAlignment.center,
			children: [
			  Text(suggestion.itemDesc!),
			  SizedBox(
				width: 8,
			  ),
			  Text(
				"(${suggestion.tipo == Tipo.A ? "A" : suggestion.tipo!})",
				style: TextStyle(fontSize: 10),
			  )
			], //subtitle: ,
		  ),
		),
	  );
	},
	onSelected: (MyObject suggestion) {
	  _txtController.text = suggestion.desc!;
	  _onSubmittedAutocomplete(suggestion);
	},
  ),
),
```

### Logs

<details open>
<summary>Logs</summary>

```console
[Paste your logs here]
```
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
[Upload media here]
</details>

**Comment by clragon** [comment]
Please refer to the [FAQ](https://github.com/AbdulRahmanAlHamali/flutter_typeahead?tab=readme-ov-file#my-suggestions-arent-changing-when-i-type). Thank you!

**Comment by clragon** [comment]
It sounds like you are trying to figure out how to achieve state managment. 
The respository issues section is primarily for errors in the package or feature suggestions.
If you need support with your code, please check out the [community resources](https://discord.gg/rflutterdev) instead.

**Comment by clragon** [comment]
I am sorry, I dont quite understand what you mean.
If you need further assitance unrelated to package issues, please check out the [community resources](https://discord.gg/rflutterdev) instead.
