### ISSUE TITLE
when adding more typeahead field into one page iOS app crashing [Bug] 

### ISSUE THREAD

**Issue by aju-annaseem** [AbdulRahmanAlHamali/flutter_typeahead#575]
### Steps to reproduce

1. add more typeahead fields into one page
2. run the app on iOS

### Expected results

not take too much memory

### Actual results

taking too much memory and app crashes.

### Package Version

5.2.0

### Platform

iOS

### Code sample

<details open>
<summary>Code sample</summary>

```dart
[Paste your code here]
```
</details>

### Logs

<details open>
<summary>Logs</summary>

```console
[Paste your logs here]
```
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
[Upload media here]
</details>

**Comment by clragon** [comment]
Thank you for your issue. This does not sound like an issue that lies within our package. 
I assume this might be a behaviour that is related to the framework itself. 
Please post a issue with crash logs etc on the flutter repository if this perists. Thank you!
