### ISSUE TITLE
Allow Stream type return instead of Future for suggestionsCallback?

### ISSUE THREAD

**Issue by sjmcdowall** [AbdulRahmanAlHamali/flutter_typeahead#58]
In a different project we are using Firestore (ugh) -- which deals with Streams .. its pretty similar to Futures ..but .. not exactly the same LOL.  Currently we allow a Future to be passed in to the suggestionsCallback ... I am wondering if we should also allow instead a Stream type thing in order for those sorts of data "streams" to be used. 

I think, in the end, that the result of a Future being done and a Stream being "done" would yield the same data that could be fed into the Builder function .. <shrug> 

As a work around of course the programmer could encapsulate the Stream logic and just present (setState) to TypeAhead the completed list and not pass a Stream or Future .. but for completeness with Streams seemingly taking over the planet this maybe good.  May also help in the BLoC stuff since that is all Stream based (well most implementations I've seen) although not exactly sure about the last.

**Comment by valebar** [comment]
Try this:
`suggestionsCallback: (pattern) async {
                          testBloc.dispatch(SearchEvent(
                            searchTokens: pattern.split(' ')));
                          List<String> results;
                          await for (var state in testBloc.state) {
                            if (state is SearchStateSuccess) {
                              results = state.items;
                              break;
                            }
                          }
                          return results;
                        }`

**Comment by MoacirSchmidt** [comment]
@valebar , thanks for you suggestion but it is a workaround like @sjmcdowall mentioned before. 

With streams (or StreamBuilder), the suggestionList could be dynamically updated from local or remote queries assynchronously

**Comment by michcio53** [comment]
any news?
