### ISSUE TITLE
How can i give the hint text and style 

### ISSUE THREAD

**Issue by GorHarshu** [AbdulRahmanAlHamali/flutter_typeahead#581]
### Use case

i want to assign the hint text and style in this how can i give can you please guide me in that

### Proposal

i am using this version  flutter_typeahead: ^5.2.0

**Comment by clragon** [comment]
Please see the documentation for [TextField](https://api.flutter.dev/flutter/material/TextField-class.html)

**Comment by GorHarshu** [comment]
it is not working what is your property there has an issue in decoaration please chehck you pakage

**Comment by clragon** [comment]
TypeAheadField does no longer control the properties of the TextField you are using. Hint text and Text style are part of the TextField's parameters. You pass the TextField you want to the `builder` function of the TypeAheadField.
