### ISSUE TITLE
[Bug] Adding the TypeAhead widget inside a datatable breaks the flow when using keyboard navigation

### ISSUE THREAD

**Issue by ammar629** [AbdulRahmanAlHamali/flutter_typeahead#582]
### Steps to reproduce

1. Create a Datatable widget
2. Assign the typeahead widget to more than one DataColumn cell
3. Traverse the widgets with tab key

### Expected results

Tab traversal has to be in the order of creation of widgets (Flutter framework default behavior)

### Actual results

The tab key traversal excludes some of the widgets from focus

### Package Version

5.2.0

### Platform

Windows

### Code sample

<details open>
<summary>Code sample</summary>

```dart
        return Padding(
          padding: const EdgeInsets.symmetric(vertical: 8.0, horizontal: 4.0),
          child: TypeAheadField<dynamic>(
            focusNode: _node,
            controller: myTextController,
            builder: (context, controller, focusNode) {
              return SizedBox(
                height: 40,
                child: AbsorbPointer(
                  absorbing: widget.readOnly,
                  child: TextField(
                    controller: controller,
                    focusNode: focusNode,
                    readOnly: widget.readOnly,
                    style: Theme.of(context).textTheme.labelLarge,
                    decoration: getInputDecoration(
                        context,
                        invalidate,
                        widget.dataTableLayout,
                        widget.fieldName,
                        widget.labelText),
                  ),
                ),
              );
            },
            suggestionsCallback: (search) async => searchStr(search, widget),
            itemBuilder: itemBuilderCallback,
            onSelected: _onSelectedCallback,
          ),
        );
      },
    );
```
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/AbdulRahmanAlHamali/flutter_typeahead/assets/33799463/d6e8f64d-9f72-4e7f-bb8a-239f7cfece2c

</details>

**Comment by clragon** [comment]
Thank you for your issue. 
This bug is most probably related to #579
The current way we do selected items in the suggestions box is most likely intefering with the focus travel. 
For updates, please follow that issue instead.

**Comment by ammar629** [comment]
Sure thanks for your response
