### ISSUE TITLE
[Bug] Keyboard up arrow skips multiple items in list on desktop

### ISSUE THREAD

**Issue by pstrode** [AbdulRahmanAlHamali/flutter_typeahead#583]
### Steps to reproduce

1. Build and run the example project on Windows or Linux desktop.
2. Use keyboard arrow down to navigate four or five items the list.
4. Use keyboard arrow up to navigate back up the list.

### Expected results

When using keyboard arrow up, it should select the item directly above the current item.

### Actual results

When using keyboard arrow up, the selected item in the list jumps _two_ up instead of the expected one.
Keyboard arrow down works as expected.

### Package Version

5.1.0 - 81c9628

### Platform

Windows, Linux

**Comment by clragon** [comment]
Thank you for your issue.
This bug is another manifestation of the current way the package tracks focus.
We are looking to fix this in #579. please follow that issue instead. Thank you!
