### ISSUE TITLE
[Bug] - Clear Suggestions Cache

### ISSUE THREAD

**Issue by tiagomn** [AbdulRahmanAlHamali/flutter_typeahead#588]
### Steps to reproduce

Hi Guys, I migratted from 4x to 5x and Im getting an issue regarding suggestions cache. I know it's  new feature, but for us it doesn't make sense, we already handle the code to call suggestionsCallback even when it's empty to get our default list and not the cached one. I called suggestionscontroller.refresh() when user clear the textfield but it's not working

### Expected results

I suggest to have a flag if I want or not cache the values.

### Actual results

Getting cache entries on suggestions but we don't want it.

### Package Version

5.2.0

### Platform

Android

### Code sample

<details open>
<summary>Code sample</summary>

```dart
//Not necessary
```
</details>

### Logs

<details open>
<summary>Logs</summary>

```console
[Paste your logs here]
```
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
[Upload media here]
</details>

**Comment by bzkrterdm** [comment]
It should be consider
