### ISSUE TITLE
Is there a way to show suggestions box when textfield is empty?

### ISSUE THREAD

**Issue by DCrow** [AbdulRahmanAlHamali/flutter_typeahead#59]
Sometimes when I have a few items(2-5) to search from, I want to show all of those items, so that I don't have to enter any text.
Something similar can be achieved by typing a letter and deleting it. 
Is this possible?

**Comment by KaYBlitZ** [comment]
Hi, I believe there is a getImmediateSuggestions property. Have you tried
that?

**Comment by DCrow** [comment]
@KaYBlitZ Thank you! Just what I wanted
