### ISSUE TITLE
[Bug] TextInputAction.next doesn't work properly

### ISSUE THREAD

**Issue by azeunkn0wn** [AbdulRahmanAlHamali/flutter_typeahead#594]
### Steps to reproduce

1. Tap on first textfield
2. press Enter (next, focus on typeAhead field)
3. press Enter (next, focus on last text field)

### Expected results

should focus to the next textfield on pressing enter/next button on keyboard

### Actual results

the suggestion box is preventing the app to focus to the next textfield.

Cases: 

When suggestion direction is up: 
- changing focus from 1st text field to typeAhead field is blocked by suggestion box, even if the suggestion box is not visible.
- changing from typeAhead field to the last text field is working

When suggestion direction is down: 
- changing focus from 1st text field to typeAhead is working.
- changing from typeAhead field to the last text field is blocked by suggestion box.

 

### Package Version

5.2.0

### Platform

Android, iOS

### Code sample

<details open>
<summary>Code sample</summary>

```dart
Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const TextField(
              textInputAction: TextInputAction.next,
            ),
            TypeAheadField(
              itemBuilder: (BuildContext context, value) {
                return Text(value.toString());
              },
              onSelected: (_) {},
              suggestionsCallback: (search) {
                return [
                  'item1',
                  'item2',
                ];
              },
              autoFlipDirection: true,
              autoFlipMinHeight: 1000,
              builder: (context, controller, focusNode) {
                return TextField(
                  focusNode: focusNode,
                  textInputAction: TextInputAction.next,
                );
              },
            ),
            const TextField(
              textInputAction: TextInputAction.next,
            ),
          ],
        ),
```
</details>

**Comment by clragon** [comment]
Thank you for your issue..
For resolution, please track #579 instead, where the focus system of the package is being discussed and rewritten.
