### ISSUE TITLE
[Bug] Project won't build on latest version of Flutter 3.24.0 (due to pointer interceptor issue)

### ISSUE THREAD

**Issue by roly151** [AbdulRahmanAlHamali/flutter_typeahead#599]
### Steps to reproduce

1. Try to run a project on Flutter 3.24.0

### Expected results

Project should run

### Actual results

Project build ends with error: Plugin pointer_interceptor:ios provides an implementation for pointer_interceptor_platform_interface and also references a default implementation for pointer_interceptor_ios, which is currently not supported. Ask the maintainers of pointer_interceptor to either remove the implementation via `implements: pointer_interceptor_platform_interface` or avoid referencing a default implementation via `platforms: ios: default_package: pointer_interceptor_ios`.

### Package Version

5.2.0

### Platform

Android

### Code sample

<details open>
<summary>Code sample</summary>

```dart
[Paste your code here]
```
</details>

### Logs

<details open>
<summary>Logs</summary>

```console
[Paste your logs here]
```
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
[Upload media here]
</details>

**Comment by mtrfnvwork** [comment]
Try to execute the following command:
`flutter pub upgrade pointer_interceptor`

**Comment by clragon** [comment]
I cannot seem to reproduce this issue. 
Please follow the advice above and if that doesnt work, notify us. 
Thanks!
