### ISSUE TITLE
Scroll suggestions

### ISSUE THREAD

**Issue by leisim** [AbdulRahmanAlHamali/flutter_typeahead#6]
Hi,

Should it be possible to scroll the suggestions?
If yes, it does not work for me :/
If no, this would be a really useful feature...

Thanks ;)

**Comment by AbdulRahmanAlHamali** [comment]
Hello Simon,

Yes, I added this ability in version 0.3.0

To do that, you need to specify the `constraints` property in the `suggestionsBoxDecoration`, and specify the maxHeight that suits you:

```
suggestionsBoxDecoration: SuggestionsBoxDecoration(
  constraints: BoxConstraints(
    maxHeight: 200.0
  )
),
```
In this example, if your entries don't fit within 200 pixels, the suggestions box will become scrollable.

Let me know if that solves it

**Comment by leisim** [comment]
Awesome, thank you!
