### ISSUE TITLE
Allow for the setting of a default String in the Text Field

### ISSUE THREAD

**Issue by josephlam1984** [AbdulRahmanAlHamali/flutter_typeahead#60]
Is there a way we could set a default String (and a hint) in the Text field?

**Comment by KaYBlitZ** [comment]
Have you tried this:
```
textFieldConfiguration: TextFieldConfiguration(
          decoration: InputDecoration(
            hintText: 'HINT_HERE',
          ),
        ),
```

**Comment by sjmcdowall** [comment]
Hint yes -- how exactly do you see the default string in the case of a search typeahead type field? You could always set it in the text controller (assuming you assign a TextController) ?? I think in a Form version you can set an initial value as well .. 

But -- that assumes what you mean by "default" value .. If you would show / describe some use cases/user stories for examples that would help .

**Comment by sjmcdowall** [comment]
Closing due to no follow up on suggestion
