### ISSUE TITLE
[Bug] OnSelected function not working in version:5.2.0

### ISSUE THREAD

**Issue by imshibl** [AbdulRahmanAlHamali/flutter_typeahead#600]
### Steps to reproduce

1. Create a list of string
2. Use the created list of string with the flutter_typehead for auto compeletion suggestions
3. try printing or performing any operations in the required onSelected function

### Expected results

This code is supposed to print the value to the debug console. but it's not working. so i have used a gesture detector in the itemBuilder,that's way its working.

### Actual results

The onSelected function is not invoking when pressed on the suggestion values

### Package Version

5.2.0

### Platform

Android, iOS

### Code sample

<details open>
<summary>Code sample</summary>

```dart
TypeAheadField<String>(
                  controller: languageTextEditingController,
                  itemBuilder: (context, language) {
                    return GestureDetector(
                      onTap: () {
                        if (!selectedLanguages.contains(language)) {
                          ref.read(selectedLanguageProvider.notifier).state = [
                            ...selectedLanguages,
                            language,
                          ];
                        }

                        languageTextEditingController.clear();
                      },
                      child: ListTile(
                        title: Text(language),
                      ),
                    );
                  },
                  builder: (context, controller, focusNode) {
                    return TextField(
                      controller: controller,
                      focusNode: focusNode,
                      decoration: InputDecoration(
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(15),
                        ),
                        labelText: 'Language',
                      ),
                    );
                  },
                  emptyBuilder: (context) => const Padding(
                    padding: EdgeInsets.all(8.0),
                    child: Text(
                      'No languages found',
                      style: TextStyle(fontSize: 16),
                    ),
                  ),
                  suggestionsCallback: (search) {
                    return languageListProvider
                        .where(
                          (language) => language.toLowerCase().contains(
                                search.toLowerCase(),
                              ),
                        )
                        .toList();
                  },
                  onSelected: (value) {
                    //not working on tap
                    print("onSelected: $value");
                  },
                ),
```
</details>

### Logs

<details open>
<summary>Logs</summary>

```console
[Paste your logs here]
```
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
[Upload media here]
</details>

**Comment by clragon** [comment]
Hi,

please do not add a GestureDetector into the item builder of the typeahead field.
The typeahead field will already wrap your items with an InkWell that will call onSelected. 


best regards.

**Comment by imshibl** [comment]
Hey, Thanks for the response.

Yah i understand. However i added GestureDetector because onSelected is not
invoking

**Comment by clragon** [comment]
Ah, right. It's because your code contains a ListTile, which swallows all pointer events, even when it has no onTap itself.
You can either add the onTap to the ListTile and call select yourself by grabbing the SuggestionsController from context, or you can use an IgnorePointer around your ListTile, which is easier, but prevents _all_ taps. In case you have extra elements inside your ListTile that should not trigger a selection, then you must to the former.

**Comment by imshibl** [comment]
Ok, thanks for the clarification.

**Comment by sharkfabri** [comment]
I confirm, version 5.2.0 ignores onSelect, with or without onTap, with or without adding a IgnorePointer as parent Widget. 
Rolling back to version 5.1.0 works as a charme.
