### ISSUE TITLE
Does it only support IOS and web platforms? ？

### ISSUE THREAD

**Issue by KitStarLee** [AbdulRahmanAlHamali/flutter_typeahead#601]
### Steps to reproduce

。。。

### Expected results

。。。

### Actual results

。。。

### Package Version

5.2.0

### Platform

Android, iOS, Windows, Linux, macOS, Web

### Code sample

<details open>
<summary>Code sample</summary>

```dart
[Paste your code here]
```
</details>

### Logs

<details open>
<summary>Logs</summary>

```console
[Paste your logs here]
```
</details>

### Screenshots or Video

![image](https://github.com/user-attachments/assets/550e09d9-c624-4cd5-bc43-44b3ac80ac61)

**Comment by clragon** [comment]
The package supports all platforms. This appears to be a display issue only. We'll investigate how to fix that.
