### ISSUE TITLE
[Bug] A problem occurred configuring project ':flutter_keyboard_visibility'.

### ISSUE THREAD

**Issue by tajjacob** [AbdulRahmanAlHamali/flutter_typeahead#608]
### Steps to reproduce

Got this error when run on android after I migrate to latest gradle 

### Expected results

can run on android

### Actual results

got error

### Package Version

4.8.0

### Platform

Android

### Code sample

<details open>
<summary>Code sample</summary>

```dart
[Paste your code here]
```
</details>

### Logs

<details open>
<summary>Logs</summary>

```console
[   +3 ms] FAILURE: Build failed with an exception.
[   +1 ms] * What went wrong:
[        ] A problem occurred configuring project ':flutter_keyboard_visibility'.
[        ] > Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
[        ]    > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

```
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
[Upload media here]
</details>

**Comment by BunnyBuddy** [comment]
It's easily solvable try and use dependency_override with flutter_keyboard_visibility's latest version. If that doesn't help, add this code in your project/android/build.gradle file,

```
allprojects {
    repositories {
        google()
        mavenCentral()
    }
    subprojects {
        afterEvaluate { project ->
            if (project.hasProperty('android')) {
                project.android {
                    if (namespace == null) {
                        namespace project.group
                    }
                }
            }
        }
    }
}
```
