### ISSUE TITLE
[Feature] Bring back minCharsForSuggestions property

### ISSUE THREAD

**Issue by bahadirarslan** [AbdulRahmanAlHamali/flutter_typeahead#609]
### Use case

I have been using your library for 2 years and it was a perfect fit for my project. But you removed `minCharsForSuggestions` property with version 5.0.0 and suggested checking string length at `suggestionsCallback`.

If I was using this widget in one screen it could be manageable but I am using this widget almost in 20 different widgets so I created the AutoCompleteTextField widget for myself which is using your widget.

This means I had to add dozens of screens' char length check to show suggestions. Instead of  doing this chore, I wrote below code
`suggestionsCallback: (search) => search.isNotEmpty && search.length >= 3 ? widget.suggestionsCallback(search) : [],`

If it was enough, this could be OK, but it is not. The `minCharsForSuggestions` value also hide emptyBuilder if the value was below the threshold. With this new implementation, when the field gets focus, it automatically shows emptyBuilder, which is unwanted because the user hasn't typed anything yet.

Now I am trying to find a way to bypass this behaviour.

### Proposal

Bring back `minCharsForSuggestions` property like version 4.x

**Comment by BunnyBuddy** [comment]
Have you tried hideOnEmpty property?

> ### Use case
> I have been using your library for 2 years and it was a perfect fit for my project. But you removed `minCharsForSuggestions` property with version 5.0.0 and suggested checking string length at `suggestionsCallback`.
> 
> If I was using this widget in one screen it could be manageable but I am using this widget almost in 20 different widgets so I created the AutoCompleteTextField widget for myself which is using your widget.
> 
> This means I had to add dozens of screens' char length check to show suggestions. Instead of doing this chore, I wrote below code `suggestionsCallback: (search) => search.isNotEmpty && search.length >= 3 ? widget.suggestionsCallback(search) : [],`
> 
> If it was enough, this could be OK, but it is not. The `minCharsForSuggestions` value also hide emptyBuilder if the value was below the threshold. With this new implementation, when the field gets focus, it automatically shows emptyBuilder, which is unwanted because the user hasn't typed anything yet.
> 
> Now I am trying to find a way to bypass this behaviour.
> 
> ### Proposal
> Bring back `minCharsForSuggestions` property like version 4.x

**Comment by bahadirarslan** [comment]
> Have you tried hideOnEmpty property?
> 
> 
> 
> > ### Use case
> 
> > I have been using your library for 2 years and it was a perfect fit for my project. But you removed `minCharsForSuggestions` property with version 5.0.0 and suggested checking string length at `suggestionsCallback`.
> 
> > 
> 
> > If I was using this widget in one screen it could be manageable but I am using this widget almost in 20 different widgets so I created the AutoCompleteTextField widget for myself which is using your widget.
> 
> > 
> 
> > This means I had to add dozens of screens' char length check to show suggestions. Instead of doing this chore, I wrote below code `suggestionsCallback: (search) => search.isNotEmpty && search.length >= 3 ? widget.suggestionsCallback(search) : [],`
> 
> > 
> 
> > If it was enough, this could be OK, but it is not. The `minCharsForSuggestions` value also hide emptyBuilder if the value was below the threshold. With this new implementation, when the field gets focus, it automatically shows emptyBuilder, which is unwanted because the user hasn't typed anything yet.
> 
> > 
> 
> > Now I am trying to find a way to bypass this behaviour.
> 
> > 
> 
> > ### Proposal
> 
> > Bring back `minCharsForSuggestions` property like version 4.x
> 
> 
> 
> 

Yes, I tried but it is not suitable for my case. Because I show add new button if the suggestion list is empty. If I use hideOnEmpty option nothing is shown. minCharsForSuggestions was perfect, why it was removed at all?

**Comment by kirpit** [comment]
I had the same feeling when first upgraded because of a similar use case; I don't want `emptyBuilder` to display before the 3rd char... But if you pay close attention, the return type is `List<T>?` - which means it can be `null` instead of an empty array 😉

**Comment by bahadirarslan** [comment]
> I had the same feeling when first upgraded because of a similar use case; I don't want `emptyBuilder` to display before the 3rd char.. But if you pay close attention, the return type is `List<T>?` - which means you can return `null` instead of an empty array 😉

Nice catch :)
Returning null solved my problem. But still I think it was not necessary to remove minCharsForSuggestion

**Comment by clragon** [comment]
We have intentionally removed this feature to reduce package complexity and instead empower users through other means, 
like returning `null` for any reason. Because of that, it is unlikely this feature will return.
