### ISSUE TITLE
Keyboard covering suggestions on direction up

### ISSUE THREAD

**Issue by KaYBlitZ** [AbdulRahmanAlHamali/flutter_typeahead#62]
Might have to adjust offset on the fly as well to move the suggestions box to start just right above keyboard.
![simulator screen shot - iphone xs max - 2019-03-01 at 11 01 23](https://user-images.githubusercontent.com/5499214/53650038-96957a80-3c11-11e9-97dc-6ca44af02acb.png)

**Comment by sjmcdowall** [comment]
Fixed in 1.1.0
