### ISSUE TITLE
Suggestions box width not adjusting during orientation change

### ISSUE THREAD

**Issue by KaYBlitZ** [AbdulRahmanAlHamali/flutter_typeahead#63]
I thought this was working before, but I guess not. Need to adjust width during orientation changes.
![simulator screen shot - iphone xs max - 2019-03-01 at 10 55 33](https://user-images.githubusercontent.com/5499214/53650138-da887f80-3c11-11e9-818f-59548f7587be.png)

**Comment by sjmcdowall** [comment]
Fixed in 1.1.0
