### ISSUE TITLE
Allow for "onFieldSubmitted" event.

### ISSUE THREAD

**Issue by KanivaTimber** [AbdulRahmanAlHamali/flutter_typeahead#67]
In my case when using this widget the user might not want to use a given suggestion. In the case where they do not, I would like to take a different action than when using the "onSuggestionSelection" event and use something like TextFormField has which is a "onFieldSubmitted" event.

**Comment by KaYBlitZ** [comment]
This is already implemented. It is just under a different name, onSubmitted. So all TextField parameters are under textFieldConfiguration like so:

```
TypeAheadFormField(
              textFieldConfiguration: TextFieldConfiguration(
                textInputAction: TextInputAction.next,
                onSubmitted: (text) {
                  // do what you need to do here like focus on another text field
                },
              ),
),
```

**Comment by KanivaTimber** [comment]
Awesome, thank you for the info!
