### ISSUE TITLE
Throttle suggestionsCallback future ..

### ISSUE THREAD

**Issue by sjmcdowall** [AbdulRahmanAlHamali/flutter_typeahead#69]
This is more of a question -- although we are seeing bad behavior (keyboard not properly interacting in iOS Simulator) with our current (probably broken) behavior.

We have found ourselves in a situation where a user that keeps on type (slowly) is activating the getSuggestions callback multiple times BEFORE the previous one has completed.  This is an expensive DB hit for us ..and eventually our DB goes to never never land .. so we want to make sure the caller only ever has ONE DB query active .. and when the previous one is done .. we take the LAST pattern given and do a new query on that .. 

I was wondering if anyone had any ideas on an approach or maybe has done something similar?  I don't see where this logic is built-in anyway to the core Typeahead logic... ? (looking at you @KaYBlitZ ! LOL)

**Comment by KaYBlitZ** [comment]
It's this code here:
```
this._debounceTimer = Timer(widget.debounceDuration, () async {
        if (this._debounceTimer.isActive) return;

        // If already closed
        if (!this.mounted) return;

        await this._getSuggestions();
      });
```
You can pass in a Duration object into TypeAhead's `debounceDuration` with a longer wait time. From what I can see, every time the user types, the `_debounceTimer` is refreshed with the `debounceDuration`. When the user stops typing, after that duration, the suggestions callback is called.

**Comment by sjmcdowall** [comment]
@KaYBlitZ -- Yeah we already did that .. but it's not that sort of throttling -- although it helps.  What happens is that if the debounce is set to a "reasonable" time like 500ms .. but the query takes 2s to run .. we can still get overwhelmed .. I want to "queue" the db calls and ignore the middle calls .. and just do the last call..

Does this make sense?

**Comment by KaYBlitZ** [comment]
That makes sense. Just not sure how to do that off the top of my head right now. Will mull it over later...

**Comment by sjmcdowall** [comment]
Completed in 1.3.0.
