### ISSUE TITLE
Text typed not reflecting in selections

### ISSUE THREAD

**Issue by willvlad** [AbdulRahmanAlHamali/flutter_typeahead#7]
Good widget visually, but not sure if the typeahead functionality is actually working - typeahead normally means when you type a letter, you should only see those entries which have that letter (or a combination), right? 

It seems the formula is not providing that. So in your 2nd example, when you type B for Beirut, you are seeing Rome coming up the list, where B is not even present. Any way of correcting such behaviour?

**Comment by AbdulRahmanAlHamali** [comment]
Hi Will,

Yes, the typeahead widget does not do the fetching of the suggestions for you. It is only a frontend component. It provides you with a function `suggestionsCallback` where it gives you the text typed in the field, and asks you for the suggestions. 

You should, accordingly, provide suggestions based on the typed text. The suggestions could come synchronously from some function that calculates the suggestions, or asynchronously from a remote server. 

In my second example, the function that I provided for `suggestionsCallback` looked at a list and used a string distance algorithm to fetch the 5 closest strings to the typed text. In your case, you can provide any function you see suitable for fetching the suggestions.

I have also opened another [issue](https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/3) in which I am asking for people's opinion, and whether the package could use a backend component. If you have any ideas in this regard, I would be thrilled to hear them!

**Comment by willvlad** [comment]
Hi Abdul, thanks for your prompt response. I think it makes sense to use some function within the plugin to calculate suggestions on the fly with no backend necessary as in most cases the list of suggestions is local. It looks like the string distance algo isn't quite the right function for this calculations. I haven't looked into which functions are normally used in typeaheads. This must have been done by many before. Perhaps some indexof equivalent...

**Comment by AbdulRahmanAlHamali** [comment]
Hmm yeah it might be valuable if we have a pre-existing list on the frontend, to provide some default search functionality. I will look into this and see what is the best way to implement it. 

Thank you for your suggestions, Will!

**Comment by sjmcdowall** [comment]
I don't think this is reasonable -- there are way too many use cases to know exactly the expected behavior if this functionally is "magically" done.  I also disagree that most lists are "hard coded" -- I think most are actually retrievals from backend systems, etc.  For simple "local" lists it shouldn't be too much work to specify a function that returns the exact filter as needed by the application ... Not all people want "leading" filtering (for example).  

I suggest we close this issue for now and re-open if a more compelling case arises.
