### ISSUE TITLE
Can't see items in dialog

### ISSUE THREAD

**Issue by keertipurswani** [AbdulRahmanAlHamali/flutter_typeahead#73]
Even though suggestions are being sent in itemBuilder, items can't be seen. Same code is working if I don't put it inside a dialog.

**Comment by sjmcdowall** [comment]
I think we'll need to see the code and a sample little app showing this.  I've never used this for a Dialog before ..

**Comment by keertipurswani** [comment]
Here is my code, It used to work before. I think it stopped working after I migrated to androidX.

showDialog(
        context: context,
        builder: (BuildContext context) {
          return SimpleDialog(
            children: <Widget>[
              Container(
                  padding: EdgeInsets.all(10.0),
                  child: Row(children: <Widget>[
                    Expanded(
                        child: TypeAheadField(
                      textFieldConfiguration: TextFieldConfiguration(
                        controller: _controller,
                        autofocus: true,
                      ),
                      suggestionsCallback: (pattern) async {
                        return getSuggestions(pattern);
                      },
                      itemBuilder: (context, suggestion) {
                        return ListTile(
                          title: Text(suggestion),
                        );
                      },
                      onSuggestionSelected: (suggestion) {
                        _controller.text = suggestion;
                      },
                    ))
                  ])),
            ],
          );
        });

**Comment by KaYBlitZ** [comment]
@keertipurswani Are you not seeing the suggestions list at all? I have never tried putting the TypeAhead in a dialog, but using the code you posted, I see this:
![Screenshot_1553000813](https://user-images.githubusercontent.com/5499214/54608429-09cb2900-4a27-11e9-9b12-071e229d3ecd.png)
Looks like the suggestions list is showing, but is only as big as the length of the dialog is. If the field is at  the bottom, you might not see anything and would have to try setting `direction` to `AxisDirection.up`

**Comment by keertipurswani** [comment]
Yes I can't see suggestions at all and my list is pretty long (500 suggestions in total). Where can I set the direction? and how can I see at least 4-5 items at once and scroll the rest?

**Comment by KaYBlitZ** [comment]
```
TypeAheadField(
                          direction: AxisDirection.up,
                          suggestionsBoxDecoration: SuggestionsBoxDecoration(
                            constraints: BoxConstraints(
                              maxHeight: 100.0,
                            ),
                          ),
```
Check code above for directionality and setting the height. AFAIK, you can't set the number of items you want to see, only the height.

**Comment by keertipurswani** [comment]
That works. Thanks :)
