### ISSUE TITLE
Multi-selection ?

### ISSUE THREAD

**Issue by sjmcdowall** [AbdulRahmanAlHamali/flutter_typeahead#74]
We have a situation where, after we show a selection list .. we want to keep the list open so the user can click multiple items (and call the appropriate callback) after each one .. and of course refresh the selection list since we've removed the selected item .. :)

It would be slick to keep this going until the onSuggestionsSelected returns a bool "false" or something.. <shrug>  Just thinking out of the box right now..  of course closing the keyboard would close the suggestions box too .. (if option set) .. 

Thoughts?

**Comment by KaYBlitZ** [comment]
Not a fan of this idea. This seems to be extra functionality that is over the scope of a simple autocomplete textbox. I think something like that would be better being implemented separately.

**Comment by sjmcdowall** [comment]
I understand your point -- although I would say we've gone way beyond a "simple autocomplete" widget quite a while ago. :)   I am giving it a SWAG but don't you think maybe 90% of the code base for a multi-select and this (since the underlying requirements are exactly the same interns of pattern / suggestion box/ etc) widget would be in common?  

I may try a little implementation of a "multiSelect: bool" option this weekend to see how horrid it may be.

**Comment by sjmcdowall** [comment]
Closing since it's not a highly (at all) idea and I think @KaYBlitZ has the right of it.
