### ISSUE TITLE
Keyboard blocks overlay

### ISSUE THREAD

**Issue by zacwolfe** [AbdulRahmanAlHamali/flutter_typeahead#79]
For some screens with variable number of fields, the placement of an auto-complete field may not be known at design time.  It would be great if the direction could adjust if there weren't enough room in the desired direction.  In this screenshot you can see that the overlay of suggestions is completely obscured:

![Simulator_Screen_Shot_-_iPhone_X_-_2019-03-22_at_16_10_10](https://user-images.githubusercontent.com/2164736/54857816-8c214a80-4cbe-11e9-801f-3c1978e784f6.png)

Here the overlay looks ok because the screen is scrolled up:

![Simulator_Screen_Shot_-_iPhone_X_-_2019-03-22_at_16_12_44](https://user-images.githubusercontent.com/2164736/54857832-993e3980-4cbe-11e9-8aac-0dbab722827f.png)

**Comment by zacwolfe** [comment]
I have a fix that is working for me, I'll open a PR

**Comment by KaYBlitZ** [comment]
This is definitely an interesting feature. I'll take a look at the PR when you are able to submit it.

**Comment by zacwolfe** [comment]
Thanks Kenneth! I'd like to submit the PR but I don't seem to have the
requisite privileges to push my dev branch.  Is this something you can help
me with?

**Comment by sjmcdowall** [comment]
You don't need permissions to submit a PR .. the PR should be from your forked develop branch to the main develop branch .. 

Then either Kenneth or I will take it from there and do the merge / release to master ..

**Comment by KaYBlitZ** [comment]
Did you fork the repository? You have to fork it first and make the changes
in your fork. You can then submit a PR from your fork to this repository.

**Comment by sjmcdowall** [comment]
AND -- make sure when you do what @KaYBlitZ says you modify the DEVELOP branch not the master.. :)

**Comment by zacwolfe** [comment]
Done

**Comment by sjmcdowall** [comment]
Fixed in #80 and published
