### ISSUE TITLE
Return suggestions in "row" style versus "column" style option?

### ISSUE THREAD

**Issue by sreyseng** [AbdulRahmanAlHamali/flutter_typeahead#82]
Currently, suggestions return as a list. Any plans to make it so that the suggestions can return as a "row" of suggestions, and wrap around as needed?

For example, instead of:

```
[Item]
[Item2]
[Item3
[Item]
[Item2]
[Item3
```

It is:

```
[Item] [Item2] [Item3] ...
...
```

**Comment by sjmcdowall** [comment]
Would this be more like rendering a [GridView](https://docs.flutter.io/flutter/widgets/GridView-class.html) ??

**Comment by sreyseng** [comment]
I believe so, yes.

**Comment by ova2** [comment]
We have a requirement to render buttons in a GridView manner inside of suggestion box. Is GridView builder supported? Currently, we only can use built-in ListView builder. Right?
