### ISSUE TITLE
Provide a way to get the suggestions when onEditingComplete is called 

### ISSUE THREAD

**Issue by long1eu** [AbdulRahmanAlHamali/flutter_typeahead#89]

**Comment by sjmcdowall** [comment]
I am not sure exactly what you are asking for here... can you give a use case or two on what you are trying to achieve and what you have tried that isn't working?

**Comment by KaYBlitZ** [comment]
You should be returning a list of suggestions in the `suggestionsCallback` section. Can't you just store that and use it in `onEditingComplete`?

**Comment by singlakaran** [comment]
@KaYBlitZ  you return list in onSuggestionSelected , but i want only selected item in list

**Comment by sjmcdowall** [comment]
@singlakaran -- I have no idea why you are or think you are getting a list -- I use this a lot and all I get is the single item that was selected .. what does you code look like?

**Comment by singlakaran** [comment]
@sjmcdowall 
 itemBuilder: (context, suggestion) {
            return ListTile(
              title: UserDetails(
                  name: suggestion['userName'],
                  image: 'https://i.pravatar.cc/300?u=bajsbjas',
                  details: suggestion['userId'],
              ),
            );
          },
          onSuggestionSelected: (suggestion) {
            this._typeAheadController.text = suggestion;
          },

**Comment by sjmcdowall** [comment]
Hint #1 -- you should use types .. the actual callback when you pass in what you do -- is a (dynamic suggestion) .. which is NOT an array but a Map (actually) .. you should do a 

debugPrint(suggestion) in your onSuggestion to see the structure of the map as when passing in a ListTile not sure exactly what you will get back to be honest.. 

but your code will be something like 

```
this._typeAheaderController.text = suggestion['name']  or whatever field you need/want .. 
```

**Comment by singlakaran** [comment]
yeah,i know it return Map, but i get full list in in  onSuggestionSelected suggestion

**Comment by singlakaran** [comment]
thanks man @sjmcdowall
