### ISSUE TITLE
keepSuggestionsOnLoading keeps the box permanently on screen

### ISSUE THREAD

**Issue by SwissCheese5** [AbdulRahmanAlHamali/flutter_typeahead#96]
When you enable keepSuggestionsOnLoading for the field, the box doesn't go away when you press the back button to remove the keyboard which is what is expected. However, at the same time, pressing back again completely exits the app and goes to the home screen, and you can't click away from the box to close it. It's permanently there.

**Comment by KaYBlitZ** [comment]
`keepSuggestionsOnLoading` is true (enabled) by default. Seems to work fine on my side. Disabling it seems to work as well? Can you post the code that seems to be getting stuck?
