### ISSUE TITLE
FlutterError: Looking up a deactivated widget's ancestor is unsafe

### ISSUE THREAD

**Issue by BerkOFF** [AbdulRahmanAlHamali/flutter_typeahead#99]
Suggested change below fixes the problem of accessing context when widget is dismounted
flutter_typeahead-1.5.0/lib/flutter_typeahead.dart:1532
Future<bool> _waitChangeMetrics() async {
 ....
 if ( **widgetMounted && (** MediaQuery.of(context).viewInsets != initial ||
_findRootMediaQuery() != initialRootMediaQuery **)** ) {
return true;
}
...
}

**Comment by KaYBlitZ** [comment]
Merged to develop. Will push to master in the upcoming days. Thanks for improving the code guys!
